

	.FUNCT	INIT-STATUS-LINE
	LESS?	WIDTH,38 \?CND1
	PRINTI	"[Screen too narrow.]"
	CRLF	
	QUIT	
?CND1:	SET	'OHERE,FALSE-VALUE
	SET	'OLD-LEN,0
	SPLIT	1
	SCREEN	S-WINDOW
	HLIGHT	H-INVERSE
	CURSET	1,1
	ICALL2	PRINT-SPACES,WIDTH
	GRTR?	WIDTH,74 \?CND3
	CURSET	1,51
	PRINTI	"Score:"
	CURSET	1,64
	PRINTI	"Moves:"
?CND3:	HLIGHT	H-NORMAL
	SCREEN	S-TEXT
	RTRUE	


	.FUNCT	UPDATE-STATUS-LINE
	SCREEN	S-WINDOW
	HLIGHT	H-NORMAL
	HLIGHT	H-INVERSE
	EQUAL?	HERE,OHERE /?CND1
	SET	'OHERE,HERE
	DIROUT	D-TABLE-ON,SL-TABLE
	ICALL1	SAY-HERE
	DIROUT	D-TABLE-OFF
	CURSET	1,2
	ICALL2	PRINT-SPACES,OLD-LEN
	GET	SL-TABLE,0 >OLD-LEN
	CURSET	1,2
	ICALL1	SAY-HERE
?CND1:	GRTR?	WIDTH,74 \?CCL5
	CURSET	1,58
	PRINTN	SCORE
	PRINTC	32
	CURSET	1,71
	PRINTN	MOVES
	JUMP	?CND3
?CCL5:	DIROUT	D-TABLE-ON,SL-TABLE
	PRINTN	SCORE
	PRINTC	47
	PRINTN	MOVES
	PRINTC	32
	DIROUT	D-TABLE-OFF
	GET	SL-TABLE,0
	ADD	STACK,1
	SUB	WIDTH,STACK
	CURSET	1,STACK
	PRINTN	SCORE
	PRINTC	47
	PRINTN	MOVES
	PRINTC	32
?CND3:	HLIGHT	H-NORMAL
	SCREEN	S-TEXT
	RTRUE	


	.FUNCT	PRINT-SPACES,N,AMT
?PRG1:	GRTR?	N,BLANKS-LEN \?CCL5
	SET	'AMT,BLANKS-LEN
	JUMP	?CND3
?CCL5:	SET	'AMT,N
?CND3:	PRINTT	BLANKS,AMT
	SUB	N,AMT >N
	GRTR?	N,0 /?PRG1
	RTRUE	


	.FUNCT	SAY-HERE,NUM
	ZERO?	LIT? \?CCL3
	PRINTI	"Darkness"
	RTRUE	
?CCL3:	ICALL2	DPRINT,HERE
	GRTR?	WIDTH,74 \TRUE
	CALL1	CANAL-LOC >NUM
	EQUAL?	NUM,10 \?CND6
	PRINTI	", near the "
	EQUAL?	NEARER-DOCK,MY-KIND-OF-DOCK \?CCL10
	PRINTI	"ea"
	JUMP	?CND8
?CCL10:	PRINTI	"we"
?CND8:	PRINTI	"st bank"
?CND6:	LOC	PROTAGONIST
	FSET?	STACK,VEHBIT \TRUE
	ZERO?	DONT-PRINT-VEHICLE \TRUE
	PRINTI	", "
	LOC	PROTAGONIST
	FSET?	STACK,INBIT \?CCL17
	PRINTC	105
	JUMP	?CND15
?CCL17:	PRINTC	111
?CND15:	PRINTC	110
	LOC	PROTAGONIST
	ICALL2	TPRINT,STACK
	RTRUE	


	.FUNCT	INCREMENT-SCORE,BASE,VAR,INC-RANK,CHANGE,DIF
	ZERO?	INC-RANK /?CND1
	INC	'RANK
?CND1:	RANDOM	VAR
	ADD	STACK,BASE >CHANGE
	ADD	BASE,VAR
	SUB	STACK,CHANGE >DIF
	SUB	INT-MAX,DIF >INT-MAX
	SUB	EXT-MAX,INT-MAX
	RANDOM	STACK
	ADD	INT-MAX,STACK >EXT-MAX
	ADD	SCORE,CHANGE >SCORE
	RETURN	SCORE


	.FUNCT	INTDIR-F
	EQUAL?	PRSA,V?BOARD \FALSE
	EQUAL?	P-PRSA-WORD,W?RIDE \FALSE
	IN?	PROTAGONIST,STALLION \?CCL8
	CALL2	DO-WALK,P-DIRECTION
	RSTACK	
?CCL8:	IN?	STALLION,HERE \?CCL10
	CALL2	DO-FIRST,STR?125
	RSTACK	
?CCL10:	PRINT	THERES-NOTHING
	PRINTR	"to ride!"


	.FUNCT	INTNUM-F
	CALL2	ADJ-USED,W?WIFE
	ZERO?	STACK /?CCL3
	EQUAL?	HERE,INNER-HAREM \?PRD6
	ZERO?	MALE \?CCL3
?PRD6:	CALL1	PICKING-WIFE
	ZERO?	STACK \?CCL3
	SET	'P-WON,FALSE-VALUE
	PRINT	YOU-CANT-SEE-ANY
	PRINTR	"wife here!"
?CCL3:	CALL2	ADJ-USED,W?HUSBAND
	ZERO?	STACK /?CCL10
	EQUAL?	HERE,INNER-HAREM \?PRD13
	ZERO?	MALE /?CCL10
?PRD13:	CALL1	PICKING-WIFE
	ZERO?	STACK \?CCL10
	SET	'P-WON,FALSE-VALUE
	PRINT	YOU-CANT-SEE-ANY
	PRINTR	"husband here!"
?CCL10:	EQUAL?	PRSA,V?ANSWER-KLUDGE \?CCL17
	ICALL	PERFORM,V?USE-QUOTES,INTNUM
	RTRUE	
?CCL17:	EQUAL?	P-NUMBER,CHOICE-NUMBER \?CCL19
	IN?	SULTANS-WIFE,HERE \?CCL19
	EQUAL?	PRSO,INTNUM \?CCL24
	ICALL	PERFORM-PRSA,SULTANS-WIFE,PRSI
	RTRUE	
?CCL24:	ICALL	PERFORM-PRSA,PRSO,SULTANS-WIFE
	RTRUE	
?CCL19:	EQUAL?	PRSA,V?PICK,V?ASK-NO-ONE-FOR \?PRD28
	IN?	HAREM-GUARD,HERE /?CTR25
?PRD28:	EQUAL?	PRSA,V?ASK-FOR \?CCL26
	EQUAL?	PRSO,HAREM-GUARD \?CCL26
?CTR25:	CALL2	PICK-WIFE,INTNUM
	RSTACK	
?CCL26:	EQUAL?	HERE,VIZICOMM-BOOTH \FALSE
	EQUAL?	PRSA,V?SET \FALSE
	ICALL2	PERFORM-PRSA,VIZICOMM
	RTRUE	


	.FUNCT	PICKING-WIFE
	EQUAL?	PRSA,V?PICK,V?ASK-NO-ONE-FOR \?CCL3
	IN?	HAREM-GUARD,HERE /TRUE
?CCL3:	EQUAL?	PRSA,V?ASK-FOR \FALSE
	EQUAL?	PRSO,HAREM-GUARD /TRUE
	RFALSE	


	.FUNCT	EACH-OTHER-F
	EQUAL?	PRSI,EACH-OTHER \?CCL3
	ICALL	PERFORM-PRSA,PRSO,PRSO
	RTRUE	
?CCL3:	CALL	NOUN-USED,W?ITSELF,EACH-OTHER
	ZERO?	STACK \FALSE
	SET	'P-WON,FALSE-VALUE
	CALL2	ADJ-USED,W?EACH
	ZERO?	STACK /?CCL8
	ICALL	CANT-USE,W?EACH,TRUE-VALUE
	RTRUE	
?CCL8:	ICALL	CANT-USE,W?OTHER,TRUE-VALUE
	RTRUE	


	.FUNCT	MAN-WOMAN-F,PERSON
	EQUAL?	PRSA,V?FOLLOW \?CCL3
	EQUAL?	FOLLOW-FLAG,4 \?CCL6
	PRINT	DONT-WANT-TO
	RTRUE	
?CCL6:	EQUAL?	FOLLOW-FLAG,5 \?CCL8
	CALL2	DO-WALK,P?NORTH
	RSTACK	
?CCL8:	EQUAL?	FOLLOW-FLAG,6 \?CCL10
	CALL2	DO-WALK,P?EAST
	RSTACK	
?CCL10:	CALL1	V-WALK-AROUND
	RSTACK	
?CCL3:	GET	P-NAMW,0
	EQUAL?	STACK,W?MAN \?CCL12
	EQUAL?	PRSO,MAN-WOMAN \?CCL12
	CALL1	FIND-MAN >PERSON
	ZERO?	PERSON /?CCL17
	ICALL	PERFORM-PRSA,PERSON,PRSI
	RTRUE	
?CCL17:	CALL2	CANT-SEE,MAN-WOMAN
	RSTACK	
?CCL12:	GET	P-NAMW,0
	EQUAL?	STACK,W?WOMAN \?CCL19
	EQUAL?	PRSO,MAN-WOMAN \?CCL19
	CALL1	FIND-WOMAN >PERSON
	ZERO?	PERSON /?CCL24
	ICALL	PERFORM-PRSA,PERSON,PRSI
	RTRUE	
?CCL24:	CALL2	CANT-SEE,MAN-WOMAN
	RSTACK	
?CCL19:	GET	P-NAMW,1
	EQUAL?	STACK,W?MAN \?CCL26
	EQUAL?	PRSI,MAN-WOMAN \?CCL26
	CALL1	FIND-MAN >PERSON
	ZERO?	PERSON /?CCL31
	ICALL	PERFORM-PRSA,PRSO,PERSON
	RTRUE	
?CCL31:	CALL2	CANT-SEE,MAN-WOMAN
	RSTACK	
?CCL26:	GET	P-NAMW,1
	EQUAL?	STACK,W?WOMAN \FALSE
	EQUAL?	PRSI,MAN-WOMAN \FALSE
	CALL1	FIND-WOMAN >PERSON
	ZERO?	PERSON /?CCL38
	ICALL	PERFORM-PRSA,PRSO,PERSON
	RTRUE	
?CCL38:	CALL2	CANT-SEE,MAN-WOMAN
	RSTACK	


	.FUNCT	FIND-MAN
	PUTP	MAN-WOMAN,P?SDESC,STR?127
	IN?	SALESMAN,HERE \?CCL3
	RETURN	SALESMAN
?CCL3:	IN?	MAD-SCIENTIST,HERE \?CCL5
	RETURN	MAD-SCIENTIST
?CCL5:	IN?	MITRE,HERE \?CCL7
	RETURN	MITRE
?CCL7:	IN?	PROPRIETOR,HERE \?CCL9
	RETURN	PROPRIETOR
?CCL9:	IN?	THORBAST,HERE \?CCL11
	ZERO?	MALE /?CCL11
	RETURN	THORBAST
?CCL11:	IN?	YOUNG-WOMAN,HERE \?CCL15
	ZERO?	MALE \?CCL15
	RETURN	YOUNG-WOMAN
?CCL15:	IN?	SULTAN,HERE \?CCL19
	ZERO?	MALE /?CCL19
	RETURN	SULTAN
?CCL19:	IN?	SULTANS-WIFE,HERE \?CCL23
	ZERO?	MALE \?CCL23
	RETURN	SULTANS-WIFE
?CCL23:	CALL2	VISIBLE?,SIDEKICK
	ZERO?	STACK /FALSE
	ZERO?	MALE /FALSE
	RETURN	SIDEKICK


	.FUNCT	FIND-WOMAN
	PUTP	MAN-WOMAN,P?SDESC,STR?128
	IN?	THORBAST,HERE \?CCL3
	ZERO?	MALE \?CCL3
	RETURN	THORBAST
?CCL3:	IN?	YOUNG-WOMAN,HERE \?CCL7
	ZERO?	MALE /?CCL7
	RETURN	YOUNG-WOMAN
?CCL7:	IN?	THETA,HERE \?CCL11
	FSET?	THETA,MUNGBIT /?CCL11
	RETURN	THETA
?CCL11:	IN?	LGOP,HERE \?CCL15
	RETURN	LGOP
?CCL15:	IN?	SULTAN,HERE \?CCL17
	ZERO?	MALE \?CCL17
	RETURN	SULTAN
?CCL17:	IN?	SULTANS-WIFE,HERE \?CCL21
	ZERO?	MALE /?CCL21
	RETURN	SULTANS-WIFE
?CCL21:	CALL2	VISIBLE?,SIDEKICK
	ZERO?	STACK /FALSE
	ZERO?	MALE \FALSE
	RETURN	SIDEKICK


	.FUNCT	NOT-HERE-OBJECT-F,TBL,PRSO?,OBJ,X
	SET	'PRSO?,TRUE-VALUE
	EQUAL?	PRSO,NOT-HERE-OBJECT \?CCL3
	EQUAL?	PRSI,NOT-HERE-OBJECT \?CCL3
	PRINTR	"Those things aren't here!"
?CCL3:	EQUAL?	P-XNAM,W?BODY \?CCL7
	EQUAL?	P-XADJ,W?MY,FALSE-VALUE \?CCL7
	EQUAL?	PRSO,NOT-HERE-OBJECT \?CCL12
	SET	'PRSO,ME
	RFALSE	
?CCL12:	SET	'PRSI,ME
	RFALSE	
?CCL7:	EQUAL?	P-XNAM,W?HAND,W?HANDS \?CCL14
	EQUAL?	P-XADJ,W?MITRE,W?KING'S \?CCL14
	EQUAL?	PRSA,V?TAKE,V?SHAKE \?CCL14
	ICALL	PERFORM,V?SHAKE-WITH,HANDS,MITRE
	RTRUE	
?CCL14:	EQUAL?	P-XNAM,W?HANDS,W?HAND,W?PALM /?PRD21
	EQUAL?	P-XNAM,W?FINGER,W?EYE,W?EYES /?PRD21
	EQUAL?	P-XNAM,W?HEAD,W?EARS,W?EAR /?PRD21
	EQUAL?	P-XNAM,W?LIP,W?LIPS,W?MOUTH /?PRD21
	EQUAL?	P-XNAM,W?KNEECAP,W?KNEECAPS,W?KNEE /?PRD21
	EQUAL?	P-XNAM,W?KNEES,W?NOSE,W?NOSTRIL /?PRD21
	EQUAL?	P-XNAM,W?BALLS,W?PENIS,W?COCK /?PRD21
	EQUAL?	P-XNAM,W?ASS,W?TITS,W?BREAST /?PRD21
	EQUAL?	P-XNAM,W?BOSOM,W?CUNT,W?VAGINA /?PRD21
	EQUAL?	P-XNAM,W?PUSSY,W?TIT,W?BODY \?CCL19
?PRD21:	EQUAL?	P-XADJ,W?TRENT'S,W?TIFFANY'S,W?TIFF'S /?CTR18
	EQUAL?	P-XADJ,W?GODDESSES,W?SHAPE'S,W?COUCHMATE /?CTR18
	EQUAL?	P-XADJ,W?THORBAST,W?THORBALA,W?ASSASSIN /?CTR18
	EQUAL?	P-XADJ,W?SALESMAN,W?SCIENTIST,W?GORILLA'S /?CTR18
	EQUAL?	P-XADJ,W?MONKEY'S,W?KING'S,W?MITRE'S /?CTR18
	EQUAL?	P-XADJ,W?SULTAN'S,W?SULTANESS /?CTR18
	EQUAL?	P-XADJ,W?PROPRIETOR,W?OWNER'S /?CTR18
	EQUAL?	P-XADJ,W?GUARD'S,W?PRINCE'S,W?DAUGHTER /?CTR18
	EQUAL?	P-XADJ,W?THETA'S,W?BARTENDER,W?WIFE'S /?CTR18
	EQUAL?	P-XADJ,W?HUSBAND'S,W?ELYSIA'S,W?ELYSIUM'S /?CTR18
	EQUAL?	P-XADJ,W?WOMAN'S,W?ROBOT'S,W?BABY'S /?CTR18
	EQUAL?	P-XADJ,W?MAN'S,W?HIS,W?HER \?CCL19
?CTR18:	PRINTR	"[Sorry. Given limited space, we can't handle everything. Therefore, you can only refer to characters in the story, not individual body parts. For example, you can KISS IRWIN but you can't KISS IRWIN'S ELBOW.]"
?CCL19:	EQUAL?	PRSO,NOT-HERE-OBJECT \?CCL45
	SET	'TBL,P-PRSO
	JUMP	?CND1
?CCL45:	SET	'TBL,P-PRSI
	SET	'PRSO?,FALSE-VALUE
?CND1:	ZERO?	PRSO? /?CCL48
	CALL1	PRSO-MOBY-VERB?
	ZERO?	STACK /?CCL48
	SET	'X,TRUE-VALUE
	JUMP	?CND46
?CCL48:	ZERO?	PRSO? \?CND46
	CALL1	PRSI-MOBY-VERB?
	ZERO?	STACK /?CND46
	SET	'X,TRUE-VALUE
?CND46:	ZERO?	X /?CCL56
	CALL	FIND-NOT-HERE,TBL,PRSO? >OBJ
	ZERO?	OBJ /FALSE
	EQUAL?	OBJ,NOT-HERE-OBJECT \TRUE
	EQUAL?	PRSA,V?FOLLOW,V?WALK-TO \?CCL64
	ICALL1	V-WALK-AROUND
	JUMP	?CND54
?CCL64:	PRINTC	91
	PRINT	YOULL-HAVE-TO
	PRINTI	"be more specific.]"
	CRLF	
	JUMP	?CND54
?CCL56:	EQUAL?	WINNER,PROTAGONIST \?CCL67
	PRINTI	"You"
	JUMP	?CND65
?CCL67:	PRINTI	"Looking confused,"
	ICALL2	TPRINT,WINNER
	PRINTI	" says, ""I"
?CND65:	PRINTI	" can't "
	EQUAL?	P-XNAM,W?ODOR,W?SMELL,W?SCENT \?CCL70
	PRINTI	"smell"
	JUMP	?CND68
?CCL70:	PRINTI	"see"
?CND68:	CALL2	NAME?,P-XNAM
	ZERO?	STACK /?CCL72
	EQUAL?	P-XNAM,W?FORD \?CND71
?CCL72:	PRINTI	" any"
?CND71:	ICALL2	NOT-HERE-PRINT,PRSO?
	PRINTI	" here!"
	EQUAL?	WINNER,PROTAGONIST /?CND75
	PRINTC	34
?CND75:	CRLF	
?CND54:	CALL1	STOP
	RSTACK	


	.FUNCT	PRSO-MOBY-VERB?
	EQUAL?	PRSA,V?WHAT,V?WHERE /TRUE
	EQUAL?	PRSA,V?WAIT-FOR,V?WALK-TO,V?MAKE /TRUE
	EQUAL?	PRSA,V?BUY,V?CALL,V?SAY /TRUE
	EQUAL?	PRSA,V?FIND,V?FOLLOW,V?PHONE /TRUE
	EQUAL?	PRSA,V?USE-QUOTES,V?ANSWER-KLUDGE /TRUE
	RFALSE	


	.FUNCT	PRSI-MOBY-VERB?
	EQUAL?	PRSA,V?ASK-ABOUT,V?ASK-FOR,V?TELL-ABOUT /TRUE
	RFALSE	


	.FUNCT	FIND-NOT-HERE,TBL,PRSO?,M-F,OBJ
	CALL2	MOBY-FIND,TBL >M-F
	EQUAL?	1,M-F \?CCL3
	ZERO?	PRSO? /?CCL6
	SET	'PRSO,P-MOBY-FOUND
	ICALL2	THIS-IS-IT,PRSO
	RFALSE	
?CCL6:	SET	'PRSI,P-MOBY-FOUND
	RFALSE	
?CCL3:	LESS?	1,M-F \?CCL8
	GET	TBL,1 >OBJ
	GETP	OBJ,P?GENERIC
	CALL	STACK >OBJ
	ZERO?	OBJ /?CCL8
	EQUAL?	OBJ,NOT-HERE-OBJECT /TRUE
	ZERO?	PRSO? /?CCL15
	SET	'PRSO,OBJ
	ICALL2	THIS-IS-IT,PRSO
	RFALSE	
?CCL15:	SET	'PRSI,OBJ
	RFALSE	
?CCL8:	RETURN	NOT-HERE-OBJECT


	.FUNCT	NOT-HERE-PRINT,PRSO?,?TMP1
	ZERO?	P-OFLAG /?CCL3
	ZERO?	P-XADJ /?CND4
	PRINTC	32
	PRINTB	P-XADJ
?CND4:	ZERO?	P-XNAM /FALSE
	PRINTC	32
	PRINTB	P-XNAM
	RTRUE	
?CCL3:	ZERO?	PRSO? /?CCL10
	GET	P-ITBL,P-NC1 >?TMP1
	GET	P-ITBL,P-NC1L
	CALL	BUFFER-PRINT,?TMP1,STACK,FALSE-VALUE
	RSTACK	
?CCL10:	GET	P-ITBL,P-NC2 >?TMP1
	GET	P-ITBL,P-NC2L
	CALL	BUFFER-PRINT,?TMP1,STACK,FALSE-VALUE
	RSTACK	


	.FUNCT	LOVE-F,LOVER
	EQUAL?	PRSA,V?MAKE \FALSE
	CALL	FIND-IN,HERE,ACTORBIT,STR?81 >LOVER
	ZERO?	LOVER /?CCL6
	ICALL	PERFORM,V?FUCK,LOVER
	RTRUE	
?CCL6:	PRINTR	"Alone? How odd."


	.FUNCT	GLOBAL-SLEEP-F
	EQUAL?	PRSA,V?TAKE,V?WALK-TO \?CCL3
	ICALL2	PERFORM,V?SLEEP
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?PUT-TO \FALSE
	EQUAL?	PRSI,GLOBAL-SLEEP \FALSE
	PRINTR	"You're not a hypnotist."


	.FUNCT	GROUND-F
	EQUAL?	HERE,IN-SPACE \?CCL3
	ICALL2	CANT-SEE,GROUND
	RTRUE	
?CCL3:	FSET?	HERE,INDOORSBIT /?CTR4
	LOC	PROTAGONIST
	EQUAL?	STACK,BARGE \?CCL5
?CTR4:	PUTP	GROUND,P?SDESC,STR?130
	JUMP	?CND1
?CCL5:	PUTP	GROUND,P?SDESC,STR?129
?CND1:	EQUAL?	PRSA,V?EXAMINE \?CCL10
	EQUAL?	HERE,SPAWNING-GROUND \?CCL13
	PRINT	OOZY-WITH-SLIME
	CRLF	
	RTRUE	
?CCL13:	CALL	GLOBAL-IN?,HOLE,HERE
	ZERO?	STACK /?CCL15
	CALL1	HOLE-INVISIBLE
	ZERO?	STACK \?CCL15
	PRINTI	"You notice"
	CALL2	ARPRINT,HOLE
	RSTACK	
?CCL15:	EQUAL?	HERE,CELL \?CCL19
	PRINTR	"Soft. Cushiony."
?CCL19:	EQUAL?	HERE,OTHER-CELL \?CCL21
	PRINTR	"Rock-hard."
?CCL21:	EQUAL?	HERE,HOLD \?CCL23
	EQUAL?	SIDEKICK-EXPLODED,1 \?CCL23
	ICALL1	SPLATTERED-DESC
	CRLF	
	RTRUE	
?CCL23:	CALL1	IN-CATACOMBS
	ZERO?	STACK /FALSE
	PRINT	CATACOMBS-WATER-DESC
	CRLF	
	RTRUE	
?CCL10:	EQUAL?	PRSA,V?TOUCH \?CCL29
	EQUAL?	HERE,CELL,OTHER-CELL \?CCL29
	ICALL	PERFORM,V?EXAMINE,GROUND
	RTRUE	
?CCL29:	EQUAL?	PRSA,V?CLIMB,V?CLIMB-ON,V?CLIMB-UP /?CTR32
	EQUAL?	PRSA,V?BOARD \?CCL33
?CTR32:	CALL1	WASTES
	RSTACK	
?CCL33:	EQUAL?	PRSA,V?LOOK-UNDER \?CCL37
	CALL1	IMPOSSIBLES
	RSTACK	
?CCL37:	EQUAL?	PRSA,V?LEAVE \?CCL39
	CALL2	DO-WALK,P?UP
	RSTACK	
?CCL39:	EQUAL?	PRSA,V?STAND-ON,V?LEAP \FALSE
	EQUAL?	HERE,ROOF \FALSE
	ICALL	PERFORM,V?LEAP,ROOMS
	RTRUE	


	.FUNCT	CEILING-F
	EQUAL?	PRSA,V?EXAMINE \?CCL3
	EQUAL?	HERE,HOLD \?CCL6
	EQUAL?	SIDEKICK-EXPLODED,1 \?CCL6
	ICALL1	SPLATTERED-DESC
	CRLF	
	RTRUE	
?CCL6:	EQUAL?	HERE,CELL \?CCL10
	ZERO?	HOLE-OPEN /?CCL10
	PRINTR	"There's a hole in the ceiling."
?CCL10:	EQUAL?	HERE,BEDROOM \FALSE
	FSET?	BEDROOM,MUNGBIT \FALSE
	PRINTR	"Most of the ceiling is now gone."
?CCL3:	FSET?	HERE,INDOORSBIT /?CCL18
	CALL2	CANT-SEE,CEILING
	RSTACK	
?CCL18:	EQUAL?	PRSA,V?ENTER \?CCL20
	EQUAL?	HERE,CELL \?CCL20
	ZERO?	HOLE-OPEN /?CCL20
	CALL2	DO-WALK,P?UP
	RSTACK	
?CCL20:	EQUAL?	PRSA,V?LOOK-UNDER \FALSE
	ICALL2	PERFORM,V?LOOK
	RTRUE	


	.FUNCT	ODOR-F
	EQUAL?	HERE,IN-SPACE \?CCL3
	IN?	THORBAST,HERE /?CCL3
	PRINT	CANT-SMELL
	RTRUE	
?CCL3:	EQUAL?	HERE,MENS-ROOM,LADIES-ROOM \?CCL7
	CALL2	RUNNING?,I-URGE
	ZERO?	STACK /?CCL7
	PRINT	CANT-SMELL
	RTRUE	
?CCL7:	EQUAL?	HERE,PLAZA \?CCL11
	LESS?	PLAZA-COUNTER,9 \?CCL11
	PRINT	CANT-SMELL
	RTRUE	
?CCL11:	EQUAL?	PRSA,V?SMELL /?CCL15
	EQUAL?	PRSA,V?EXAMINE \FALSE
	EQUAL?	P-PRSA-WORD,W?DESCRIBE \FALSE
?CCL15:	GETP	HERE,P?ODOR
	ZERO?	STACK /?CCL22
	FSET?	HERE,SMELLEDBIT \?CCL25
	PRINTI	"There is a strong odor of "
	GETP	HERE,P?ODOR
	PRINT	STACK
	PRINTR	" in the air."
?CCL25:	FSET	HERE,SMELLEDBIT
	ICALL1	SCRATCH-N-SNIFF
	GETP	HERE,P?ACTION
	ICALL	STACK,M-SMELL
	CRLF	
	RTRUE	
?CCL22:	EQUAL?	HERE,INNER-HAREM \?CCL27
	SET	'HERE,HAREM
	ICALL	PERFORM,V?SMELL,ODOR
	SET	'HERE,INNER-HAREM
	RTRUE	
?CCL27:	EQUAL?	HERE,GARDEN \?CCL29
	CALL2	NO-SCRATCH-N-SNIFF,STR?131
	RSTACK	
?CCL29:	CALL2	ACCESSIBLE?,CHOCOLATE
	ZERO?	STACK /?CCL31
	FSET?	CHOCOLATE,UNTEEDBIT /?CCL31
	PRINTI	"[the "
	ICALL2	DPRINT,CHOCOLATE
	PRINTC	93
	CRLF	
	ICALL	PERFORM,V?SMELL,CHOCOLATE
	RTRUE	
?CCL31:	PRINT	CANT-SMELL
	RTRUE	


	.FUNCT	SCRATCH-N-SNIFF,NUM
	PRINTI	"[Scratch 'n' sniff spot number "
	ZERO?	NUM /?CCL3
	PRINTN	NUM
	JUMP	?CND1
?CCL3:	GETP	HERE,P?ODOR-NUMBER
	PRINTN	STACK
?CND1:	PRINT	HIT-RETURN
	PRINTI	"continue.]"
	PUTB	P-INBUF,1,0
	READ	P-INBUF,P-LEXV
	CRLF	
	RTRUE	


	.FUNCT	NO-SCRATCH-N-SNIFF,STRING
	PRINTI	"[Too bad there's no scratch 'n' sniff for this one, huh?]

Ahhh, the odor of "
	PRINT	STRING
	PRINTR	"!"


	.FUNCT	WATER-F
	EQUAL?	HERE,MINARET,DUNETOP \?CCL3
	CALL2	TOUCHING?,WATER
	ZERO?	STACK /?CCL3
	CALL2	CANT-REACH,WATER
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?BUY,V?DRINK \?CCL7
	PRINTR	"You're not thirsty."
?CCL7:	EQUAL?	PRSA,V?EXAMINE,V?LOOK-UNDER,V?LOOK-INSIDE \?CCL9
	PRINTR	"The water is dark and murky."
?CCL9:	EQUAL?	PRSA,V?MAKE,V?PASS \?CCL11
	CALL1	V-PEE
	RSTACK	
?CCL11:	EQUAL?	PRSA,V?REACH-IN \?CCL13
	PRINTR	"Your hand is now wet."
?CCL13:	EQUAL?	PRSA,V?PUT-ON \?CCL15
	EQUAL?	PRSI,WATER \?CCL15
	ICALL	PERFORM,V?PUT,PRSO,WATER
	RTRUE	
?CCL15:	CALL	GLOBAL-IN?,CANAL-OBJECT,HERE
	ZERO?	STACK /?CCL19
	EQUAL?	PRSO,WATER \?CCL22
	ICALL	PERFORM-PRSA,CANAL-OBJECT,PRSI
	RTRUE	
?CCL22:	ICALL	PERFORM-PRSA,PRSO,CANAL-OBJECT
	RTRUE	
?CCL19:	EQUAL?	PRSA,V?PUT \?CCL24
	EQUAL?	PRSI,WATER \?CCL24
	EQUAL?	PRSO,RAFT \?CCL29
	EQUAL?	HERE,OASIS \?CCL29
	PRINTR	"Next you'll be putting yachts in bathtubs!"
?CCL29:	EQUAL?	PRSO,RAFT \?CCL33
	CALL1	IN-CATACOMBS
	ZERO?	STACK /?CCL33
	ICALL	PERFORM,V?DROP,RAFT
	RTRUE	
?CCL33:	CALL1	WASTES
	RSTACK	
?CCL24:	EQUAL?	PRSA,V?WALK,V?ON \?CCL37
	EQUAL?	HERE,MENS-ROOM,LADIES-ROOM \?CCL37
	ICALL	PERFORM,V?FLUSH,TOILET
	RTRUE	
?CCL37:	EQUAL?	PRSA,V?CRAWL-UNDER,V?ENTER,V?BOARD \FALSE
	CALL1	V-SWIM
	RSTACK	


	.FUNCT	HANDS-F,ACTOR
	EQUAL?	PRSA,V?APPLAUD \?CCL3
	SET	'PRSO,FALSE-VALUE
	CALL1	V-APPLAUD
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?SHAKE \?CCL5
	EQUAL?	HERE,THRONE-ROOM \?CCL8
	ICALL	PERFORM,V?SHAKE-WITH,HANDS,MITRE
	RTRUE	
?CCL8:	CALL	FIND-IN,HERE,ACTORBIT,STR?53 >ACTOR
	ZERO?	ACTOR /?CCL10
	ICALL	PERFORM,V?SHAKE-WITH,HANDS,ACTOR
	RTRUE	
?CCL10:	PRINTR	"Pleased to meet you."
?CCL5:	EQUAL?	PRSA,V?COUNT \?CCL12
	CALL	NOUN-USED,W?FINGER,HANDS
	ZERO?	STACK /?CCL15
	PRINTI	"Ten"
	JUMP	?CND13
?CCL15:	PRINTI	"Two"
?CND13:	PRINTR	", as usual."
?CCL12:	EQUAL?	PRSA,V?CLEAN \?CCL17
	PRINTR	"Done."
?CCL17:	EQUAL?	PRSA,V?TAKE-WITH \?CCL19
	EQUAL?	PRSI,HANDS \?CCL19
	ICALL	PERFORM,V?TAKE,PRSO
	RTRUE	
?CCL19:	EQUAL?	PRSA,V?PUT-ON \?CCL23
	EQUAL?	PRSI,EYES \?CCL23
	ICALL	PERFORM,V?SPUT-ON,EYES,HANDS
	RTRUE	
?CCL23:	EQUAL?	PRSA,V?PUT,V?PUT-ON \?CCL27
	EQUAL?	PRSI,EARS \?CCL27
	ICALL	PERFORM,V?SPUT-ON,EARS,HANDS
	RTRUE	
?CCL27:	EQUAL?	PRSA,V?SPUT-ON \FALSE
	EQUAL?	PRSO,NOSE,EARS,EYES \FALSE
	ZERO?	GONE-APE /?CCL36
	PRINT	DEXTERITY
	RTRUE	
?CCL36:	CALL1	ITEMS-CARRIED
	GRTR?	STACK,0 \?CCL38
	PRINT	YOU-CANT
	PRINTI	"do that with "
	PRINTD	HANDS
	PRINTR	"s full!"
?CCL38:	ZERO?	HAND-COVER /?CCL41
	PRINTI	"You're already"
	JUMP	?CND39
?CCL41:	SET	'HAND-COVER,PRSO
	FSET	PRSO,MUNGBIT
	EQUAL?	HAND-COVER,EARS \?CCL44
	PRINT	MUFFLED
	PRINTI	"'re"
	JUMP	?CND39
?CCL44:	PRINTI	"Okay, you're now"
?CND39:	PRINTI	" covering "
	ICALL2	DPRINT,HAND-COVER
	PRINTI	" with "
	PRINTD	HANDS
	PRINTR	"s."


	.FUNCT	ITEMS-CARRIED,X,CNT
	FIRST?	PROTAGONIST >X /?PRG2
?PRG2:	ZERO?	X \?CCL6
	RETURN	CNT
?CCL6:	FSET?	X,WORNBIT /?CND4
	EQUAL?	X,COMIC-BOOK /?CND4
	INC	'CNT
?CND4:	NEXT?	X >X /?PRG2
	JUMP	?PRG2


	.FUNCT	HEAD-F
	EQUAL?	PRSA,V?PUT-ON \FALSE
	EQUAL?	PRSO,SACK,SHEET,BLANKET \FALSE
	SET	'AWAITING-REPLY,2
	ICALL	QUEUE,I-REPLY,2
	PRINTR	"Where do you think you are, Traal?"


	.FUNCT	EYES-F
	EQUAL?	PRSA,V?CLOSE \?CCL3
	ZERO?	GONE-APE /?CCL6
	CALL1	WASTES
	RSTACK	
?CCL6:	FSET?	EYES,MUNGBIT \?CCL8
	EQUAL?	EYES,HAND-COVER \?CCL11
	PRINT	HANDS-OVER-EYES
	RTRUE	
?CCL11:	PRINT	SENILITY-STRIKES
	RTRUE	
?CCL8:	FSET	EYES,MUNGBIT
	CALL2	EYES-ARE-NOW,STR?132
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?OPEN \FALSE
	FSET?	EYES,MUNGBIT \?CCL16
	EQUAL?	EYES,HAND-COVER \?CCL19
	PRINT	HANDS-OVER-EYES
	RTRUE	
?CCL19:	CALL2	SENSE-AGAIN,EYES
	RSTACK	
?CCL16:	PRINTR	"They are open!"


	.FUNCT	EYES-ARE-NOW,STRING
	PRINTI	"Your eyes are now "
	PRINT	STRING
	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	OPEN-EYES-AND-REMOVE-HANDS
	FCLEAR	EYES,MUNGBIT
	ZERO?	HAND-COVER /FALSE
	FCLEAR	HAND-COVER,MUNGBIT
	SET	'HAND-COVER,FALSE-VALUE
	RETURN	HAND-COVER


	.FUNCT	EARS-F
	EQUAL?	PRSA,V?TAKE \?CCL3
	EQUAL?	P-PRSA-WORD,W?HOLD \?CCL3
	ICALL	PERFORM,V?SPUT-ON,EARS,HANDS
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?UNCOVER \FALSE
	FSET?	COTTON-BALLS,WORNBIT \FALSE
	ZERO?	GONE-APE \FALSE
	EQUAL?	EARS,HAND-COVER \?CND11
	SET	'HAND-COVER,FALSE-VALUE
?CND11:	ICALL	PERFORM,V?REMOVE,COTTON-BALLS
	RTRUE	


	.FUNCT	NOSE-F
	EQUAL?	PRSA,V?PICK,V?BLOW \?CCL3
	PRINT	YECHH
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?TAKE \?CCL5
	EQUAL?	P-PRSA-WORD,W?HOLD \?CCL5
	ICALL	PERFORM,V?SPUT-ON,NOSE,HANDS
	RTRUE	
?CCL5:	EQUAL?	PRSA,V?UNCOVER \FALSE
	FSET?	CLOTHES-PIN,WORNBIT \FALSE
	ZERO?	GONE-APE \FALSE
	EQUAL?	NOSE,HAND-COVER \?CND13
	SET	'HAND-COVER,FALSE-VALUE
?CND13:	ICALL	PERFORM,V?REMOVE,CLOTHES-PIN
	RTRUE	


	.FUNCT	MOUTH-F
	EQUAL?	PRSA,V?CLEAN \?CCL3
	FSET?	LIP-BALM,WORNBIT \?CCL3
	ICALL	PERFORM,V?REMOVE,LIP-BALM
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?EXAMINE \?CCL7
	FSET?	LIP-BALM,WORNBIT \?CCL7
	ICALL	ROB,PROTAGONIST,TOILET
	MOVE	LIP-BALM,PROTAGONIST
	ICALL1	V-INVENTORY
	CALL	ROB,TOILET,PROTAGONIST
	RSTACK	
?CCL7:	EQUAL?	PRSA,V?PUT \?CCL11
	EQUAL?	PRSI,MOUTH \?CCL11
	ICALL	PERFORM,V?EAT,PRSO
	RTRUE	
?CCL11:	EQUAL?	PRSA,V?OPEN \FALSE
	PRINTR	"This fails to catch any flies."


	.FUNCT	NAUGHTY-BITS-F
	CALL	NOUN-USED,W?PUSSY,CUNT
	ZERO?	STACK /?CCL3
	CALL2	ADJ-USED,W?MY
	ZERO?	STACK \?CCL3
	CALL2	VISIBLE?,PAINTING
	ZERO?	STACK /?CCL3
	EQUAL?	PRSO,CUNT \?CCL9
	ICALL	PERFORM-PRSA,PAINTING,PRSI
	RTRUE	
?CCL9:	ICALL	PERFORM-PRSA,PRSI,PAINTING
	RTRUE	
?CCL3:	PRINTI	"You don't need to refer to "
	PRINTD	COCK
	PRINTI	" to complete "
	PRINT	LGOP-CAPS
	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	ME-F
	EQUAL?	PRSA,V?TELL \?CCL3
	PRINTI	"Talking to yourself is a sign of impending mental collapse."
	CRLF	
	CALL1	STOP
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?RELIEVE \?CCL5
	CALL1	V-PEE
	RSTACK	
?CCL5:	EQUAL?	PRSA,V?PUT \?CCL7
	EQUAL?	PRSI,ME \?CCL7
	ZERO?	MALE \?CCL7
	ZERO?	NAUGHTY-LEVEL /?CCL7
	ICALL	PERFORM,V?FUCK,ME
	RTRUE	
?CCL7:	EQUAL?	PRSA,V?EAT,V?FUCK,V?TOUCH \?CCL13
	ZERO?	NAUGHTY-LEVEL /?CCL13
	PRINTI	"Encouraging such behavior would endanger the possibility of landing a lucrative Hollywood contract to make a film of "
	PRINT	LGOP-CAPS
	PRINT	PERIOD-CR
	RTRUE	
?CCL13:	EQUAL?	PRSA,V?GIVE \?CCL17
	EQUAL?	PRSI,ME \?CCL17
	ICALL	PERFORM,V?TAKE,PRSO
	RTRUE	
?CCL17:	EQUAL?	PRSA,V?SHOW \?CCL21
	EQUAL?	PRSI,ME \?CCL21
	ICALL	PERFORM,V?EXAMINE,PRSO
	RTRUE	
?CCL21:	EQUAL?	PRSA,V?MOVE \?CCL25
	CALL1	V-WALK-AROUND
	RSTACK	
?CCL25:	EQUAL?	PRSA,V?SEARCH \?CCL27
	ICALL1	V-INVENTORY
	RTRUE	
?CCL27:	EQUAL?	PRSA,V?EXAMINE \?CCL29
	ZERO?	GONE-APE /?CCL32
	PRINTR	"You've gone ape!"
?CCL32:	PRINTI	"You're wearing"
	FSET?	WHITE-SUIT,WORNBIT \?CCL35
	CALL2	ARPRINT,WHITE-SUIT
	RSTACK	
?CCL35:	CALL2	ARPRINT,GARMENT
	RSTACK	
?CCL29:	EQUAL?	PRSA,V?MUNG,V?KILL \?CCL37
	CALL2	JIGS-UP,STR?133
	RSTACK	
?CCL37:	EQUAL?	PRSA,V?WHERE,V?FIND \?CCL39
	PRINTI	"You're in"
	CALL2	TRPRINT,HERE
	RSTACK	
?CCL39:	EQUAL?	PRSA,V?MEASURE \?CCL41
	PRINTR	"You don't measure up."
?CCL41:	EQUAL?	PRSA,V?UNTIE \?CCL43
	ZERO?	BODY-TIED-TO-SLAB /?CCL43
	ZERO?	GONE-APE /?CCL48
	ICALL2	PERFORM-PRSA,YOUR-BODY
	RTRUE	
?CCL48:	CALL1	YUKS
	RSTACK	
?CCL43:	EQUAL?	PRSA,V?TIE \?CCL50
	EQUAL?	PRSI,SECOND-SLAB,FIRST-SLAB \?CCL50
	ZERO?	BODY-TIED-TO-SLAB /?CCL55
	ZERO?	GONE-APE \?CCL55
	PRINTR	"You are!"
?CCL55:	PRINT	YOU-CANT
	PRINTR	"tie yourself down!"
?CCL50:	EQUAL?	PRSA,V?FOLLOW \FALSE
	PRINTR	"Like most computers, I don't have legs."


	.FUNCT	GLOBAL-ROOM-F
	EQUAL?	PRSA,V?EXAMINE,V?LOOK-INSIDE,V?LOOK \?CCL3
	CALL1	V-LOOK
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?WALK-TO,V?ENTER \?CCL5
	CALL1	V-WALK-AROUND
	RSTACK	
?CCL5:	EQUAL?	PRSA,V?DISEMBARK,V?EXIT,V?LEAVE \?CCL7
	CALL2	DO-WALK,P?OUT
	RSTACK	
?CCL7:	EQUAL?	PRSA,V?SEARCH \?CCL9
	EQUAL?	HERE,EXIT-SHOP \?CCL12
	ICALL2	PERFORM-PRSA,DUST
	RTRUE	
?CCL12:	PRINT	NOTHING-NEW
	RTRUE	
?CCL9:	EQUAL?	PRSA,V?PUT \FALSE
	EQUAL?	PRSI,GLOBAL-ROOM \FALSE
	EQUAL?	P-PRSA-WORD,W?THROW \?CCL19
	ICALL	PERFORM,V?THROW,PRSO
	RTRUE	
?CCL19:	ICALL	PERFORM,V?DROP,PRSO
	RTRUE	


	.FUNCT	HOUSE-F
	EQUAL?	PRSA,V?BOARD,V?WALK-TO,V?ENTER \?CCL3
	EQUAL?	HERE,BEDROOM,TEENSY-WEENSY-HOUSE /?CTR5
	EQUAL?	HERE,LABORATORY,LOOKS-CAN-BE-DECEIVING \?CCL6
?CTR5:	PRINT	LOOK-AROUND
	RTRUE	
?CCL6:	EQUAL?	HERE,FRONT-DOOR \?CCL10
	CALL2	DO-WALK,P?NORTH
	RSTACK	
?CCL10:	EQUAL?	HERE,BACK-DOOR \?CCL12
	CALL2	DO-WALK,P?SOUTH
	RSTACK	
?CCL12:	EQUAL?	HERE,CLEVELAND \?CCL14
	CALL2	DO-WALK,P?NE
	RSTACK	
?CCL14:	EQUAL?	HERE,BEDROOM,GARDEN \FALSE
	CALL2	DO-WALK,P?WEST
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?DISEMBARK,V?LEAVE,V?EXIT \?CCL18
	EQUAL?	HERE,LABORATORY,BEDROOM \?CCL21
	PRINT	CANT-FROM-HERE
	RTRUE	
?CCL21:	EQUAL?	HERE,TEENSY-WEENSY-HOUSE,LABORATORY \?CCL23
	CALL1	V-WALK-AROUND
	RSTACK	
?CCL23:	PRINT	LOOK-AROUND
	RTRUE	
?CCL18:	EQUAL?	PRSA,V?LOOK-INSIDE \?CCL25
	EQUAL?	HERE,FRONT-DOOR,BACK-DOOR,GARDEN \?CCL28
	PRINT	CANT-FROM-HERE
	RTRUE	
?CCL28:	CALL1	V-LOOK
	RSTACK	
?CCL25:	EQUAL?	PRSA,V?SEARCH \FALSE
	PRINT	NOTHING-NEW
	RTRUE	


	.FUNCT	SIGN-F,NUM
	CALL1	CANAL-LOC >NUM
	EQUAL?	HERE,CANAL \?CCL3
	EQUAL?	NUM,15 /?CCL3
	CALL2	CANT-SEE,SIGN
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?READ \FALSE
	EQUAL?	HERE,END-OF-HALLWAY \?CCL10
	PRINTR	"""Up To Observation Room."""
?CCL10:	EQUAL?	HERE,OBSERVATION-ROOM \?CCL12
	PRINTR	"""Down to Cells."""
?CCL12:	EQUAL?	HERE,EXIT-SHOP \?CCL14
	PRINTI	"""E"
	PRINT	BOUGHT-AND-SOLD
	PRINTR	"."""
?CCL14:	EQUAL?	HERE,VIZICOMM-BOOTH \?CCL16
	PRINTR	"""Out of order."""
?CCL16:	EQUAL?	HERE,SOUTH-POLE \?CCL18
	PRINTR	"""Martian Orphanages, Inc.
   South Polar Branch"""
?CCL18:	EQUAL?	HERE,PENGUIN-PARK \?CCL20
	PRINTR	"""Give generously to the Penguin Retirement Fund."""
?CCL20:	EQUAL?	HERE,CANAL,WATTZ-UPP-DOCK \FALSE
	PRINTR	"The sign has no writing, only the skull and crossbones."


	.FUNCT	STAIRS-F
	EQUAL?	PRSA,V?CLIMB-UP,V?CLIMB \?CCL3
	CALL2	DO-WALK,P?UP
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?CLIMB-DOWN \?CCL5
	EQUAL?	HERE,BEDROOM \?CCL8
	CALL2	BEDROOM-EXIT-F,TRUE-VALUE
	ZERO?	STACK /TRUE
	CALL2	GOTO,TEENSY-WEENSY-HOUSE
	RSTACK	
?CCL8:	CALL2	DO-WALK,P?DOWN
	RSTACK	
?CCL5:	EQUAL?	PRSA,V?THROW \FALSE
	EQUAL?	PRSI,STAIRS \FALSE
	CALL1	WASTES
	RSTACK	


	.FUNCT	WINDOW-F
	EQUAL?	PRSA,V?LOOK-INSIDE \?CCL3
	EQUAL?	HERE,OBSERVATION-ROOM \?CCL6
	SET	'SEEN-EXAMINATION-ROOM,TRUE-VALUE
	PRINT	YOU-SEE
	PRINTI	" a large room below. "
	CALL2	EXAMINATION-ROOM-DESC,TRUE-VALUE
	RSTACK	
?CCL6:	EQUAL?	HERE,BEDROOM \?CCL8
	MOVE	FORD,HERE
	FSET?	HEADLIGHT,TRYTAKEBIT \?CND9
	MOVE	HEADLIGHT,HERE
?CND9:	MOVE	FORD,HERE
	PRINTI	"A car is parked on the street, twenty feet below. It's a Ford, a 1933 Ford ... and one of its "
	PRINTD	HEADLIGHT
	PRINTI	"s is "
	IN?	HEADLIGHT,HERE \?CCL13
	FSET?	HEADLIGHT,TRYTAKEBIT \?CCL13
	PRINTI	"loose"
	JUMP	?CND11
?CCL13:	PRINTI	"missing"
?CND11:	PRINT	PERIOD-CR
	RTRUE	
?CCL8:	EQUAL?	HERE,HOLD \?CCL17
	PRINT	YOU-SEE
	PRINTI	" Saturn and her ample rings."
	EQUAL?	SPACESHIP-SCENE-STATUS,1 /?CND18
	PRINTI	" Much closer, no more than a hundred feet away, is"
	ICALL2	APRINT,PASSENGER-SHIP
	PRINTR	". Judging by the steam blowing from her ion engines, she's preparing to depart."
?CND18:	CRLF	
	RTRUE	
?CCL17:	EQUAL?	HERE,JOES-BAR \?CCL21
	PRINTR	"It's raw and blowy outside. Little whirlpools of dust dance by."
?CCL21:	EQUAL?	HERE,SOUTH-POLE \?CCL23
	FSET?	ORPHANAGE-FOYER,TOUCHBIT \?CCL26
	PRINTR	"The window is fogged."
?CCL26:	SET	'COTTON-BALLS-SEEN,TRUE-VALUE
	MOVE	COTTON-BALLS,HERE
	PRINT	YOU-SEE
	PRINTI	" a "
	PRINTD	COTTON-BALLS
	PRINTR	" sitting in an entrance foyer."
?CCL23:	EQUAL?	HERE,ORPHANAGE-FOYER \?CCL28
	PRINT	YOU-SEE
	PRINTR	" an icy plain."
?CCL28:	EQUAL?	HERE,MAIN-HALL-OF-PALACE \FALSE
	PRINTR	"Colored light spills through the window."
?CCL3:	EQUAL?	PRSA,V?OPEN \?CCL32
	EQUAL?	HERE,BEDROOM \?CCL35
	PRINT	ALREADY-IS
	RTRUE	
?CCL35:	PRINTR	"It's not that kind of window."
?CCL32:	EQUAL?	PRSA,V?CLOSE \?CCL37
	EQUAL?	HERE,BEDROOM \?CCL40
	PRINTR	"It seems stuck."
?CCL40:	PRINT	ALREADY-IS
	RTRUE	
?CCL37:	EQUAL?	PRSA,V?PUT,V?PUT-THROUGH \?CCL42
	EQUAL?	PRSI,WINDOW \?CCL42
	EQUAL?	HERE,BEDROOM \?CCL42
	EQUAL?	PRSO,HANDS \?CCL48
	PRINT	HUH
	RTRUE	
?CCL48:	IN?	PROTAGONIST,BED \?CCL50
	CALL2	CANT-REACH,PRSI
	RSTACK	
?CCL50:	EQUAL?	PRSO,SHEET \?CCL52
	ZERO?	SHEET-HANGING \FALSE
	ZERO?	SHEET-TIED \FALSE
?CCL52:	REMOVE	PRSO
	ICALL1	PRONOUN
	PRINTI	" land"
	FSET?	PRSO,PLURALBIT /?CND57
	PRINTC	115
?CND57:	PRINTI	" on the street below. An urchin dashes up and runs off with"
	CALL2	TRPRINT,PRSO
	RSTACK	
?CCL42:	EQUAL?	PRSA,V?EMPTY-FROM \?CCL60
	EQUAL?	PRSI,WINDOW \?CCL60
	EQUAL?	HERE,BEDROOM \?CCL60
	ICALL	PERFORM,V?EMPTY,PRSO,WINDOW
	RTRUE	
?CCL60:	EQUAL?	PRSA,V?DISEMBARK,V?EXIT,V?ENTER /?CCL65
	EQUAL?	PRSA,V?LEAP-OFF \FALSE
?CCL65:	EQUAL?	HERE,BEDROOM \?CCL70
	ZERO?	SHEET-HANGING /?CCL73
	ICALL	PERFORM,V?CLIMB-DOWN,SHEET
	RTRUE	
?CCL73:	CALL1	PLUMMET-TO-PAVEMENT
	RSTACK	
?CCL70:	EQUAL?	HERE,SOUTH-POLE,ORPHANAGE-FOYER \?CCL75
	PRINTR	"It's barred!"
?CCL75:	EQUAL?	HERE,OBSERVATION-ROOM \?CCL77
	CALL2	DO-WALK,P?WEST
	RSTACK	
?CCL77:	CALL	DO-FIRST,STR?67,WINDOW
	RSTACK	


	.FUNCT	TREE-F
	EQUAL?	PRSA,V?CLIMB-UP,V?CLIMB \FALSE
	PRINTR	"The trees are all unclimbable."


	.FUNCT	HOLE-F,OLD-HERE
	CALL1	CIRCLE-ISNT-BLACK
	ZERO?	STACK \?PRD5
	EQUAL?	PRSO,HOLE \?PRD5
	GET	P-ADJW,0
	EQUAL?	STACK,W?WHITE /?CTR2
?PRD5:	CALL1	CIRCLE-ISNT-BLACK
	ZERO?	STACK \?PRD9
	EQUAL?	PRSI,HOLE \?PRD9
	GET	P-ADJW,1
	EQUAL?	STACK,W?WHITE /?CTR2
?PRD9:	CALL1	CIRCLE-ISNT-BLACK
	ZERO?	STACK /?PRD13
	EQUAL?	PRSO,HOLE \?PRD13
	GET	P-ADJW,0
	EQUAL?	STACK,W?BLACK /?CTR2
?PRD13:	CALL1	CIRCLE-ISNT-BLACK
	ZERO?	STACK /?CCL3
	EQUAL?	PRSI,HOLE \?CCL3
	GET	P-ADJW,1
	EQUAL?	STACK,W?BLACK \?CCL3
?CTR2:	CALL2	CANT-SEE,HOLE
	RSTACK	
?CCL3:	CALL1	HOLE-INVISIBLE
	ZERO?	STACK /?CCL21
	CALL2	CANT-SEE,HOLE
	RSTACK	
?CCL21:	EQUAL?	HERE,CELL \?CCL23
	CALL	NOUN-USED,W?HOLE,HOLE
	ZERO?	STACK /?CCL23
	EQUAL?	PRSA,V?WALK-TO,V?ENTER,V?BOARD /?CTR22
	EQUAL?	PRSA,V?LOOK-INSIDE \?CCL23
?CTR22:	CALL2	DO-WALK,P?UP
	RSTACK	
?CCL23:	LOC	PROTAGONIST
	EQUAL?	STACK,CAGE,FIRST-SLAB,SECOND-SLAB \?CCL30
	CALL2	TOUCHING?,HOLE
	ZERO?	STACK /?CCL30
	ICALL2	CANT-REACH,HOLE
	RTRUE	
?CCL30:	EQUAL?	PRSA,V?BOARD,V?ENTER,V?STAND-ON \?CCL34
	CALL1	CIRCLE-ISNT-BLACK
	ZERO?	STACK /?CCL37
	PRINT	NOTHING-HAPPENS
	RTRUE	
?CCL37:	IN?	PROTAGONIST,HERE /?CND35
	ICALL1	NOT-GOING-ANYWHERE
	RTRUE	
?CND35:	ICALL1	FALL-THROUGH-HOLE
	SET	'LONG-CORRIDOR-LOC,1
	SET	'MAD-SCIENTIST-COUNTER,0
	SET	'IMPATIENCE-COUNTER,0
	ICALL2	DEQUEUE,I-MAD-SCIENTIST
	SET	'OLD-HERE,HERE
	EQUAL?	HERE,LONG-CORRIDOR \?CCL41
	PRINTI	"Geronimo!
   Yow! You appear in midair, high above a canal-studded desertscape. The ground is approaching uncomfortably fast.
   Caw! Caw! A pterodactyl snatches you"
	ICALL1	AND-SIDEKICK
	PRINTI	" in midair and deposits you safely in"
	PRINT	ELLIPSIS
	FSET?	MY-KIND-OF-DOCK,TOUCHBIT \?CCL44
	RANDOM	100
	LESS?	60,STACK /?CCL44
	ICALL2	GOTO,MY-KIND-OF-DOCK
	JUMP	?CND39
?CCL44:	FSET?	OASIS,TOUCHBIT \?CCL48
	RANDOM	100
	LESS?	40,STACK /?CCL48
	ICALL2	GOTO,OASIS
	JUMP	?CND39
?CCL48:	ICALL2	GOTO,RUINED-CASTLE-2
	JUMP	?CND39
?CCL41:	GETP	HERE,P?HOLE-DESTINATION
	ICALL2	GOTO,STACK
?CND39:	EQUAL?	OLD-HERE,WELL-BOTTOM \TRUE
	IN?	SIDEKICK,WELL-BOTTOM \TRUE
	SET	'HOLE-MOVE,TRUE-VALUE
	ICALL1	SIDEKICK-FOLLOWS-YOU
	SET	'HOLE-MOVE,FALSE-VALUE
	RTRUE	
?CCL34:	EQUAL?	PRSA,V?TAKE,V?LOOK-UNDER \?CCL56
	PRINTR	"It's not liftable."
?CCL56:	EQUAL?	PRSA,V?PUT-ON,V?RUB,V?POUR \?CCL58
	CALL	NOUN-USED,W?STAIN,STAIN
	ZERO?	STACK /?CCL58
	EQUAL?	PRSO,STAIN \?CCL58
	CALL2	APPLY-STAIN,HOLE
	RSTACK	
?CCL58:	EQUAL?	PRSA,V?PUT-THROUGH,V?PUT-ON,V?PUT \?CCL63
	EQUAL?	PRSI,HOLE \?CCL63
	CALL1	CIRCLE-ISNT-BLACK
	ZERO?	STACK /?CCL68
	CALL1	WASTES
	RSTACK	
?CCL68:	EQUAL?	PRSO,SOD /FALSE
	EQUAL?	HERE,LONG-CORRIDOR \?CCL73
	REMOVE	PRSO
	JUMP	?CND71
?CCL73:	EQUAL?	PRSO,TORCH \?CND74
	EQUAL?	HERE,WELL-BOTTOM \?CND74
	ICALL1	TORCH-OFF
?CND74:	GETP	HERE,P?HOLE-DESTINATION
	MOVE	PRSO,STACK
?CND71:	CALL1	NON-DIMENSIONAL-JOURNEY
	RSTACK	
?CCL63:	CALL1	CIRCLE-ISNT-BLACK
	ZERO?	STACK \FALSE
	EQUAL?	PRSA,V?TOUCH,V?REACH-IN \?CCL81
	PRINT	HAND-DWINDLES
	RTRUE	
?CCL81:	EQUAL?	PRSA,V?LOOK-INSIDE,V?EXAMINE \?CCL83
	PRINT	STARING-INTO-VOID
	RTRUE	
?CCL83:	EQUAL?	PRSA,V?MEASURE \FALSE
	ICALL2	PERFORM-PRSA,FLEXIBLE-HOLE
	RTRUE	


	.FUNCT	HOLE-INVISIBLE
	EQUAL?	HERE,GARDEN \?PRD5
	FSET?	SOD,MUNGBIT \TRUE
?PRD5:	EQUAL?	HERE,CELL \?PRD8
	ZERO?	HOLE-OPEN /TRUE
?PRD8:	EQUAL?	HERE,LONG-CORRIDOR \FALSE
	EQUAL?	LONG-CORRIDOR-LOC,3 /FALSE
	RTRUE	


	.FUNCT	NON-DIMENSIONAL-JOURNEY
	PRINTI	"You get all cross-eyed trying to follow the nondimensional journey of"
	ICALL1	TPRINT-PRSO
	PRINTI	" into"
	ICALL2	TPRINT,HOLE
	PRINTI	". When you get your eyeballs untangled again,"
	ICALL1	TPRINT-PRSO
	PRINTR	" is gone."


	.FUNCT	FALL-THROUGH-HOLE
	SET	'HOLE-MOVE,TRUE-VALUE
	SET	'RAFT-HELD,FALSE-VALUE
	PRINTI	"You're sucked into the hole in a direction that isn't down, but neither is it one of the other directions with which you're familiar."
	CALL2	ULTIMATELY-IN?,WHITE-SUIT
	ZERO?	STACK /?CND1
	MOVE	WHITE-SUIT,AT-MAIN-HATCH
	FCLEAR	WHITE-SUIT,TOUCHBIT
	FCLEAR	WHITE-SUIT,WORNBIT
	CALL2	VISIBLE?,WHITE-SUIT
	ZERO?	STACK /?CND1
	PRINTI	" Oddly, your "
	ICALL2	DPRINT,WHITE-SUIT
	PRINTI	" vanishes without a trace."
?CND1:	CRLF	
	CRLF	
	RTRUE	


	.FUNCT	TOUCHING?,THING
	EQUAL?	PRSO,THING \?CCL3
	EQUAL?	PRSA,V?TAKE,V?TOUCH,V?SHAKE /TRUE
	EQUAL?	PRSA,V?CLEAN,V?KISS,V?SWIM /TRUE
	EQUAL?	PRSA,V?PUSH,V?CLOSE,V?LOOK-UNDER /TRUE
	EQUAL?	PRSA,V?MOVE,V?OPEN,V?KNOCK /TRUE
	EQUAL?	PRSA,V?SET,V?SHAKE,V?RAISE /TRUE
	EQUAL?	PRSA,V?UNLOCK,V?LOCK,V?CLIMB-UP /TRUE
	EQUAL?	PRSA,V?CLIMB,V?CLIMB-DOWN,V?CLIMB-ON /TRUE
	EQUAL?	PRSA,V?BOARD,V?ENTER,V?ON /TRUE
	EQUAL?	PRSA,V?OFF,V?SET,V?THROW /TRUE
	EQUAL?	PRSA,V?TASTE,V?FUCK,V?RAPE /TRUE
	EQUAL?	PRSA,V?LOOK-INSIDE,V?STAND-ON,V?TIE /TRUE
	EQUAL?	PRSA,V?MUNG,V?KICK,V?KILL /TRUE
	EQUAL?	PRSA,V?KNOCK,V?CUT,V?WHIP /TRUE
	EQUAL?	PRSA,V?BITE,V?PUSH /TRUE
?CCL3:	EQUAL?	PRSI,THING \FALSE
	EQUAL?	PRSA,V?PUT-ON,V?PUT,V?GIVE /TRUE
	RFALSE	


	.FUNCT	IN-CATACOMBS
	EQUAL?	HERE,CATACOMBS,WELL-BOTTOM,LADDER-ROOM /TRUE
	EQUAL?	HERE,BURIAL-CHAMBER,FORGOTTEN-STOREHOUSE /TRUE
	RFALSE	


	.FUNCT	IN-SPACE?
	EQUAL?	HERE,HOLD,STABLE,AT-MAIN-HATCH /TRUE
	EQUAL?	HERE,LONG-CORRIDOR,IN-SPACE,SPACE-YACHT /TRUE
	RFALSE	


	.FUNCT	CANT-SEE,OBJ,STRING
	SET	'P-WON,FALSE-VALUE
	PRINT	YOU-CANT
	EQUAL?	OBJ,ODOR \?CCL3
	PRINTI	"smell"
	JUMP	?CND1
?CCL3:	PRINTI	"see"
?CND1:	ZERO?	OBJ /?CCL5
	ZERO?	OBJ /?CND4
	CALL2	NAME?,OBJ
	ZERO?	STACK \?CND4
?CCL5:	PRINTI	" any"
?CND4:	ZERO?	OBJ \?CCL12
	PRINTC	32
	PRINT	STRING
	JUMP	?CND10
?CCL12:	EQUAL?	OBJ,PRSI \?CCL14
	ICALL1	PRSI-PRINT
	JUMP	?CND10
?CCL14:	ICALL1	PRSO-PRINT
?CND10:	PRINTI	" here."
	CRLF	
	CALL1	STOP
	RSTACK	


	.FUNCT	CANT-VERB-A-PRSO,STRING
	PRINT	YOU-CANT
	PRINT	STRING
	ICALL2	APRINT,PRSO
	PRINTR	"!"


	.FUNCT	OPEN-YOUR-EYES
	FSET?	EYES,MUNGBIT \?CCL3
	CALL	DO-FIRST,STR?67,EYES
	RSTACK	
?CCL3:	CALL	DO-FIRST,STR?135,EYES
	RSTACK	


	.FUNCT	NOW-TIED,OBJ
	PRINTI	"Okay,"
	ICALL1	TPRINT-PRSO
	PRINTI	" is now tied to"
	CALL2	TRPRINT,OBJ
	RSTACK	


	.FUNCT	TELL-HIT-HEAD
	PRINTI	"You bang your bean against"
	ICALL1	TPRINT-PRSO
	PRINTR	" as you attempt this."


	.FUNCT	NOUN-USED,TEST-NOUN,OBJ
	EQUAL?	PRSO,OBJ \?CCL3
	GET	P-NAMW,0
	EQUAL?	STACK,TEST-NOUN /TRUE
?CCL3:	EQUAL?	PRSI,OBJ \FALSE
	GET	P-NAMW,1
	EQUAL?	STACK,TEST-NOUN /TRUE
	RFALSE	


	.FUNCT	ADJ-USED,TEST-ADJ,?TMP1
	GET	P-ADJW,0 >?TMP1
	GET	P-ADJW,1
	EQUAL?	TEST-ADJ,?TMP1,STACK /TRUE
	RFALSE	


	.FUNCT	OFF-VEHICLE?,OBJ
	EQUAL?	OBJ,STOOL,TOILET,FRONT-STOOP /TRUE
	EQUAL?	OBJ,FIRST-SLAB,SECOND-SLAB /TRUE
	RFALSE	


	.FUNCT	OPEN-CLOSED,OBJ
	FSET?	OBJ,OPENBIT \?CCL3
	PRINTI	"open"
	RTRUE	
?CCL3:	PRINTI	"closed"
	RTRUE	


	.FUNCT	WEE
	SET	'AWAITING-REPLY,2
	ICALL	QUEUE,I-REPLY,2
	PRINTR	"Wasn't that fun?"


	.FUNCT	IN-YOUR-PACKAGE,STRING
	PRINTI	"This is the "
	PRINT	STRING
	CALL1	IN-PACKAGE
	RSTACK	


	.FUNCT	IN-PACKAGE
	PRINTI	" that came in your "
	PRINT	LGOP-CAPS
	PRINTI	" package."
	RTRUE	


	.FUNCT	HIS-HER,CAP-H
	ZERO?	CAP-H /?CCL3
	PRINTC	72
	JUMP	?CND1
?CCL3:	PRINTC	104
?CND1:	ZERO?	MALE /?CCL6
	PRINTI	"is"
	RTRUE	
?CCL6:	PRINTI	"er"
	RTRUE	


	.FUNCT	HER-HIS,CAP-H
	ZERO?	CAP-H /?CCL3
	PRINTC	72
	JUMP	?CND1
?CCL3:	PRINTC	104
?CND1:	ZERO?	MALE /?CCL6
	PRINTI	"er"
	RTRUE	
?CCL6:	PRINTI	"is"
	RTRUE	


	.FUNCT	HIM-HER
	ZERO?	MALE /?CCL3
	PRINTI	"him"
	RTRUE	
?CCL3:	PRINTI	"her"
	RTRUE	


	.FUNCT	HER-HIM
	ZERO?	MALE /?CCL3
	PRINTI	"her"
	RTRUE	
?CCL3:	PRINTI	"him"
	RTRUE	


	.FUNCT	HE-SHE,CAP
	ZERO?	MALE /?CCL3
	ZERO?	CAP /?CCL6
	PRINTC	72
	JUMP	?CND1
?CCL6:	PRINTC	104
	JUMP	?CND1
?CCL3:	ZERO?	CAP /?CCL9
	PRINTI	"Sh"
	JUMP	?CND1
?CCL9:	PRINTI	"sh"
?CND1:	PRINTC	101
	RTRUE	


	.FUNCT	SHE-HE,CAP
	ZERO?	MALE /?CCL3
	ZERO?	CAP /?CCL6
	PRINTI	"Sh"
	JUMP	?CND1
?CCL6:	PRINTI	"sh"
	JUMP	?CND1
?CCL3:	ZERO?	CAP /?CCL9
	PRINTC	72
	JUMP	?CND1
?CCL9:	PRINTC	104
?CND1:	PRINTC	101
	RTRUE	


	.FUNCT	CANT-REACH,OBJ
	PRINT	YOU-CANT
	PRINTI	"reach"
	ICALL2	TPRINT,OBJ
	IN?	PROTAGONIST,HERE /?CND1
	PRINTI	" from"
	LOC	PROTAGONIST
	ICALL2	TPRINT,STACK
?CND1:	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	EAGERLY-ACCEPTS
	MOVE	PRSO,PRSI
	PRINTI	"Eagerly,"
	ICALL1	TPRINT-PRSI
	PRINTI	" accepts"
	CALL1	TPRINT-PRSO
	RSTACK	


	.FUNCT	NOT-ON-GROUND,VEHICLE
	PRINTI	"But"
	ICALL2	TPRINT,VEHICLE
	PRINTR	" isn't on the ground!"


	.FUNCT	AND-SIDEKICK,NEW-SIDEKICK-LOC
	CALL2	VISIBLE?,SIDEKICK
	ZERO?	STACK /FALSE
	ZERO?	NEW-SIDEKICK-LOC /?CND4
	MOVE	SIDEKICK,NEW-SIDEKICK-LOC
?CND4:	PRINTI	" and "
	CALL1	DPRINT-SIDEKICK
	RSTACK	


	.FUNCT	PLAYER-CANT-SEE
	FSET?	EYES,MUNGBIT /?CTR2
	EQUAL?	HAND-COVER,EYES \?CCL3
?CTR2:	CALL1	OPEN-YOUR-EYES
	RSTACK	
?CCL3:	ZERO?	LIT \FALSE
	PRINT	TOO-DARK
	CRLF	
	RTRUE	


	.FUNCT	DO-FIRST,STRING,OBJ
	PRINT	YOULL-HAVE-TO
	PRINT	STRING
	ZERO?	OBJ /?CND1
	ICALL2	TPRINT,OBJ
?CND1:	PRINTR	" first."


	.FUNCT	NOT-IN
	PRINTI	"But"
	ICALL1	TPRINT-PRSO
	PRINTI	" isn't "
	FSET?	PRSI,ACTORBIT \?CCL3
	PRINTI	"being held by"
	JUMP	?CND1
?CCL3:	FSET?	PRSI,SURFACEBIT \?CCL5
	PRINTI	"on"
	JUMP	?CND1
?CCL5:	PRINTI	"in"
?CND1:	CALL2	TRPRINT,PRSI
	RSTACK	


	.FUNCT	NO-LID
	PRINTI	"The "
	ICALL2	DPRINT,PRSO
	PRINTR	" has no lid."


	.FUNCT	SORE,STRING
	PRINTI	"You begin to get a sore "
	PRINT	STRING
	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	CANT-USE-THAT-WAY,STRING
	PRINTC	91
	PRINT	YOU-CANT
	PRINTI	"use "
	PRINT	STRING
	PRINTR	" that way.]"


	.FUNCT	RECOGNIZE
	SET	'P-WON,FALSE-VALUE
	PRINTR	"[That sentence isn't one I recognize.]"


	.FUNCT	EXPLETIVE
	PRINTI	" ""Oh "
	ZERO?	NAUGHTY-LEVEL \?CCL3
	PRINTI	"shucks"
	JUMP	?CND1
?CCL3:	EQUAL?	NAUGHTY-LEVEL,1 \?CCL5
	PRINTI	"damn"
	JUMP	?CND1
?CCL5:	PRINTI	"shit"
?CND1:	PRINTI	"! "
	RTRUE	


	.FUNCT	PRONOUN
	EQUAL?	PRSO,ME \?CCL3
	PRINTI	"You"
	RTRUE	
?CCL3:	FSET?	PRSO,PLURALBIT \?CCL5
	PRINTI	"They"
	RTRUE	
?CCL5:	FSET?	PRSO,FEMALEBIT \?CCL7
	PRINTI	"She"
	RTRUE	
?CCL7:	FSET?	PRSO,ACTORBIT \?CCL9
	PRINTI	"He"
	RTRUE	
?CCL9:	PRINTI	"It"
	RTRUE	


	.FUNCT	REFERRING,HIM-HER
	PRINTI	"I don't see wh"
	ZERO?	HIM-HER /?CCL3
	PRINTC	111
	JUMP	?CND1
?CCL3:	PRINTI	"at"
?CND1:	PRINTR	" you're referring to."


	.FUNCT	NO-ONE-HERE,STRING
	PRINTI	"There's no one here to "
	PRINT	STRING
	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	SEE-MANUAL,STRING
	PRINTI	"[You need quotes to "
	PRINT	STRING
	PRINTR	" See the instruction manual section entitled ""Communicating With Infocom's Interactive Fiction.""]"


	.FUNCT	UNIMPORTANT-THING-F
	PRINTR	"That's not important; leave it alone."

	.ENDI
