

	.FUNCT	NAME-CASTLE
	FSET?	HERE,TOUCHBIT /FALSE
	ZERO?	CASTLES-SEEN \?CCL5
	PUTP	HERE,P?SDESC,STR?235
	JUMP	?CND3
?CCL5:	EQUAL?	CASTLES-SEEN,1 \?CCL7
	PUTP	HERE,P?SDESC,STR?236
	JUMP	?CND3
?CCL7:	EQUAL?	CASTLES-SEEN,2 \?CND3
	PUTP	HERE,P?SDESC,STR?237
?CND3:	INC	'CASTLES-SEEN
	RETURN	CASTLES-SEEN


	.FUNCT	CASTLE-NOTE
	EQUAL?	CASTLES-SEEN,2 \?CCL3
	PRINTI	"(There do seem to be quite a few of them around here, eh?) "
	RTRUE	
?CCL3:	EQUAL?	CASTLES-SEEN,3 \FALSE
	PRINTI	"(It's no wonder this section of Mars is considered the Ruined Castle Capital of the Solar System.) "
	RTRUE	


	.FUNCT	RUINED-CASTLE-1-F,RARG
	EQUAL?	RARG,M-ENTER \?CCL3
	CALL1	NAME-CASTLE
	RSTACK	
?CCL3:	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"You stand amongst the ruins of a mighty castle. "
	ICALL1	CASTLE-NOTE
	PRINTI	"The only part of the castle that is more than a pile of rubble is to the north. A path leads out of the ruin to the south."
	RTRUE	


	.FUNCT	THRONE-ROOM-F,RARG
	EQUAL?	RARG,M-LOOK \FALSE
	REMOVE	MITRE
	MOVE	MITRE,HERE
	PRINTI	"This is the "
	PRINTD	HERE
	PRINTI	" of the once-potent "
	PRINTD	MITRE
	PRINTI	", of legendary fame. Of course, the version you've probably heard is significantly warped from What Really Happened.
   In the diseased version of the legend commonly transmitted on Earth, Mitre is called Midas. The King was granted his wish that everything he touched would turn to gold. His greed caught up with him when he transformed even his own daughter into gold.
   "
	PRINTD	MITRE
	PRINTI	"'s wish was, in fact, that everything he touched would turn to"
	PRINT	45-DEGREE-ANGLE
	PRINTI	"s. "
	ZERO?	NAUGHTY-LEVEL \?CCL6
	PRINTC	84
	JUMP	?CND4
?CCL6:	PRINTI	"No one has ever explained this strange wish; the most likely hypothesis is a sexual fetish. In any case, t"
?CND4:	PRINTI	"he tale has a similar climax, with Mitre turning his own daughter into a"
	PRINT	45-DEGREE-ANGLE
	PRINTC	46
	RTRUE	


	.FUNCT	MITRE-CROWN-F
	EQUAL?	PRSA,V?TAKE \?CCL3
	PRINT	MORE-ROYAL-BLOOD
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?EXAMINE \FALSE
	PRINTR	"It's not very round for a crown."


	.FUNCT	GOWN-F
	EQUAL?	PRSA,V?TAKE \FALSE
	ICALL2	PERFORM-PRSA,THETA
	RTRUE	


	.FUNCT	MITRE-F,OARG
	ZERO?	OARG /?CCL3
	EQUAL?	OARG,M-OBJDESC? /TRUE
	PRINTI	"   King Mitre sits upon the throne, looking "
	FSET?	THETA,MUNGBIT \?CCL8
	PRINTI	"dejected and lonely. Next to him is a pile of"
	PRINT	45-DEGREE-ANGLE
	PRINTI	"s. One stands out from the others, thanks to its golden hair and flowing white gown"
	JUMP	?CND6
?CCL8:	PRINTI	"delirious with joy"
?CND6:	PRINTI	". The main entrance of the throne room is to the south, but a tight opening leads north."
	RTRUE	
?CCL3:	EQUAL?	MITRE,WINNER \?CCL10
	EQUAL?	PRSA,V?WHAT \?PRD15
	EQUAL?	PRSO,LGOP /?CTR12
?PRD15:	EQUAL?	PRSA,V?TELL-ABOUT \?CCL13
	EQUAL?	PRSO,ME \?CCL13
	EQUAL?	PRSI,LGOP \?CCL13
?CTR12:	PRINTR	"""Leather fetishists, every one of them. Me, I'm not into fetishes."""
?CCL13:	EQUAL?	PRSA,V?CHEER \?CCL22
	EQUAL?	PRSO,ROOMS \?CCL22
	SET	'WINNER,PROTAGONIST
	ICALL2	PERFORM-PRSA,MITRE
	SET	'WINNER,MITRE
	RTRUE	
?CCL22:	EQUAL?	PRSA,V?TOUCH \?CCL26
	FSET?	PRSO,TAKEBIT \?CCL26
	EQUAL?	PRSO,COMIC-BOOK,GARMENT /?CCL26
	SET	'WINNER,PROTAGONIST
	ICALL	PERFORM,V?GIVE,PRSO,MITRE
	SET	'WINNER,MITRE
	RTRUE	
?CCL26:	PRINTI	"""I don't feel like talking. I'm too "
	FSET?	THETA,MUNGBIT \?CND30
	PRINTI	"un"
?CND30:	PRINTI	"happy."""
	CRLF	
	CALL1	STOP
	RSTACK	
?CCL10:	EQUAL?	PRSA,V?EXAMINE \?CCL33
	PRINTI	"The old king looks very "
	FSET?	THETA,MUNGBIT \?CCL36
	PRINTI	"down"
	JUMP	?CND34
?CCL36:	PRINTI	"up"
?CND34:	PRINTR	". His appearance is rather odd, since his clothes, his jewelry, his crown, even his very throne, all have a rather angular appearance."
?CCL33:	EQUAL?	PRSA,V?ASK-ABOUT \?PRD40
	EQUAL?	PRSI,THETA /?CTR37
?PRD40:	EQUAL?	PRSA,V?SHOW \?CCL38
	EQUAL?	PRSO,THETA \?CCL38
?CTR37:	FSET?	THETA,MUNGBIT \?CCL47
	PRINTR	"The king weeps pitifully."
?CCL47:	PRINTR	"The king beams."
?CCL38:	EQUAL?	PRSA,V?GIVE \?CCL49
	EQUAL?	PRSI,MITRE \?CCL49
	REMOVE	PRSO
	PRINTI	"As Mitre touches"
	ICALL1	TPRINT-PRSO
	PRINTC	44
	ICALL2	TPRINT,PILE-OF-ANGLES
	PRINTR	" becomes a bit larger."
?CCL49:	EQUAL?	PRSA,V?TOUCH \?CCL53
	PRINTR	"It only works the other way."
?CCL53:	EQUAL?	PRSA,V?SHAKE-WITH \FALSE
	EQUAL?	PRSO,HANDS \FALSE
	PRINTI	"As you join the other angles in the pile, life becomes very boring. Two centuries later, following Mitre's death, the "
	PRINTD	PILE-OF-ANGLES
	PRINTI	" is sold to a geometry teacher on Baffin Island, who uses you to demonstrate bisections, trigonometric proofs, and basic picture framing techniques."
	CRLF	
	CALL1	FINISH
	RSTACK	


	.FUNCT	THETA-F
	CALL2	ADJ-USED,W?NUMBER
	ZERO?	STACK /?CCL3
	EQUAL?	P-NUMBER,45 /?CCL3
	CALL1	NO-X-DEGREE-ANGLE
	RSTACK	
?CCL3:	EQUAL?	THETA,WINNER \?CCL7
	EQUAL?	PRSA,V?WHAT \?PRD12
	EQUAL?	PRSO,LGOP /?CTR9
?PRD12:	EQUAL?	PRSA,V?TELL-ABOUT \?CCL10
	EQUAL?	PRSO,ME \?CCL10
	EQUAL?	PRSI,LGOP \?CCL10
?CTR9:	PRINTR	"""The travelling acrobatic troupe! I saw them while I was mooning on Phobos. Their costumes are made of pure Chomperhide leather."""
?CCL10:	PRINTR	"The princess, whose recent experience has made her more obtuse, just looks at you dumbly."
?CCL7:	EQUAL?	PRSA,V?MEASURE \?CCL19
	FSET?	THETA,MUNGBIT \?CCL19
	ICALL2	PERFORM-PRSA,PILE-OF-ANGLES
	RTRUE	
?CCL19:	EQUAL?	PRSA,V?EXAMINE \?CCL23
	FSET?	THETA,MUNGBIT \?CCL26
	PRINTR	"The angle has the sort of golden hair and satiny robes that one normally associates with princesses."
?CCL26:	PRINTR	"The princess, once acute, is now cute."
?CCL23:	EQUAL?	PRSA,V?FUCK,V?KISS,V?TAKE /?CTR27
	EQUAL?	PRSA,V?BEND,V?TOUCH \?CCL28
?CTR27:	PRINTI	"Mitre growls, ""Keep "
	PRINTD	HANDS
	PRINTR	"s off my daughter."""
?CCL28:	EQUAL?	PRSA,V?MARRY \FALSE
	FSET?	THETA,MUNGBIT \?CCL35
	CALL2	WANT-CHILDREN,STR?239
	RSTACK	
?CCL35:	PRINTR	"""Only one of royal blood shall bisect ... er, wed ... my Theta!"" bellows Mitre."


	.FUNCT	WANT-CHILDREN,STRING
	SET	'AWAITING-REPLY,2
	ICALL	QUEUE,I-REPLY,2
	PRINTI	"Would you really want "
	PRINT	STRING
	PRINTR	" children?"


	.FUNCT	EIGHTY-TWO-DEGREE-ANGLE-F
	CALL2	ADJ-USED,W?NUMBER
	ZERO?	STACK /?CCL3
	EQUAL?	P-NUMBER,82 /?CCL3
	CALL1	NO-X-DEGREE-ANGLE
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?MEASURE \FALSE
	FSET?	EIGHTY-TWO-DEGREE-ANGLE,UNTEEDBIT /FALSE
	PRINTR	"82 degrees."


	.FUNCT	NO-X-DEGREE-ANGLE
	PRINT	YOU-CANT-SEE-ANY
	PRINTN	P-NUMBER
	PRINTR	" degree angle here!"


	.FUNCT	GENERIC-ANGLE-F
	FSET?	THETA,MUNGBIT /FALSE
	RETURN	EIGHTY-TWO-DEGREE-ANGLE


	.FUNCT	PILE-OF-ANGLES-F
	CALL2	ADJ-USED,W?NUMBER
	ZERO?	STACK /?CCL3
	EQUAL?	P-NUMBER,45 /?CCL3
	CALL1	NO-X-DEGREE-ANGLE
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?COUNT \?CCL7
	PRINTR	"Lots."
?CCL7:	EQUAL?	PRSA,V?TAKE \?CCL9
	PRINTI	"The "
	PRINTD	PILE-OF-ANGLES
	PRINTI	" is too big to carry."
	FSET?	THETA,MUNGBIT \?CND10
	PRINTI	" Besides, other than"
	ICALL2	TPRINT,THETA
	PRINTR	", none of them are interesting."
?CND10:	CRLF	
	RTRUE	
?CCL9:	EQUAL?	PRSA,V?MEASURE \FALSE
	PRINTR	"45 degrees."


	.FUNCT	FROG-CROWN-F
	EQUAL?	PRSA,V?TAKE \?CCL3
	PRINT	MORE-ROYAL-BLOOD
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?EXAMINE \FALSE
	PRINTR	"It's tiny."


	.FUNCT	RUINED-CASTLE-2-F,RARG
	EQUAL?	RARG,M-ENTER \?CCL3
	FCLEAR	RUINED-CASTLE-2,MUNGBIT
	CALL1	NAME-CASTLE
	RSTACK	
?CCL3:	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"This ancient castle now lies in ruins. "
	ICALL1	CASTLE-NOTE
	PRINTI	"All that remains of its once-proud ramparts are dust and rubble, and an occasional stone block. A path leads away from the ruin to the west"
	CALL2	UNCHARTABLE-DESERT,STR?241
	RSTACK	


	.FUNCT	UNCHARTABLE-DESERT,STRING
	PRINTI	". To the "
	PRINT	STRING
	PRINTI	": unchartable desert."
	RTRUE	


	.FUNCT	FROG-F
	EQUAL?	PRSA,V?LISTEN,V?TELL /?CTR2
	EQUAL?	PRSA,V?GIVE \?CCL3
	EQUAL?	PRSI,FROG \?CCL3
?CTR2:	PRINTI	"""Ribit."""
	CRLF	
	EQUAL?	PRSA,V?TELL \TRUE
	ICALL1	STOP
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?SUCK,V?TASTE,V?EAT /?CTR10
	EQUAL?	PRSA,V?SMELL \?CCL11
?CTR10:	PRINT	YECHH
	RTRUE	
?CCL11:	EQUAL?	PRSA,V?EXAMINE \?CCL15
	PRINTR	"You realize what aroused your attention: the tiny gold crown on the frog's head. The frog is otherwise totally ordinary. Ordinary for a frog, that is. By any other measure it is a repulsive creature, with swollen eyes, oozing warts, slimy skin, and a grating croak."
?CCL15:	EQUAL?	PRSA,V?TOUCH \?CCL17
	PRINTI	"Huge, ugly warts cover every inch of "
	PRINTD	YOUR-BODY
	ZERO?	NAUGHTY-LEVEL \?CCL20
	PRINTI	", but"
	JUMP	?CND18
?CCL20:	PRINTI	". Fortunately for your sex life,"
?CND18:	PRINTR	" they quickly fade away."
?CCL17:	EQUAL?	PRSA,V?MARRY \?CCL22
	CALL2	WANT-CHILDREN,STR?243
	RSTACK	
?CCL22:	EQUAL?	PRSA,V?KISS \FALSE
	PRINTI	"You lean forward"
	FSET?	EYES,MUNGBIT \?CCL27
	PRINTI	" with "
	PRINTD	EYES
	PRINTC	32
	EQUAL?	EYES,HAND-COVER \?CCL30
	PRINTI	"covered"
	JUMP	?CND28
?CCL30:	PRINTI	"closed"
?CND28:	FSET?	NOSE,MUNGBIT \?CCL33
	FSET?	EARS,MUNGBIT \?CCL36
	PRINTC	44
	JUMP	?CND34
?CCL36:	PRINTI	" and"
?CND34:	PRINTC	32
	PRINTD	NOSE
	PRINTI	" shut"
	FSET?	EARS,MUNGBIT \?CCL39
	FSET?	MOUTH,MUNGBIT \?CCL42
	PRINTC	44
	JUMP	?CND40
?CCL42:	PRINTI	" and"
?CND40:	PRINTC	32
	PRINTD	EARS
	PRINTC	32
	EQUAL?	EARS,HAND-COVER \?CCL45
	PRINTI	"covered"
	JUMP	?CND43
?CCL45:	PRINTI	"stuffed up"
?CND43:	FSET?	MOUTH,MUNGBIT \?CCL48
	ICALL1	FROG-SEX-SCENE
	RTRUE	
?CCL48:	PRINT	ABOUT-TO-KISS
	PRINTR	"the thought of slimy frog lips pressing against your own makes you shudder away."
?CCL39:	PRINT	ABOUT-TO-KISS
	PRINTR	"the creature lets loose a loud, croaking ""ribit."" You admit that you are incapable of kissing under such circumstances."
?CCL33:	PRINT	ABOUT-TO-KISS
	PRINTR	"the stench of old pond scum overwhelms you, and you lurch back, retching."
?CCL27:	PRINT	ABOUT-TO-KISS
	PRINTR	"the sight of its green warts and slimy skin make it impossible to continue."


	.FUNCT	FROG-SEX-SCENE
	MOVE	FROG,LOCAL-GLOBALS
	MOVE	BLENDER,HERE
	ICALL	INCREMENT-SCORE,17,17,TRUE-VALUE
	ICALL1	OPEN-EYES-AND-REMOVE-HANDS
	PRINTI	" and your lips smeared with balm. Planting "
	PRINTD	MOUTH
	PRINTI	" solidly against the frog's, you kiss deeply. "
	ZERO?	NAUGHTY-LEVEL \?CCL3
	PRINTI	"The kiss is surprisingly pleasant, until you notice that you're embracing a "
	ZERO?	MALE /?CCL6
	PRINTI	"beautiful princess. Sh"
	JUMP	?CND4
?CCL6:	PRINTI	"handsome prince. H"
?CND4:	PRINTI	"e leaps back, blushing deeply. ""We're ... we're not married,"" "
	ICALL1	SHE-HE
	PRINTI	" stammers. Then, still reddening, "
	ICALL1	SHE-HE
	PRINTI	" vanishes into thin air! Y"
	JUMP	?CND1
?CCL3:	FSET	RUINED-CASTLE-2,MUNGBIT
	PRINTI	"When you feel a tongue sliding into "
	PRINTD	MOUTH
	PRINTI	", revulsion gives way to pleasure, as the no-longer-enchanted but quite enchanting prince"
	ZERO?	MALE /?CND7
	PRINTI	"ss"
?CND7:	PRINTI	" presses against you. "
	EQUAL?	NAUGHTY-LEVEL,1 \?CCL11
	PRINTI	"Some time later, after the prince"
	ZERO?	MALE /?CND12
	PRINTI	"ss"
?CND12:	PRINTI	" has departed..."
	JUMP	?CND9
?CCL11:	ZERO?	MALE /?CCL16
	PRINTI	"Rubbing her hot, naked body against yours, s"
	JUMP	?CND14
?CCL16:	PRINTI	"As your arms grip his naked, muscular back, "
?CND14:	PRINTI	"he effortlessly slips off your "
	ICALL2	DPRINT,GARMENT
	PRINTI	". A warm and wild feeling springs from your loins, spreading like a fiery potion through your veins. Within moments you are joined in passionate love, and just as a quick and lustful orgasm seems inevitable, a force crackles in the air, and you are alone, naked, sweating, and unsatisfied."
?CND9:	CRLF	
	PRINTI	"   As you gather up your garment and put it on, y"
?CND1:	PRINTI	"ou notice"
	ICALL2	APRINT,BLENDER
	PRINTI	" on the ground. "
	PRINT	ITS-ENGRAVED
	IN?	SIDEKICK,HERE \?CND17
	PRINTC	32
	ICALL1	DPRINT-SIDEKICK
	PRINTR	" is at the other end of the ruin, sifting through some rubble, oblivious to your ""experience."""
?CND17:	CRLF	
	RTRUE	


	.FUNCT	BLENDER-F
	EQUAL?	PRSA,V?READ \?CCL3
	ZERO?	NAUGHTY-LEVEL /?CCL6
	PRINTI	"""Dearest,"
	CRLF	
	EQUAL?	NAUGHTY-LEVEL,2 \?CCL9
	PRINTI	"   Sorry to leave so abruptly; p"
	JUMP	?CND7
?CCL9:	PRINTI	"   P"
?CND7:	PRINTI	"erhaps some day we will meet again"
	EQUAL?	NAUGHTY-LEVEL,2 \?CND10
	PRINTI	", and finish what we began"
?CND10:	PRINTI	". "
	JUMP	?CND4
?CCL6:	PRINTC	34
?CND4:	PRINTR	"Please accept this token of my gratitude for delivering me from enchantment."""
?CCL3:	EQUAL?	PRSA,V?EXAMINE \?CCL13
	CALL	NOUN-USED,W?ENGRAVING,BLENDER
	ZERO?	STACK /?CCL16
	ICALL	PERFORM,V?READ,BLENDER
	RTRUE	
?CCL16:	PRINT	ITS-ENGRAVED
	CRLF	
	RTRUE	
?CCL13:	EQUAL?	PRSA,V?ON \?CCL18
	PRINTR	"""Whirr."""
?CCL18:	EQUAL?	PRSA,V?LOOK-INSIDE \?CCL20
	PRINTR	"It's empty."
?CCL20:	EQUAL?	PRSA,V?PUT \FALSE
	EQUAL?	PRSI,BLENDER \FALSE
	PRINTI	"But"
	ICALL1	TPRINT-PRSO
	PRINTR	" doesn't need blending."


	.FUNCT	RUINED-CASTLE-3-F,RARG
	EQUAL?	RARG,M-ENTER \?CCL3
	CALL1	NAME-CASTLE
	RSTACK	
?CCL3:	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"Wind whistles among the fallen archways, crumbled balustrades, and black circle of this ruined castle. "
	ICALL1	CASTLE-NOTE
	PRINTI	"Paths lead east and northwest through the rubble."
	RTRUE	


	.FUNCT	MOUSE-F
	EQUAL?	PRSA,V?CLICK \?CCL3
	SET	'AWAITING-REPLY,2
	ICALL	QUEUE,I-REPLY,2
	PRINTR	"You expect maybe a window to open?"
?CCL3:	EQUAL?	PRSA,V?SHOW \?CCL5
	EQUAL?	PRSO,PAINTING \?CCL5
	FSET?	PAINTING,UNTEEDBIT /?CCL5
	FCLEAR	MOUSE,TRYTAKEBIT
	FSET	MOUSE,TOUCHBIT
	ICALL	QUEUE,I-MOUSE,2
	PRINTR	"The mouse freezes with fear."
?CCL5:	EQUAL?	PRSA,V?GIVE \?CCL10
	EQUAL?	PRSI,MOUSE \?CCL10
	PRINTR	"Marsmice, like earthmice, prefer cheese."
?CCL10:	EQUAL?	PRSA,V?CATCH \?CCL14
	ICALL	PERFORM,V?TAKE,MOUSE
	RTRUE	
?CCL14:	CALL2	TOUCHING?,MOUSE
	ZERO?	STACK /?CCL16
	IN?	MOUSE,HERE \?CCL16
	FSET?	MOUSE,TRYTAKEBIT \?CCL16
	PRINTR	"The little fellow scurries easily away from you."
?CCL16:	EQUAL?	PRSA,V?FOLLOW \?CCL21
	EQUAL?	P-PRSA-WORD,W?CHASE \?CCL21
	IN?	MOUSE,HERE \?CCL21
	FSET?	MOUSE,TRYTAKEBIT \?CCL21
	ICALL	PERFORM,V?TAKE,MOUSE
	RTRUE	
?CCL21:	EQUAL?	PRSA,V?TAKE \?CCL27
	FSET?	MOUSE,MUNGBIT /?CCL27
	CALL2	CCOUNT,PROTAGONIST
	LESS?	STACK,11 \?CCL27
	FSET	MOUSE,MUNGBIT
	ICALL	INCREMENT-SCORE,14,9,TRUE-VALUE
	RFALSE	
?CCL27:	EQUAL?	PRSA,V?MEASURE \?CCL32
	PRINTR	"Tiny."
?CCL32:	EQUAL?	PRSA,V?TOUCH \FALSE
	PRINTR	"The mouse squeaks happily."


	.FUNCT	I-MOUSE
	FSET	MOUSE,TRYTAKEBIT
	IN?	MOUSE,RUINED-CASTLE-1 \?CND1
	FCLEAR	MOUSE,TOUCHBIT
?CND1:	IN?	MOUSE,HERE \FALSE
	PRINTR	"   The mouse relaxes and begins scampering about."


	.FUNCT	ROYAL-DOCKS-F,RARG
	EQUAL?	RARG,M-LOOK \FALSE
	ZERO?	NAUGHTY-LEVEL \?CCL6
	PRINTI	"This dock juts"
	JUMP	?CND4
?CCL6:	PRINTI	"During the peak of King Mitre's reign, a cruel joke went around the kingdom that Mitre's two greatest loves were his Royal Docks and his Royal Ducks. The joke was never very good and has long since been forgotten, and the ducks perished years ago from a sexually transmitted disease, but the docks remain, jutting"
?CND4:	PRINTI	" into a wide Martian Canal which flows from west to east. Behind you, to the south, is a ruined castle."
	RTRUE	


	.FUNCT	BARGE-F,OARG
	ZERO?	OARG /?CCL3
	EQUAL?	OARG,M-OBJDESC? /TRUE
	PRINTI	"   A barge, hand-crafted from fine Martian cedarwood, is "
	EQUAL?	HERE,CANAL \?CCL8
	PRINTI	"floating nearby."
	RTRUE	
?CCL8:	PRINTI	"moored at the end of the dock."
	RTRUE	
?CCL3:	EQUAL?	HERE,CANAL \?CCL10
	IN?	PROTAGONIST,RAFT \?CCL10
	EQUAL?	RAFT-LOC-NUM,BARGE-LOC-NUM /?CCL10
	CALL2	CANT-SEE,BARGE
	RSTACK	
?CCL10:	EQUAL?	PRSA,V?SINK \?CCL15
	PRINTR	"The barge is unsinkable. (Then again, so was the Titanic.)"
?CCL15:	EQUAL?	PRSA,V?LAUNCH,V?UNTIE \?CCL17
	PRINTI	"The barge isn't moored"
	IN?	BARGE,CANAL /?CND18
	PRINTI	" with ropes"
?CND18:	PRINT	PERIOD-CR
	RTRUE	
?CCL17:	EQUAL?	PRSA,V?EXAMINE \?CCL21
	CALL	NOUN-USED,W?CONTROL,BARGE
	ZERO?	STACK \?CTR23
	CALL	NOUN-USED,W?CONTROLS,BARGE
	ZERO?	STACK \?CTR23
	CALL	NOUN-USED,W?BUTTONS,BARGE
	ZERO?	STACK /?CCL24
?CTR23:	PRINTI	"The controls consist of a "
	PRINTD	ORANGE-BUTTON
	PRINTI	", and a "
	PRINTD	PURPLE-BUTTON
	PRINTR	". Both buttons have writing on them."
?CCL24:	PRINTI	"This large barge could host a host of royal guests."
	EQUAL?	HERE,CANAL /?CND28
	PRINTI	" The barge rests immobile at the dockside, despite a strong current and no visible mooring lines."
?CND28:	PRINTI	" There are some simple controls on the side of the barge"
	EQUAL?	HERE,CANAL /?CND30
	PRINTI	" nearest the dock"
?CND30:	PRINT	PERIOD-CR
	RTRUE	
?CCL21:	EQUAL?	PRSA,V?READ \?CCL33
	ICALL2	PERFORM-PRSA,ORANGE-BUTTON
	ICALL2	PERFORM-PRSA,PURPLE-BUTTON
	RTRUE	
?CCL33:	EQUAL?	PRSA,V?PUSH \?CCL35
	CALL	NOUN-USED,W?CONTROL,BARGE
	ZERO?	STACK \?CTR34
	CALL	NOUN-USED,W?CONTROLS,BARGE
	ZERO?	STACK \?CTR34
	CALL	NOUN-USED,W?BUTTONS,BARGE
	ZERO?	STACK /?CCL35
?CTR34:	ICALL2	PERFORM-PRSA,ORANGE-BUTTON
	PRINTI	"   "
	ICALL2	PERFORM-PRSA,PURPLE-BUTTON
	RTRUE	
?CCL35:	EQUAL?	PRSA,V?SET \?CCL42
	PRINT	NO-STEERING
	RTRUE	
?CCL42:	EQUAL?	PRSA,V?TAKE,V?BOARD \?CCL44
	EQUAL?	HERE,CANAL \?CCL44
	IN?	PROTAGONIST,RAFT \?CCL44
	MOVE	PROTAGONIST,BARGE
	SET	'OHERE,FALSE-VALUE
	PRINTI	"Grabbing onto the barge, you"
	ICALL2	AND-SIDEKICK,BARGE
	MOVE	RAFT,PROTAGONIST
	SET	'RAFT-HELD,FALSE-VALUE
	PRINTI	" climb in"
	PRINT	KEEP-IT-FROM-FLOATING-AWAY
	RTRUE	
?CCL44:	EQUAL?	PRSA,V?PUT-ON \?CCL49
	EQUAL?	PRSI,BARGE \?CCL49
	ICALL	PERFORM,V?PUT,PRSO,BARGE
	RTRUE	
?CCL49:	EQUAL?	PRSA,V?SMELL \?CCL53
	CALL2	NO-SCRATCH-N-SNIFF,STR?247
	RSTACK	
?CCL53:	EQUAL?	PRSA,V?SHAKE \?CCL55
	IN?	PROTAGONIST,BARGE \?CCL55
	CALL1	SHAKE-BOAT
	RSTACK	
?CCL55:	EQUAL?	PRSA,V?LAND \FALSE
	SET	'AWAITING-REPLY,2
	ICALL	QUEUE,I-REPLY,2
	PRINTI	"Read any "
	PRINTD	ORANGE-BUTTON
	PRINTR	"s lately?"


	.FUNCT	GENERIC-BARGE-F
	RETURN	BARGE


	.FUNCT	SHAKE-BOAT
	PRINTI	"You knock yourself overboard."
	CRLF	
	CRLF	
	ICALL	PERFORM,V?BOARD,CANAL-OBJECT
	RTRUE	


	.FUNCT	ORANGE-BUTTON-F,ATBARGE
	CALL1	CHECK-BARGE-LOC >ATBARGE
	ZERO?	ATBARGE \?CCL3
	ICALL2	CANT-SEE,ORANGE-BUTTON
	JUMP	?CND1
?CCL3:	EQUAL?	ATBARGE,RAFT \?CND1
	CALL2	TOUCHING?,ORANGE-BUTTON
	ZERO?	STACK /?CND1
	ICALL2	CANT-REACH,PRSO
?CND1:	EQUAL?	PRSA,V?EXAMINE,V?READ \?CCL9
	PRINTI	"The "
	PRINTD	ORANGE-BUTTON
	PRINTI	" reads: MagnetoMoor O"
	ZERO?	MOORING-ON /?CCL12
	PRINTC	110
	JUMP	?CND10
?CCL12:	PRINTI	"ff"
?CND10:	PRINT	PERIOD-CR
	RTRUE	
?CCL9:	EQUAL?	PRSA,V?PUSH \FALSE
	ZERO?	MOORING-ON /?CCL17
	SET	'MOORING-ON,FALSE-VALUE
	JUMP	?CND15
?CCL17:	SET	'MOORING-ON,TRUE-VALUE
?CND15:	PRINT	WRITING-CHANGES
	PRINTC	46
	IN?	BARGE,CANAL /?CCL20
	ZERO?	MOORING-ON \?CCL20
	EQUAL?	HERE,ICY-DOCK /?CCL20
	MOVE	BARGE,CANAL
	ZERO?	RAFT-HELD /?CND24
	IN?	PROTAGONIST,BARGE \?CND24
	MOVE	RAFT,CANAL
	SET	'RAFT-LOC-NUM,BARGE-LOC-NUM
?CND24:	FCLEAR	BARGE,NDESCBIT
	ICALL	QUEUE,I-CANAL,-1
	PRINTI	" The barge s"
	ZERO?	BARGE-UNDER-POWER /?CCL30
	PRINTI	"hoot"
	JUMP	?CND28
?CCL30:	PRINTI	"lide"
?CND28:	PRINTI	"s away from the dock, into the deeper waters of the canal."
	CRLF	
	IN?	PROTAGONIST,BARGE \TRUE
	CRLF	
	ICALL2	GOTO,BARGE
	RTRUE	
?CCL20:	CALL1	BARGE-DOCKS
	ZERO?	STACK \TRUE
	CRLF	
	RTRUE	


	.FUNCT	CHECK-BARGE-LOC,?TMP1
	IN?	PROTAGONIST,BARGE /?CTR2
	IN?	BARGE,CANAL /?PRD6
	LOC	BARGE >?TMP1
	LOC	PROTAGONIST
	EQUAL?	?TMP1,STACK /?CTR2
?PRD6:	EQUAL?	HERE,CANAL \?CCL3
	IN?	BARGE,CANAL \?CCL3
	EQUAL?	BARGE-LOC-NUM,RAFT-LOC-NUM \?CCL3
?CTR2:	RETURN	BARGE
?CCL3:	EQUAL?	HERE,CANAL \FALSE
	CALL1	BARGE-VISIBLE-AT-DOCK
	ZERO?	STACK /FALSE
	RETURN	RAFT


	.FUNCT	PURPLE-BUTTON-F,ATBARGE
	CALL1	CHECK-BARGE-LOC >ATBARGE
	ZERO?	ATBARGE \?CCL3
	ICALL2	CANT-SEE,PURPLE-BUTTON
	JUMP	?CND1
?CCL3:	EQUAL?	ATBARGE,RAFT \?CND1
	CALL2	TOUCHING?,PURPLE-BUTTON
	ZERO?	STACK /?CND1
	ICALL2	CANT-REACH,PRSO
?CND1:	EQUAL?	PRSA,V?EXAMINE,V?READ \?CCL9
	PRINTI	"The "
	PRINTD	PURPLE-BUTTON
	PRINTI	" reads: "
	ZERO?	BARGE-UNDER-POWER /?CCL12
	PRINTI	"Full Speed Ahead"
	JUMP	?CND10
?CCL12:	PRINTI	"Go With The Flow"
?CND10:	PRINT	PERIOD-CR
	RTRUE	
?CCL9:	EQUAL?	PRSA,V?PUSH \FALSE
	PRINT	WRITING-CHANGES
	ZERO?	BARGE-UNDER-POWER /?CCL17
	SET	'BARGE-UNDER-POWER,FALSE-VALUE
	JUMP	?CND15
?CCL17:	SET	'BARGE-UNDER-POWER,TRUE-VALUE
	IN?	PROTAGONIST,RAFT \?CND15
	EQUAL?	HERE,CANAL \?CND15
	ICALL1	BARGE-FORGES-AHEAD
?CND15:	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	BARGE-FORGES-AHEAD
	LESS?	BARGE-LOC-NUM,16 \?CCL3
	ZERO?	MOORING-ON /?CCL3
	SET	'BARGE-LOC-NUM,15
	MOVE	BARGE,WATTZ-UPP-DOCK
	JUMP	?CND1
?CCL3:	SET	'BARGE-LOC-NUM,36
	MOVE	BARGE,ICY-DOCK
?CND1:	PRINTI	". The barge, under power, forges ahead and disappears from sight"
	RTRUE	


	.FUNCT	CANAL-LOC
	EQUAL?	HERE,CANAL \FALSE
	IN?	PROTAGONIST,BARGE /?CTR4
	RETURN	RAFT-LOC-NUM
?CTR4:	RETURN	BARGE-LOC-NUM


	.FUNCT	SET-RAFT-LOC
	EQUAL?	HERE,CANAL \?CCL3
	SET	'RAFT-LOC-NUM,BARGE-LOC-NUM
	RETURN	RAFT-LOC-NUM
?CCL3:	EQUAL?	HERE,HICKORY-AND-DICKORY-DOCK \?CCL5
	SET	'RAFT-LOC-NUM,-1
	RETURN	RAFT-LOC-NUM
?CCL5:	EQUAL?	HERE,ROYAL-DOCKS \?CCL7
	SET	'RAFT-LOC-NUM,1
	RETURN	RAFT-LOC-NUM
?CCL7:	EQUAL?	HERE,BABY-DOCK \?CCL9
	SET	'RAFT-LOC-NUM,6
	RETURN	RAFT-LOC-NUM
?CCL9:	EQUAL?	HERE,DONALD-DOCK \?CCL11
	SET	'RAFT-LOC-NUM,7
	RETURN	RAFT-LOC-NUM
?CCL11:	EQUAL?	HERE,WATTZ-UPP-DOCK \?CCL13
	SET	'RAFT-LOC-NUM,15
	RETURN	RAFT-LOC-NUM
?CCL13:	SET	'RAFT-LOC-NUM,10
	RETURN	RAFT-LOC-NUM


	.FUNCT	CANAL-OBJECT-F
	CALL2	ADJ-USED,W?SMALL
	ZERO?	STACK /?CCL3
	CALL1	UNIMPORTANT-THING-F
	RSTACK	
?CCL3:	EQUAL?	HERE,DUNETOP,MINARET \?CCL5
	CALL2	TOUCHING?,CANAL-OBJECT
	ZERO?	STACK /?CCL5
	CALL2	CANT-REACH,CANAL-OBJECT
	RSTACK	
?CCL5:	EQUAL?	PRSA,V?SWIM,V?ENTER,V?BOARD /?CTR8
	EQUAL?	PRSA,V?CRAWL-UNDER \?CCL9
?CTR8:	CALL2	UNTOUCHABLE?,CANAL-OBJECT
	ZERO?	STACK /?CCL14
	ICALL2	CANT-REACH,CANAL-OBJECT
	JUMP	?CND12
?CCL14:	EQUAL?	HERE,ICY-DOCK \?CCL16
	PRINTI	"The current sucks you under"
	EQUAL?	NAUGHTY-LEVEL,2 \?CND17
	PRINTI	", which really sucks"
?CND17:	ICALL2	JIGS-UP,STR?248
	JUMP	?CND12
?CCL16:	PRINTI	"In The Canal
   As you swim in the cool waters of the canal, a slimy tentacle touches you, convincing you that it's safer back "
?CND12:	LOC	PROTAGONIST
	EQUAL?	STACK,RAFT,BARGE \?CCL21
	PRINTI	"in"
	LOC	PROTAGONIST
	ICALL2	TRPRINT,STACK
	JUMP	?CND19
?CCL21:	PRINTI	"on the dock."
	CRLF	
?CND19:	CRLF	
	CALL1	DESCRIBE-ROOM
	RSTACK	
?CCL9:	EQUAL?	PRSA,V?CROSS \?CCL23
	ICALL	PERFORM,V?ENTER,CANAL-OBJECT
	RTRUE	
?CCL23:	EQUAL?	PRSA,V?PUT \?CCL25
	EQUAL?	P-PRSA-WORD,W?THROW \?CCL25
	EQUAL?	PRSO,RAFT \?CCL25
	FSET?	RAFT,UNTEEDBIT /?CCL25
	IN?	PROTAGONIST,RAFT /?CCL25
	MOVE	RAFT,HERE
	SET	'RAFT-HELD,TRUE-VALUE
	ICALL	PERFORM,V?DROP,RAFT
	RTRUE	
?CCL25:	EQUAL?	PRSA,V?THROW,V?PUT \?CCL32
	EQUAL?	PRSI,CANAL-OBJECT \?CCL32
	EQUAL?	PRSO,RAFT \?CCL37
	FSET?	RAFT,UNTEEDBIT /?CTR39
	FSET?	RAFT,MUNGBIT \?CCL40
?CTR39:	REMOVE	RAFT
	PRINTI	"It sinks like a stone."
	FSET?	RAFT,UNTEEDBIT \?CND43
	PRINTR	" I guess a raf doesn't float nearly as well as a raft."
?CND43:	CRLF	
	RTRUE	
?CCL40:	ZERO?	RAFT-HELD \?CTR45
	IN?	RAFT,CANAL \?CCL46
?CTR45:	PRINT	ALREADY-IS
	RTRUE	
?CCL46:	PRINTI	"The raft is now "
	EQUAL?	HERE,ICY-DOCK \?CCL51
	MOVE	RAFT,HERE
	PRINTI	"in the water"
	PRINT	PINNED
	RTRUE	
?CCL51:	SET	'RAFT-HELD,TRUE-VALUE
	MOVE	RAFT,HERE
	EQUAL?	HERE,CANAL \?CND52
	SET	'RAFT-LOC-NUM,BARGE-LOC-NUM
?CND52:	PRINTI	"bobbing in the canal."
	EQUAL?	HERE,CANAL \?CCL55
	ZERO?	BARGE-UNDER-POWER /?CND54
?CCL55:	PRINTI	" If you weren't holding it, it would surely be "
	EQUAL?	HERE,CANAL \?CCL60
	PRINTR	"left behind."
?CCL60:	PRINTR	"carried away."
?CND54:	CRLF	
	RTRUE	
?CCL37:	REMOVE	PRSO
	EQUAL?	PRSO,TORCH \?CCL63
	FSET?	TORCH,ONBIT \?CCL63
	PRINTI	"""Phfffft!"
	JUMP	?CND61
?CCL63:	PRINTI	"""Glub."
?CND61:	PRINTI	""" "
	FSET?	PRSO,PLURALBIT \?CCL68
	PRINTI	"They're"
	JUMP	?CND66
?CCL68:	PRINTI	"It's"
?CND66:	PRINTI	" gone"
	EQUAL?	PRSO,BABY /?CCL70
	CALL	ULTIMATELY-IN?,BABY,PRSO
	ZERO?	STACK /?CND69
?CCL70:	PRINTI	", you heartless baby murderer, you"
?CND69:	PRINT	PERIOD-CR
	RTRUE	
?CCL32:	EQUAL?	PRSA,V?LOOK-INSIDE \FALSE
	ICALL2	PERFORM-PRSA,WATER
	RTRUE	


	.FUNCT	DOCK-OBJECT-F,NUM,DOCK-ROOM
	CALL1	CANAL-LOC >NUM
	EQUAL?	HERE,CANAL \?CND1
	EQUAL?	NUM,-1,1,6 /?CND1
	EQUAL?	NUM,7,10,15 /?CND1
	ICALL2	CANT-SEE,DOCK-OBJECT
	RTRUE	
?CND1:	EQUAL?	HERE,DUNETOP,MINARET \?CCL8
	CALL2	TOUCHING?,DOCK-OBJECT
	ZERO?	STACK /?CCL8
	PRINT	CANT-FROM-HERE
	RTRUE	
?CCL8:	EQUAL?	PRSA,V?BOARD,V?TAKE \?CCL12
	EQUAL?	HERE,CANAL \?CCL12
	IN?	PROTAGONIST,RAFT \?CCL12
	PRINTI	"You lunge for the dock and secure a handhold. An agile clamber places you"
	ICALL1	AND-SIDEKICK
	PRINTI	" on the dock"
	PRINT	KEEP-IT-FROM-FLOATING-AWAY
	CRLF	
	SET	'RAFT-WAIT,FALSE-VALUE
	SET	'DONT-PRINT-VEHICLE,TRUE-VALUE
	CALL2	SET-DOCK-ROOM,RAFT-LOC-NUM >DOCK-ROOM
	ICALL2	GOTO,DOCK-ROOM
	SET	'DONT-PRINT-VEHICLE,FALSE-VALUE
	IN?	SIDEKICK,RAFT \?CND16
	MOVE	SIDEKICK,HERE
?CND16:	MOVE	RAFT,HERE
	RTRUE	
?CCL12:	EQUAL?	PRSA,V?BOARD \?CCL19
	EQUAL?	HERE,CANAL \?CCL22
	CALL2	DO-FIRST,STR?249
	RSTACK	
?CCL22:	IN?	PROTAGONIST,HERE \?CCL24
	PRINT	LOOK-AROUND
	RTRUE	
?CCL24:	LOC	PROTAGONIST
	ICALL	PERFORM,V?DISEMBARK,STACK
	RTRUE	
?CCL19:	EQUAL?	PRSA,V?TAKE-OFF \?CCL26
	EQUAL?	P-PRSA-WORD,W?GET \?CCL26
	ICALL	PERFORM,V?BOARD,CANAL-OBJECT
	RTRUE	
?CCL26:	EQUAL?	PRSA,V?PUT-ON,V?PUT \?CCL30
	EQUAL?	PRSI,DOCK-OBJECT \?CCL30
	EQUAL?	HERE,CANAL /?CCL30
	ICALL	PERFORM,V?PUT-ON,PRSO,GROUND
	RTRUE	
?CCL30:	EQUAL?	PRSA,V?LEAP-OFF \?CCL35
	EQUAL?	HERE,DUNETOP,CANAL \?CCL38
	PRINT	LOOK-AROUND
	RTRUE	
?CCL38:	ICALL	PERFORM,V?ENTER,CANAL-OBJECT
	RTRUE	
?CCL35:	EQUAL?	PRSA,V?SEARCH \?CCL40
	PRINT	NOTHING-NEW
	RTRUE	
?CCL40:	EQUAL?	PRSA,V?EXAMINE \FALSE
	EQUAL?	HERE,CANAL,MINARET,DUNETOP /FALSE
	CALL1	V-LOOK
	RSTACK	


	.FUNCT	DUNES-F
	EQUAL?	HERE,MINARET \?CCL3
	CALL2	TOUCHING?,DUNES
	ZERO?	STACK /?CCL3
	CALL2	CANT-REACH,DUNES
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?CLIMB-UP,V?CLIMB \?CCL7
	EQUAL?	HERE,DUNETOP \?CCL10
	PRINT	LOOK-AROUND
	RTRUE	
?CCL10:	EQUAL?	HERE,CANALVIEW-MALL,DONALD-DOCK \?CCL12
	CALL2	DO-WALK,P?UP
	RSTACK	
?CCL12:	PRINTR	"This dune is too steep."
?CCL7:	EQUAL?	PRSA,V?CLIMB-DOWN \FALSE
	EQUAL?	HERE,DUNETOP \FALSE
	CALL2	DO-WALK,P?DOWN
	RSTACK	


	.FUNCT	CANAL-F,RARG,NUM,DOCK-DIR
	EQUAL?	RARG,M-LOOK \FALSE
	CALL1	CANAL-LOC >NUM
	CALL2	SET-DOCK-DIR,NUM >DOCK-DIR
	PRINTI	"The "
	LOC	PROTAGONIST
	ICALL2	DPRINT,STACK
	PRINTI	" rocks gently in the current of a wide canal."
	EQUAL?	NUM,1,7,15 /?CTR5
	EQUAL?	NUM,-1,6 /?CTR5
	EQUAL?	NUM,10 \?CCL6
	IN?	PROTAGONIST,RAFT \?CCL6
?CTR5:	PRINTI	" A dock is "
	IN?	PROTAGONIST,RAFT \?CCL14
	PRINTI	"close enough to grab"
	JUMP	?CND12
?CCL14:	PRINTI	"visible"
?CND12:	PRINTI	" on the "
	PRINT	DOCK-DIR
	PRINTI	"ern shore."
	JUMP	?CND4
?CCL6:	EQUAL?	NUM,10 \?CCL16
	PRINTI	" There are docks on both banks."
	JUMP	?CND4
?CCL16:	PRINTI	" The banks of the canal are steep and sandy."
?CND4:	CALL1	BARGE-VISIBLE-AT-DOCK
	ZERO?	STACK /?CND17
	PRINTI	" A "
	PRINTD	BARGE
	PRINTI	" is moored to the dock"
	EQUAL?	NUM,10 \?CND19
	PRINTI	" on the "
	IN?	BARGE,ABANDONED-DOCK \?CCL23
	PRINTI	"we"
	JUMP	?CND21
?CCL23:	PRINTI	"ea"
?CND21:	PRINTI	"stern shore"
?CND19:	PRINTC	46
?CND17:	EQUAL?	NUM,5,12,29 \?CCL26
	PRINTI	" A smaller canal flows diagonally into this one, and the channel widens slightly to accommodate the heavier flow."
	JUMP	?CND24
?CCL26:	EQUAL?	NUM,9,10 \?CND24
	PRINTI	" Just "
	EQUAL?	NUM,9 \?CCL30
	PRINTI	"ahead"
	JUMP	?CND28
?CCL30:	PRINTI	"behind"
?CND28:	PRINTI	", the canal curves sharply to the "
	EQUAL?	NUM,9 \?CCL33
	PRINTI	"south."
	JUMP	?CND24
?CCL33:	PRINTI	"west."
?CND24:	EQUAL?	NUM,4,5,8 \?CND34
	PRINTI	" Sculpted reddish "
	PRINTD	DUNES
	PRINTI	" rise into view beyond the banks of the canal."
?CND34:	RANDOM	100
	LESS?	15,STACK /?CND36
	PRINTI	" The dark clouds of a sandstorm are visible on the horizon."
?CND36:	EQUAL?	NUM,15 \?CND38
	PRINTI	" A red warning buoy is anchored nearby. A sign atop the swaying buoy shows a skull and crossbones."
?CND38:	GRTR?	NUM,12 \TRUE
	LESS?	NUM,32 \TRUE
	EQUAL?	NUM,31 \?CCL46
	CRLF	
	PRINTI	"   "
	ICALL2	DESCRIBE-POWER-TRANSMITTER,31
	FSET?	POWER-TRANSMITTER,TOUCHBIT /TRUE
	FSET	POWER-TRANSMITTER,TOUCHBIT
	CRLF	
	PRINTI	"   As the "
	LOC	PROTAGONIST
	ICALL2	DPRINT,STACK
	PRINTI	" passes through the beam, you feel a tingling from every cell in "
	PRINTD	YOUR-BODY
	PRINTC	46
	RTRUE	
?CCL46:	PRINTC	32
	ICALL2	DESCRIBE-POWER-TRANSMITTER,NUM
	RTRUE	


	.FUNCT	BARGE-FROM-RAFT-F
	CALL1	BARGE-VISIBLE-AT-DOCK
	ZERO?	STACK \?CCL3
	CALL2	CANT-SEE,PRSO
	RSTACK	
?CCL3:	CALL2	TOUCHING?,PRSO
	ZERO?	STACK /FALSE
	CALL2	CANT-REACH,PRSO
	RSTACK	


	.FUNCT	BARGE-VISIBLE-AT-DOCK,NUM
	CALL1	CANAL-LOC >NUM
	EQUAL?	NUM,1 \?PRD5
	IN?	BARGE,ROYAL-DOCKS /TRUE
?PRD5:	EQUAL?	NUM,6 \?PRD8
	IN?	BARGE,BABY-DOCK /TRUE
?PRD8:	EQUAL?	NUM,7 \?PRD11
	IN?	BARGE,DONALD-DOCK /TRUE
?PRD11:	EQUAL?	NUM,10 \?PRD14
	LOC	BARGE
	EQUAL?	STACK,MY-KIND-OF-DOCK,ABANDONED-DOCK /TRUE
?PRD14:	EQUAL?	NUM,15 \FALSE
	IN?	BARGE,WATTZ-UPP-DOCK /TRUE
	RFALSE	


	.FUNCT	BUOY-F,NUM
	CALL1	CANAL-LOC >NUM
	EQUAL?	NUM,15 /?CCL3
	EQUAL?	HERE,WATTZ-UPP-DOCK /?CCL3
	CALL2	CANT-SEE,BUOY
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?EXAMINE,V?READ \?CCL7
	ICALL	PERFORM,V?READ,SIGN
	RTRUE	
?CCL7:	EQUAL?	PRSA,V?OPEN,V?TAKE \?CCL9
	PRINT	YOU-CANT
	EQUAL?	PRSA,V?TAKE \?CCL12
	PRINTI	"take"
	JUMP	?CND10
?CCL12:	PRINTI	"open"
?CND10:	PRINTR	" a buoy! Where'd you get such a silly idea?"
?CCL9:	CALL2	TOUCHING?,BUOY
	ZERO?	STACK /FALSE
	CALL2	CANT-REACH,BUOY
	RSTACK	


	.FUNCT	I-CANAL,NUM,MOVED
	IN?	BARGE,CANAL /?CND1
	IN?	RAFT,CANAL /?CND1
	ICALL2	DEQUEUE,I-CANAL
	RFALSE	
?CND1:	IN?	BARGE,CANAL \?CND5
	ZERO?	BARGE-UNDER-POWER \?CTR8
	ZERO?	BARGE-WAIT /?CCL9
?CTR8:	IN?	PROTAGONIST,BARGE \?CND12
	SET	'MOVED,TRUE-VALUE
?CND12:	SET	'BARGE-WAIT,FALSE-VALUE
	ZERO?	RAFT-HELD /?CND14
	IN?	RAFT,CANAL \?CND14
	IN?	PROTAGONIST,BARGE \?CND14
	INC	'RAFT-LOC-NUM
?CND14:	INC	'BARGE-LOC-NUM
	JUMP	?CND5
?CCL9:	SET	'BARGE-WAIT,TRUE-VALUE
?CND5:	IN?	RAFT,CANAL \?CND19
	ZERO?	RAFT-HELD \?CND19
	ZERO?	RAFT-WAIT /?CCL25
	IN?	PROTAGONIST,RAFT \?CND26
	SET	'MOVED,TRUE-VALUE
?CND26:	SET	'RAFT-WAIT,FALSE-VALUE
	INC	'RAFT-LOC-NUM
	JUMP	?CND19
?CCL25:	SET	'RAFT-WAIT,TRUE-VALUE
?CND19:	CALL1	CANAL-LOC >NUM
	EQUAL?	NUM,31 \?CND28
	CALL2	QUEUED?,I-ION-DEATH
	ZERO?	STACK \?CND28
	LOC	PROTAGONIST
	IN?	SIDEKICK,STACK \?CND32
	SET	'SIDEKICK-IONIZED,TRUE-VALUE
?CND32:	ICALL	QUEUE,I-ION-DEATH,6
?CND28:	LESS?	NUM,17 \?CCL36
	PUTP	POWER-TRANSMITTER,P?SDESC,STR?250
	JUMP	?CND34
?CCL36:	GRTR?	NUM,30 \?CCL38
	PUTP	POWER-TRANSMITTER,P?SDESC,STR?251
	JUMP	?CND34
?CCL38:	PUTP	POWER-TRANSMITTER,P?SDESC,STR?252
?CND34:	EQUAL?	HERE,CANAL /?CCL41
	GRTR?	BARGE-LOC-NUM,36 \?CND42
	MOVE	BARGE,ICY-DOCK
	ZERO?	RAFT-HELD /?CND42
	MOVE	RAFT,ICY-DOCK
?CND42:	GRTR?	RAFT-LOC-NUM,36 \?CND46
	MOVE	RAFT,ICY-DOCK
?CND46:	ICALL1	BARGE-DOCKS
	RFALSE	
?CCL41:	ZERO?	MOVED /FALSE
	PRINTI	"   The "
	LOC	PROTAGONIST
	ICALL2	DPRINT,STACK
	PRINTC	32
	EQUAL?	NUM,10 \?CCL51
	ZERO?	BARGE-UNDER-POWER /?CCL54
	IN?	PROTAGONIST,BARGE \?CCL54
	SET	'NEARER-DOCK,MY-KIND-OF-DOCK
	PRINTI	"chugs quickly"
	JUMP	?CND52
?CCL54:	SET	'NEARER-DOCK,ABANDONED-DOCK
	PRINTI	"drifts slowly"
?CND52:	PRINTI	" around the bend, ending up near the "
	ZERO?	BARGE-UNDER-POWER /?CCL59
	IN?	PROTAGONIST,BARGE \?CCL59
	PRINTI	"ea"
	JUMP	?CND57
?CCL59:	PRINTI	"we"
?CND57:	PRINTI	"stern bank of"
	JUMP	?CND49
?CCL51:	ZERO?	BARGE-UNDER-POWER /?CCL64
	IN?	PROTAGONIST,BARGE \?CCL64
	PRINTI	"barges"
	JUMP	?CND62
?CCL64:	PRINTI	"drifts"
?CND62:	PRINTI	" further down"
?CND49:	PRINTI	" the canal."
	EQUAL?	NUM,36 \?CND67
	PRINTI	" A wide dock spans the canal to the south. The "
	LOC	PROTAGONIST
	ICALL2	DPRINT,STACK
	PRINTI	" butts up against it"
	PRINT	PINNED
	CRLF	
	IN?	PROTAGONIST,RAFT \?CCL71
	IN?	BARGE,CANAL \?CCL71
	EQUAL?	BARGE-LOC-NUM,36 \?CCL71
	MOVE	BARGE,ICY-DOCK
	JUMP	?CND69
?CCL71:	IN?	PROTAGONIST,BARGE \?CND69
	IN?	RAFT,CANAL \?CND69
	EQUAL?	RAFT-LOC-NUM,36 \?CND69
	MOVE	BARGE,ICY-DOCK
?CND69:	LOC	PROTAGONIST
	MOVE	STACK,ICY-DOCK
	LOC	PROTAGONIST
	ICALL2	GOTO,STACK
	RTRUE	
?CND67:	EQUAL?	HAND-COVER,EYES /?CTR80
	FSET?	EYES,MUNGBIT \?CCL81
?CTR80:	PRINTC	32
	PRINT	YOU-CANT
	PRINTI	"see a thing, of course."
	CRLF	
	JUMP	?CND79
?CCL81:	CRLF	
	CRLF	
	ICALL1	DESCRIBE-ROOM
?CND79:	EQUAL?	BARGE-LOC-NUM,RAFT-LOC-NUM \?CND84
	IN?	RAFT,CANAL \?CND84
	IN?	BARGE,CANAL \?CND84
	IN?	PROTAGONIST,RAFT \?CCL91
	ICALL2	BARGE-F,M-OBJDESC
	CRLF	
	JUMP	?CND84
?CCL91:	ICALL2	RAFT-F,M-OBJDESC
	CRLF	
?CND84:	ICALL2	BARGE-DOCKS,TRUE-VALUE
	RTRUE	


	.FUNCT	POWER-TRANSMITTER-F,NUM
	CALL1	CANAL-LOC >NUM
	GRTR?	NUM,31 /?CTR2
	LESS?	NUM,13 \?CCL3
?CTR2:	CALL2	CANT-SEE,POWER-TRANSMITTER
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?EXAMINE \?CCL7
	ICALL2	DESCRIBE-POWER-TRANSMITTER,NUM
	CRLF	
	RTRUE	
?CCL7:	CALL2	TOUCHING?,POWER-TRANSMITTER
	ZERO?	STACK /FALSE
	CALL2	CANT-REACH,POWER-TRANSMITTER
	RSTACK	


	.FUNCT	DESCRIBE-POWER-TRANSMITTER,NUM
	EQUAL?	NUM,31 \?CCL3
	PRINTI	"The "
	LOC	PROTAGONIST
	ICALL2	DPRINT,STACK
	PRINTI	" is now passing the metal structure that has been looming closer for the last hour. Its size and power are overwhelming; a relic of Martian technology at its height. Vacuum tubes the size of telephone booths produce power that was once beamed all over Mars. But now, in the twilight of the planet's civilization, the machine's base has rusted away. The massive tower now shoots its ion power beam uselessly across the canal, into the sand of the opposite bank."
	RTRUE	
?CCL3:	LESS?	NUM,17 \?CCL5
	PRINTI	"You spy a metallic glint, far ahead."
	RTRUE	
?CCL5:	GRTR?	NUM,27 \?CCL7
	PRINTI	"A massive machine, unlike anything you've ever seen, rises from the shore, looming closer with each passing minute."
	RTRUE	
?CCL7:	PRINTI	"A metal structure, glinting in the weak Martian sunlight, is visible at the edge of the canal"
	LESS?	NUM,21 \?CCL10
	PRINTI	", but far, far ahead."
	RTRUE	
?CCL10:	LESS?	NUM,24 \?CCL12
	PRINTI	" far ahead of you."
	RTRUE	
?CCL12:	PRINTI	", a bit too far to make out any details."
	RTRUE	


	.FUNCT	I-ION-DEATH
	INC	'ION-DEATH-COUNTER
	PRINTI	"   "
	GRTR?	ION-DEATH-COUNTER,4 \?CCL3
	CALL2	JIGS-UP,STR?257
	RSTACK	
?CCL3:	FSET?	POWER-TRANSMITTER,MUNGBIT \?CCL6
	ICALL	QUEUE,I-ION-DEATH,2
	JUMP	?CND4
?CCL6:	ICALL	QUEUE,I-ION-DEATH,6
?CND4:	ICALL1	V-DIAGNOSE
	ZERO?	SIDEKICK-IONIZED /TRUE
	CALL2	VISIBLE?,SIDEKICK
	ZERO?	STACK /TRUE
	EQUAL?	ION-DEATH-COUNTER,3 \TRUE
	PRINTI	"   "
	ICALL1	DPRINT-SIDEKICK
	PRINTR	" says, ""My head is pounding! I wish we had some aspirin."""


	.FUNCT	BARGE-DOCKS,CALLED-BY-INT,DOCK-ROOM,DOCK-DIR
	ZERO?	MOORING-ON /FALSE
	IN?	BARGE,CANAL \FALSE
	EQUAL?	BARGE-LOC-NUM,7,10,15 /?CTR2
	EQUAL?	BARGE-LOC-NUM,1,6 \FALSE
?CTR2:	ZERO?	CALLED-BY-INT /?CND9
	PRINTI	"  "
?CND9:	CALL2	SET-DOCK-ROOM,BARGE-LOC-NUM >DOCK-ROOM
	CALL2	SET-DOCK-DIR,BARGE-LOC-NUM >DOCK-DIR
	IN?	BARGE,HERE \?CND11
	PRINTI	" The barge drifts toward the dock on the "
	PRINT	DOCK-DIR
	PRINTI	"ern shore, butting against it with a loud ""clank."""
	IN?	PROTAGONIST,BARGE \?CND13
	CRLF	
?CND13:	CRLF	
?CND11:	MOVE	BARGE,DOCK-ROOM
	IN?	PROTAGONIST,BARGE \?CND15
	ZERO?	RAFT-HELD /?CND17
	MOVE	RAFT,DOCK-ROOM
?CND17:	ICALL2	GOTO,BARGE
?CND15:	SET	'BARGE-WAIT,FALSE-VALUE
	RTRUE	


	.FUNCT	SET-DOCK-ROOM,NUM
	EQUAL?	NUM,-1 \?CCL3
	RETURN	HICKORY-AND-DICKORY-DOCK
?CCL3:	EQUAL?	NUM,1 \?CCL5
	RETURN	ROYAL-DOCKS
?CCL5:	EQUAL?	NUM,6 \?CCL7
	RETURN	BABY-DOCK
?CCL7:	EQUAL?	NUM,7 \?CCL9
	RETURN	DONALD-DOCK
?CCL9:	EQUAL?	NUM,15 \?CCL11
	RETURN	WATTZ-UPP-DOCK
?CCL11:	EQUAL?	NEARER-DOCK,MY-KIND-OF-DOCK /?CTR12
	RETURN	ABANDONED-DOCK
?CTR12:	RETURN	MY-KIND-OF-DOCK


	.FUNCT	SET-DOCK-DIR,NUM
	EQUAL?	NUM,-1,1,7 \?CCL3
	RETURN	STR?258
?CCL3:	EQUAL?	NUM,6 \?CCL5
	RETURN	STR?259
?CCL5:	EQUAL?	NUM,15 \?CCL7
	RETURN	STR?260
?CCL7:	EQUAL?	NEARER-DOCK,MY-KIND-OF-DOCK /?CTR8
	RETURN	STR?260
?CTR8:	RETURN	STR?241


	.FUNCT	AMONG-THE-DUNES-F,RARG
	EQUAL?	RARG,M-ENTER \FALSE
	FSET?	AMONG-THE-DUNES,TOUCHBIT /FALSE
?PRG6:	RANDOM	8270
	ADD	100,STACK >WIFE-NUMBER
	MOD	WIFE-NUMBER,10
	ZERO?	STACK /?PRG6
	CALL2	PALINDROME-NUMBER?,WIFE-NUMBER
	ZERO?	STACK \?PRG6
	RTRUE	


	.FUNCT	PALINDROME-NUMBER?,NUM,?TMP1
	GRTR?	NUM,999 \?CCL3
	DIV	NUM,1000 >?TMP1
	MOD	NUM,10
	EQUAL?	?TMP1,STACK /TRUE
	RFALSE	
?CCL3:	DIV	NUM,100 >?TMP1
	MOD	NUM,10
	EQUAL?	?TMP1,STACK /TRUE
	RFALSE	


	.FUNCT	LIP-BALM-F
	FSET?	LIP-BALM,UNTEEDBIT /FALSE
	EQUAL?	PRSA,V?PUT-ON \?PRD7
	EQUAL?	PRSI,MOUTH /?CTR4
?PRD7:	EQUAL?	PRSA,V?WEAR \?CCL5
?CTR4:	FSET?	LIP-BALM,WORNBIT \?CCL12
	PRINT	SENILITY-STRIKES
	RTRUE	
?CCL12:	MOVE	LIP-BALM,PROTAGONIST
	FSET	LIP-BALM,WORNBIT
	FSET	MOUTH,MUNGBIT
	PRINTR	"You coat your lips with the glistening balm, using up the whole stick."
?CCL5:	EQUAL?	PRSA,V?EXAMINE \?CCL14
	FSET?	LIP-BALM,WORNBIT \?CCL14
	ICALL2	PERFORM-PRSA,MOUTH
	RTRUE	
?CCL14:	EQUAL?	PRSA,V?CLEAN,V?REMOVE \FALSE
	FSET?	LIP-BALM,WORNBIT \FALSE
	MOVE	LIP-BALM,LOCAL-GLOBALS
	FCLEAR	MOUTH,MUNGBIT
	PRINTR	"You wipe away the lip balm."


	.FUNCT	CODED-MESSAGE-F
	EQUAL?	PRSA,V?EXAMINE,V?READ \FALSE
	PRINTI	"VSDFHHQN UXRB VVLN RW "
	ZERO?	MALE /?CCL6
	PRINTI	"UH"
	JUMP	?CND4
?CCL6:	PRINTI	"PL"
?CND4:	PRINTI	"K JQLNVD BE "
	ZERO?	MALE /?CCL9
	PRINTI	"UH"
	JUMP	?CND7
?CCL9:	PRINTI	"PL"
?CND7:	PRINTI	"K RW IOHVUXRB BILWQHGL -- SDP WHUFHV HKW WHJ GQD "
	ZERO?	MALE \?CND10
	PRINTI	"VVH"
?CND10:	PRINTI	"QDWOXV HKW IR "
	ICALL2	REVERSE-NUMBER,WIFE-NUMBER
	PRINTI	" UHEPXQ "
	ZERO?	MALE /?CCL14
	PRINTI	"HILZ"
	JUMP	?CND12
?CCL14:	PRINTI	"GQDEVXK"
?CND12:	PRINTR	" WFDWQRF RW VL QRLVVLP UXRB"


	.FUNCT	REVERSE-NUMBER,NUM
?PRG1:	MOD	NUM,10
	PRINTN	STACK
	DIV	NUM,10 >NUM
	ZERO?	NUM \?PRG1
	RTRUE	


	.FUNCT	MESSENGER-F
	EQUAL?	PRSA,V?EXAMINE \?CCL3
	PRINTR	"It's dead. Very dead."
?CCL3:	EQUAL?	PRSA,V?KISS,V?FUCK \?CCL5
	PRINTR	"Is there even a word for this sort of perverse behavior? Necro-xeno-philia? Xeno-necro-philia? Grosso-sicko-philia?"
?CCL5:	EQUAL?	PRSA,V?PUT-ON \?CCL7
	EQUAL?	PRSO,LIP-BALM \?CCL7
	PRINTR	"Too late."
?CCL7:	EQUAL?	PRSA,V?SEARCH \?CCL11
	PRINT	NOTHING-NEW
	RTRUE	
?CCL11:	EQUAL?	PRSA,V?ALARM \FALSE
	PRINTR	"This guy's not resting, he's deceased!"


	.FUNCT	DUNETOP-F,RARG
	EQUAL?	RARG,M-ENTER \FALSE
	ZERO?	TITS-COUNTER \FALSE
	CALL	QUEUE,I-TITS,-1
	RSTACK	


	.FUNCT	I-TITS
	INC	'TITS-COUNTER
	EQUAL?	NAUGHTY-LEVEL,2 /?CCL3
	ICALL2	DEQUEUE,I-TITS
	RFALSE	
?CCL3:	EQUAL?	TITS-COUNTER,4 \?CCL5
	PRINTR	"   [A warning for any Jerry Falwell groupies who are miraculously still playing: we'll be using the word ""tits"" in five turns or so. Please consult the manual for the proper way to stop playing.]"
?CCL5:	EQUAL?	TITS-COUNTER,7 \?CCL7
	PRINTR	"   [Only a few turns until the ""tits"" reference! Use QUIT now if you might be offended!]"
?CCL7:	EQUAL?	TITS-COUNTER,9 \?CCL9
	PRINTR	"   [Last warning! The word ""tits"" will appear in the very next turn! This is your absolutely last chance to avoid seeing ""tits"" used!!!]"
?CCL9:	EQUAL?	TITS-COUNTER,10 \FALSE
	ICALL2	DEQUEUE,I-TITS
	PRINTI	"   A hyperdimensional traveller suddenly appears out of thin air. ""My sister has tremendous breasts,"" says the traveller and, without further explanation, vanishes"
	FSET?	NOSE,MUNGBIT /?CND12
	PRINTI	", leaving only a vague trace of interdimensional ozone"
?CND12:	PRINTR	".
   [Oh, regarding the use of ""tits,"" we changed our mind at the last minute. Everyone agreed it was too risque.]"


	.FUNCT	OUTSIDE-SHOP-F
	EQUAL?	PRSA,V?BOARD,V?WALK-TO,V?ENTER \?CCL3
	CALL2	DO-WALK,P?SOUTH
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?DISEMBARK,V?LEAVE,V?EXIT \FALSE
	PRINT	LOOK-AROUND
	RTRUE	


	.FUNCT	INSIDE-SHOP-F
	EQUAL?	PRSA,V?EXIT,V?LEAVE,V?DISEMBARK \?CCL3
	CALL2	DO-WALK,P?NORTH
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?ENTER,V?WALK-TO,V?BOARD \?CCL5
	PRINT	LOOK-AROUND
	RTRUE	
?CCL5:	EQUAL?	PRSA,V?SEARCH \?CCL7
	ICALL2	PERFORM-PRSA,DUST
	RTRUE	
?CCL7:	EQUAL?	PRSA,V?EXAMINE \FALSE
	CALL1	V-LOOK
	RSTACK	


	.FUNCT	EXIT-SHOP-F,RARG
	EQUAL?	RARG,M-END \FALSE
	FSET?	PROPRIETOR,TOUCHBIT /FALSE
	FSET	PROPRIETOR,TOUCHBIT
	PRINTI	"   "
	PRINT	PROPRIETOR-STIRS
	PRINTR	"Don't get many customers these days, since they abandoned the dock. In fact, you're only the third in the last hundred and fifty centuries."" He slips back into a drowse."


	.FUNCT	PROPRIETOR-F
	EQUAL?	PROPRIETOR,WINNER \?CCL3
	EQUAL?	PRSA,V?WHAT \?PRD8
	EQUAL?	PRSO,LGOP /?CTR5
?PRD8:	EQUAL?	PRSA,V?TELL-ABOUT \?CCL6
	EQUAL?	PRSO,ME \?CCL6
	EQUAL?	PRSI,LGOP \?CCL6
?CTR5:	PRINTR	"""A bunch of deadbeats! Never pay their bills -- I've had to repossess God knows how many exits!"""
?CCL6:	SET	'WINNER,PROTAGONIST
	ICALL	PERFORM,V?ALARM,PROPRIETOR
	CALL1	STOP
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?ALARM \?CCL15
	PRINT	PROPRIETOR-STIRS
	PRINTC	69
	PRINT	BOUGHT-AND-SOLD
	PRINTI	","" he mumbles, ""e"
	PRINT	BOUGHT-AND-SOLD
	PRINTR	"."" A moment later, he nods off."
?CCL15:	EQUAL?	PRSA,V?BARTER-WITH /?CTR16
	EQUAL?	PRSA,V?ASK-FOR \?CCL17
	EQUAL?	PRSI,EXIT-OBJECT \?CCL17
?CTR16:	ICALL	PERFORM,V?BUY,EXIT-OBJECT
	RTRUE	
?CCL17:	EQUAL?	PRSA,V?SHOW,V?GIVE \?CCL23
	EQUAL?	PRSO,TEN-MARSMID-COIN \?CCL23
	PRINTR	"""Humph? Eh, oh, sorry, no change for a ten. And the Mall Merchants Association would have my license if I accepted an overpayment. Try again in a year ... or two ... grunt snore."""
?CCL23:	EQUAL?	PRSA,V?SHOW,V?GIVE \?CCL27
	EQUAL?	PRSO,ONE-MARSMID-COIN \?CCL27
	REMOVE	ONE-MARSMID-COIN
	MOVE	TUBE,DUST
	ICALL	INCREMENT-SCORE,5,12
	PRINTR	"The proprietor slowly focuses one eye on the coin. ""Not much in stock these days,"" he explains. ""My supplier went bankrupt ninety thousand years ago."" He takes the coin and starts to hand you a cardboard tube, but his eye drifts out of focus again, and he drops it wearily into the dust."
?CCL27:	EQUAL?	PRSA,V?SHOW,V?GIVE \FALSE
	EQUAL?	PRSO,FLEXIBLE-HOLE \FALSE
	PRINT	PROPRIETOR-STIRS
	PRINTR	"Don't think I could sell such an out-of-date model. No one wants exits anymore, anyway. Don't know why I bother ... to stay in business ... zzzz."""


	.FUNCT	EXIT-OBJECT-F
	EQUAL?	PRSA,V?BUY \?CCL3
	EQUAL?	HERE,EXIT-SHOP \?CCL6
	PRINTR	"""One marsmid, please, grunt snore zzz."""
?CCL6:	FSET?	EXIT-SHOP,TOUCHBIT \?CCL8
	PRINTI	"This isn't an "
	PRINTD	EXIT-SHOP
	PRINTR	"!"
?CCL8:	PRINTR	"Buy an exit?!?!"
?CCL3:	EQUAL?	PRSA,V?BUY-WITH \?CCL10
	EQUAL?	PRSI,TEN-MARSMID-COIN,ONE-MARSMID-COIN \?CCL10
	ICALL	PERFORM,V?GIVE,PRSI,PROPRIETOR
	RTRUE	
?CCL10:	EQUAL?	PRSA,V?TAKE \FALSE
	IN?	TUBE,DUST \FALSE
	EQUAL?	HERE,EXIT-SHOP \FALSE
	PRINTR	"It's lost in the dust."


	.FUNCT	DUST-F,X
	EQUAL?	PRSA,V?DIG,V?REACH-IN,V?SEARCH /?CTR2
	EQUAL?	PRSA,V?RAKE,V?LOOK-INSIDE \?CCL3
?CTR2:	FIRST?	DUST >X \?CCL8
	MOVE	X,PROTAGONIST
	ICALL2	THIS-IS-IT,X
	PRINTI	"You grasp"
	ICALL2	APRINT,X
	PRINTR	"!"
?CCL8:	PRINTR	"You sift through the dust but find nothing."
?CCL3:	EQUAL?	PRSA,V?BOARD,V?ENTER \?CCL10
	PRINTR	"You're already up to your neck in dust."
?CCL10:	EQUAL?	PRSA,V?PUT \?CCL12
	EQUAL?	PRSI,DUST \?CCL12
	ICALL	PERFORM,V?DROP,PRSO
	RTRUE	
?CCL12:	EQUAL?	PRSA,V?BLOW,V?MOVE,V?CLEAN \FALSE
	PRINTR	"You'd need a plow to move this dust."


	.FUNCT	FLEXIBLE-HOLE-F,SIDEKICK-VISIBLE
	EQUAL?	PRSA,V?EXAMINE \?CCL3
	PRINTI	"The "
	PRINTD	FLEXIBLE-HOLE
	PRINTR	" looks just like a portable version of the ""holes"" you've been encountering all over the solar system."
?CCL3:	EQUAL?	PRSA,V?MEASURE \?CCL5
	PRINTI	"The "
	ICALL2	DPRINT,HOLE
	PRINTR	" is two feet across."
?CCL5:	EQUAL?	PRSA,V?LOOK-INSIDE,V?TOUCH,V?REACH-IN \?CCL7
	IN?	FLEXIBLE-HOLE,TUBE \?CCL7
	CALL1	MEANT-OTHER-HOLE
	ZERO?	STACK \TRUE
	CALL2	NOT-ON-GROUND,FLEXIBLE-HOLE
	RSTACK	
?CCL7:	EQUAL?	PRSA,V?TOUCH,V?REACH-IN \?CCL13
	PRINT	HAND-DWINDLES
	RTRUE	
?CCL13:	EQUAL?	PRSA,V?LOOK-INSIDE \?CCL15
	PRINT	STARING-INTO-VOID
	RTRUE	
?CCL15:	EQUAL?	PRSA,V?PUT-ON,V?PUT \?CCL17
	EQUAL?	PRSI,FLEXIBLE-HOLE \?CCL17
	LOC	FLEXIBLE-HOLE
	EQUAL?	STACK,HERE,RAFT,BARGE \?CCL22
	MOVE	PRSO,BOUDOIR
	CALL1	NON-DIMENSIONAL-JOURNEY
	RSTACK	
?CCL22:	CALL1	MEANT-OTHER-HOLE
	ZERO?	STACK \TRUE
	CALL2	NOT-ON-GROUND,FLEXIBLE-HOLE
	RSTACK	
?CCL17:	EQUAL?	PRSA,V?BOARD,V?ENTER,V?STAND-ON \FALSE
	CALL2	ULTIMATELY-IN?,FLEXIBLE-HOLE
	ZERO?	STACK /?CCL29
	CALL1	MEANT-OTHER-HOLE
	ZERO?	STACK \TRUE
	PRINT	HOLDING-IT
	RTRUE	
?CCL29:	IN?	PROTAGONIST,HERE /?CCL33
	LOC	PROTAGONIST
	IN?	FLEXIBLE-HOLE,STACK /?CCL33
	CALL1	NOT-GOING-ANYWHERE
	RSTACK	
?CCL33:	LOC	FLEXIBLE-HOLE
	EQUAL?	STACK,HERE,TREE-HOLE /?CCL37
	LOC	FLEXIBLE-HOLE
	EQUAL?	STACK,RAFT,BARGE /?CCL37
	CALL1	MEANT-OTHER-HOLE
	ZERO?	STACK \TRUE
	CALL2	NOT-ON-GROUND,FLEXIBLE-HOLE
	RSTACK	
?CCL37:	ZERO?	SIDEKICK-TRIP-FLAG /?CCL43
	CALL2	QUEUED?,I-SIDEKICK-OUT-WINDOW
	ZERO?	STACK /?CCL43
	CALL2	DO-WALK,P?DOWN
	RSTACK	
?CCL43:	CALL2	VISIBLE?,SIDEKICK
	ZERO?	STACK /?CND46
	SET	'SIDEKICK-VISIBLE,TRUE-VALUE
?CND46:	ICALL1	FALL-THROUGH-HOLE
	ICALL2	GOTO,BOUDOIR
	CALL2	QUEUED?,I-ION-DEATH
	ZERO?	STACK /?CND48
	FSET	POWER-TRANSMITTER,MUNGBIT
	ICALL	QUEUE,I-ION-DEATH,1
?CND48:	ZERO?	SIDEKICK-VISIBLE /TRUE
	SET	'HOLE-MOVE,TRUE-VALUE
	ICALL1	SIDEKICK-FOLLOWS-YOU
	RTRUE	


	.FUNCT	MEANT-OTHER-HOLE
	EQUAL?	PRSO,FLEXIBLE-HOLE \?PRD5
	GET	P-ADJW,0
	EQUAL?	STACK,W?FLEXIBLE,W?PORTABLE /FALSE
?PRD5:	EQUAL?	PRSI,FLEXIBLE-HOLE \?CCL3
	GET	P-ADJW,1
	EQUAL?	STACK,W?FLEXIBLE,W?PORTABLE /FALSE
?CCL3:	CALL	GLOBAL-IN?,HOLE,HERE
	ZERO?	STACK /FALSE
	EQUAL?	PRSO,FLEXIBLE-HOLE \?CCL13
	ICALL	PERFORM-PRSA,HOLE,PRSI
	RTRUE	
?CCL13:	ICALL	PERFORM-PRSA,PRSO,HOLE
	RTRUE	


	.FUNCT	LAUNDRY-ROOM-F,RARG
	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"One of the less pleasant aspects of running a palace is the sheer volume of dirty laundry its occupants produce. Why, the 8379 "
	ZERO?	MALE /?CCL6
	PRINTI	"wive"
	JUMP	?CND4
?CCL6:	PRINTI	"husband"
?CND4:	PRINTI	"s alone could keep a crew of cleaners sleepless. Add in the servants, cooks, gardeners, stablehands, jesters, visiting nobles, brothers-in-law in virtual permanent residence... Suffice it to say that there's "
	ZERO?	NAUGHTY-LEVEL \?CCL9
	PRINTI	"quite"
	JUMP	?CND7
?CCL9:	PRINTI	"one hell of"
?CND7:	PRINTI	" a lot of dirty laundry here. You can barely see the exit to the north through it all."
	RTRUE	


	.FUNCT	CLOTHES-PIN-F
	FSET?	CLOTHES-PIN,UNTEEDBIT /FALSE
	EQUAL?	PRSA,V?PIN,V?PUT-ON \?CCL5
	EQUAL?	PRSO,CLOTHES-PIN \?CCL5
	EQUAL?	PRSI,NOSE /?CCL10
	CALL1	WASTES
	RSTACK	
?CCL10:	ZERO?	GONE-APE /?CCL12
	PRINT	DEXTERITY
	RTRUE	
?CCL12:	FSET?	CLOTHES-PIN,WORNBIT \?CCL14
	PRINT	SENILITY-STRIKES
	RTRUE	
?CCL14:	MOVE	CLOTHES-PIN,PROTAGONIST
	FSET	CLOTHES-PIN,WORNBIT
	FSET	NOSE,MUNGBIT
	PRINTR	"You pin your proboscis."
?CCL5:	EQUAL?	PRSA,V?PUT \?CCL16
	EQUAL?	PRSO,NOSE \?CCL16
	ICALL	PERFORM,V?PUT-ON,CLOTHES-PIN,NOSE
	RTRUE	
?CCL16:	EQUAL?	PRSA,V?TIE \?CCL20
	EQUAL?	P-PRSA-WORD,W?ATTACH \?CCL20
	EQUAL?	PRSO,CLOTHES-PIN \?CCL20
	ZERO?	PRSI /?CCL20
	ICALL	PERFORM,V?PUT-ON,CLOTHES-PIN,PRSI
	RTRUE	
?CCL20:	EQUAL?	PRSA,V?TAKE-WITH \?CCL26
	EQUAL?	P-PRSA-WORD,W?HOLD \?CCL26
	EQUAL?	PRSO,NOSE \?CCL26
	ICALL	PERFORM,V?PUT-ON,CLOTHES-PIN,NOSE
	RTRUE	
?CCL26:	EQUAL?	PRSA,V?TAKE-OFF,V?REMOVE \FALSE
	FSET?	CLOTHES-PIN,WORNBIT \FALSE
	ZERO?	GONE-APE /?CND34
	ICALL	PERFORM,V?TAKE,CLOTHES-PIN
	RTRUE	
?CND34:	ICALL1	OPEN-EYES-AND-REMOVE-HANDS
	FCLEAR	CLOTHES-PIN,WORNBIT
	CALL2	SENSE-AGAIN,NOSE
	RSTACK	


	.FUNCT	WELL-ENTER-F
	PRINTI	"You climb down the well for a long distance. Near the bottom the handholds end, so you"
	ICALL2	AND-SIDEKICK,WELL-BOTTOM
	PRINTI	" leap the rest of the way, landing on"
	ICALL2	APRINT,HOLE
	PRINTI	". "
	SET	'HERE,WELL-BOTTOM
	MOVE	PROTAGONIST,WELL-BOTTOM
	SET	'OHERE,FALSE-VALUE
	ICALL	PERFORM,V?STAND-ON,HOLE
	RFALSE	


	.FUNCT	WELL-F
	EQUAL?	PRSA,V?REACH-IN,V?LOOK-INSIDE \?CCL3
	PRINTR	"Handholds lead downward!"
?CCL3:	EQUAL?	PRSA,V?CLIMB-UP,V?CLIMB,V?CLIMB-DOWN /?CTR4
	EQUAL?	PRSA,V?ENTER,V?BOARD \?CCL5
?CTR4:	EQUAL?	HERE,WELL-BOTTOM \?CCL10
	ICALL2	DO-WALK,P?UP
	RTRUE	
?CCL10:	ICALL1	WELL-ENTER-F
	RTRUE	
?CCL5:	EQUAL?	PRSA,V?PUT \FALSE
	EQUAL?	PRSI,WELL-OBJECT \FALSE
	EQUAL?	HERE,ORIENTAL-GARDEN \FALSE
	MOVE	PRSO,BARGE
	EQUAL?	PRSO,TORCH \?CND16
	ICALL1	TORCH-OFF
?CND16:	PRINTR	"It drops out of sight."


	.FUNCT	TOWER-F
	EQUAL?	PRSA,V?BOARD,V?WALK-TO,V?ENTER /?CTR2
	EQUAL?	PRSA,V?CLIMB-UP,V?CLIMB \?CCL3
?CTR2:	EQUAL?	HERE,BASE-OF-TOWER \?CCL8
	CALL2	DO-WALK,P?UP
	RSTACK	
?CCL8:	EQUAL?	HERE,MINARET \FALSE
	PRINT	LOOK-AROUND
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?EXIT,V?LEAVE,V?DISEMBARK \FALSE
	EQUAL?	HERE,BASE-OF-TOWER \?CCL15
	PRINT	LOOK-AROUND
	RTRUE	
?CCL15:	CALL2	DO-WALK,P?DOWN
	RSTACK	


	.FUNCT	AUDIENCE-CHAMBER-F,RARG
	EQUAL?	RARG,M-LOOK \?CCL3
	PRINTI	"The good news is that this hall is intoxicatingly beautiful, laid with the snow-white fur of the rare Martian Velvetworm and endowed with platinum arches and balustrades. Silky curtains embrace openings to the south, southwest, and west.
   The bad news is that no "
	ZERO?	MALE \?CND4
	PRINTI	"wo"
?CND4:	PRINTI	"man has ever entered the "
	ICALL2	DPRINT,HERE
	PRINTI	" of"
	ICALL2	TPRINT,SULTAN
	PRINTI	" and departed alive."
	RTRUE	
?CCL3:	EQUAL?	RARG,M-END \FALSE
	FSET?	SULTAN,TOUCHBIT /FALSE
	FSET	SULTAN,TOUCHBIT
	CALL	QUEUE,I-SULTAN,-1
	RSTACK	


	.FUNCT	AUDIENCE-CHAMBER-EXIT-F
	ZERO?	RIDDLE-ANSWERED \?CCL3
	PRINTI	"""Rule violation! Rule violation!"" "
	CALL1	RIDDLE-DEATH
	RSTACK	
?CCL3:	EQUAL?	PRSO,P?SOUTH \?CCL5
	RETURN	ORIENTAL-GARDEN
?CCL5:	EQUAL?	PRSO,P?SW \?CCL7
	RETURN	MAIN-HALL-OF-PALACE
?CCL7:	GRTR?	CHOICE-NUMBER,0 /?CTR8
	EQUAL?	HAREM-GUARD-COUNTER,5 \?CCL9
?CTR8:	RETURN	HAREM
?CCL9:	CALL2	RUNNING?,I-HAREM-GUARD
	ZERO?	STACK /?CCL13
	ICALL	QUEUE,I-HAREM-GUARD,2
	PRINTI	"""Hey!"" The "
	PRINTD	HAREM-GUARD
	PRINTI	" pushes you back. ""Pick a number first!"
	CRLF	
	RFALSE	
?CCL13:	ICALL	QUEUE,I-HAREM-GUARD,2
	MOVE	HAREM-GUARD,AUDIENCE-CHAMBER
	SET	'AWAITING-FAKE-ORPHAN,TRUE-VALUE
	PRINTI	"A well-armed "
	ZERO?	MALE /?CND14
	PRINTI	"fe"
?CND14:	PRINTI	"male guard blocks you. ""Congratulations on your performance,"" "
	ICALL1	SHE-HE
	PRINTI	" says in a bored voice. You wonder how the guard can be so unmoved by your historic feat. As though sensing your thoughts, the guard says, ""The "
	ICALL2	DPRINT,SULTAN
	PRINTI	" likes to pretend that no one's ever gotten the riddle, but someone got it last year, the word spread around, and now everyone knows the answer. You're the twelfth winner this week already. "
	ICALL2	HE-SHE,TRUE-VALUE
	PRINTI	" sent away to Maude's House of Riddles on Ganymede for a new one, but the mail is so slow..."" The guard shakes "
	ICALL1	HER-HIS
	PRINTI	" head. ""Well, pick a "
	ZERO?	MALE /?CCL18
	PRINTI	"wife"
	JUMP	?CND16
?CCL18:	PRINTI	"husband"
?CND16:	PRINTI	"; any number from 1 to 8379. Don't waste time thinking; they're all clones anyway."" "
	ICALL2	SHE-HE,TRUE-VALUE
	PRINTI	" looks at you expectantly."
	CRLF	
	RFALSE	


	.FUNCT	HUSBAND-NOT-HERE-F
	EQUAL?	PRSA,V?PICK \?CCL3
	IN?	HAREM-GUARD,HERE \?CCL3
	CALL2	I-HAREM-GUARD,TRUE-VALUE
	RSTACK	
?CCL3:	CALL1	PRSO-MOBY-VERB?
	ZERO?	STACK \FALSE
	CALL1	PRSI-MOBY-VERB?
	ZERO?	STACK \FALSE
	CALL2	CANT-SEE,HUSBAND-NOT-HERE
	RSTACK	


	.FUNCT	WIFE-NOT-HERE-F
	EQUAL?	PRSA,V?PICK \?CCL3
	IN?	HAREM-GUARD,HERE \?CCL3
	CALL2	I-HAREM-GUARD,TRUE-VALUE
	RSTACK	
?CCL3:	CALL1	PRSO-MOBY-VERB?
	ZERO?	STACK \FALSE
	CALL1	PRSI-MOBY-VERB?
	ZERO?	STACK \FALSE
	CALL2	CANT-SEE,WIFE-NOT-HERE
	RSTACK	


	.FUNCT	HAREM-GUARD-F
	EQUAL?	HAREM-GUARD,WINNER \?CCL3
	EQUAL?	PRSA,V?ANSWER-KLUDGE \?CCL6
	EQUAL?	PRSO,INTNUM \?CCL6
	CALL2	PICK-WIFE,INTNUM
	RSTACK	
?CCL6:	CALL2	I-HAREM-GUARD,TRUE-VALUE
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?FOLLOW \FALSE
	EQUAL?	FOLLOW-FLAG,13,14 \FALSE
	CALL2	DO-WALK,P?WEST
	RSTACK	


	.FUNCT	I-HAREM-GUARD,CALLED-BY-HAREM-GUARD-F
	INC	'HAREM-GUARD-COUNTER
	ZERO?	CALLED-BY-HAREM-GUARD-F /?CCL3
	ICALL	QUEUE,I-HAREM-GUARD,2
	JUMP	?CND1
?CCL3:	ICALL	QUEUE,I-HAREM-GUARD,-1
?CND1:	EQUAL?	HERE,AUDIENCE-CHAMBER \?CCL5
	GRTR?	CHOICE-NUMBER,0 \?CND4
?CCL5:	SET	'AWAITING-FAKE-ORPHAN,FALSE-VALUE
	ICALL2	DEQUEUE,I-HAREM-GUARD
	REMOVE	HAREM-GUARD
	RFALSE	
?CND4:	ZERO?	CALLED-BY-HAREM-GUARD-F \?CND8
	PRINTI	"   "
?CND8:	PRINTC	34
	EQUAL?	HAREM-GUARD-COUNTER,5 \?CCL12
	REMOVE	HAREM-GUARD
	SET	'FOLLOW-FLAG,14
	ICALL	QUEUE,I-FOLLOW,2
	ICALL2	DEQUEUE,I-HAREM-GUARD
	SET	'AWAITING-FAKE-ORPHAN,FALSE-VALUE
	PRINTR	"I'm not waiting around anymore! You blew it, sucker."" The guard storms angrily away."
?CCL12:	PRINTI	"Ahem? A number...?"" says"
	ICALL2	TPRINT,HAREM-GUARD
	EQUAL?	HAREM-GUARD-COUNTER,4 \?CND13
	PRINTI	" with growing impatience"
?CND13:	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	PICK-WIFE,OBJ,DUPE
	EQUAL?	OBJ,INTNUM /?CTR2
	CALL2	NUMBER?,P-CONT
	EQUAL?	STACK,W?NUMBER \?CCL3
?CTR2:	LESS?	P-NUMBER,1 \?CCL8
	PRINT	GIMME-TROUBLE
	JUMP	?CND1
?CCL8:	GRTR?	P-NUMBER,8379 \?CCL10
	PRINTI	"""There're only 8379 of 'em."""
	CRLF	
	JUMP	?CND1
?CCL10:	INTBL?	P-NUMBER,WRONG-ANSWERS,8 >DUPE \?CCL12
	PRINTI	"""You already asked for that one, dodo-brain!"""
	CRLF	
	JUMP	?CND1
?CCL12:	EQUAL?	P-NUMBER,WIFE-NUMBER /?CTR13
	RANDOM	100
	LESS?	HAREM-PROB,STACK /?CCL14
?CTR13:	SET	'CHOICE-NUMBER,P-NUMBER
	SET	'AWAITING-FAKE-ORPHAN,FALSE-VALUE
	SET	'FOLLOW-FLAG,13
	ICALL	QUEUE,I-FOLLOW,2
	REMOVE	HAREM-GUARD
	ICALL	QUEUE,I-HAREM,5
	PRINTI	"The guard, walking off, says, ""I'll summon that one. You may enter."""
	CRLF	
	JUMP	?CND1
?CCL14:	DIV	HAREM-PROB,15
	PUT	WRONG-ANSWERS,STACK,P-NUMBER
	ADD	HAREM-PROB,15 >HAREM-PROB
	PRINTI	"The guard consults a list. """
	RANDOM	100
	LESS?	25,STACK /?CCL19
	PRINTI	"Traded to the Du"
	ZERO?	MALE /?CCL22
	PRINTI	"ke"
	JUMP	?CND20
?CCL22:	PRINTI	"chess"
?CND20:	PRINTI	" of Deimos for two eunuchs and a jester to be named later"
	JUMP	?CND17
?CCL19:	CALL2	PICK-ONE,EXCUSES
	PRINT	STACK
?CND17:	PRINTI	". Pick another number."""
	CRLF	
	JUMP	?CND1
?CCL3:	PRINTI	"[Please give your selection in numerical form.]"
	CRLF	
?CND1:	ICALL	QUEUE,I-HAREM-GUARD,2
	CALL1	STOP
	RSTACK	


	.FUNCT	SULTAN-F,OARG
	ZERO?	OARG /?CCL3
	EQUAL?	OARG,M-OBJDESC? /TRUE
	PRINTI	"   The "
	ICALL2	DPRINT,SULTAN
	PRINTI	" is here,"
	ZERO?	RIDDLE-ANSWERED /?CCL8
	CALL1	ARGUING-WITH-LEGAL-ADVISOR
	RSTACK	
?CCL8:	PRINTI	" enthroned."
	RTRUE	
?CCL3:	EQUAL?	SULTAN,WINNER \?CCL10
	EQUAL?	PRSA,V?TELL-ABOUT \?CCL13
	EQUAL?	PRSO,ME \?CCL13
	EQUAL?	PRSI,LGOP \?CCL13
	PRINTR	"""They were exiled from Leather Island in the Caribbean, after cheating in the Miss Leather Island beauty pageant; the silicone injectionist spilled the beans. Now they rule all of Phobos. Hmmph! They call that hunk of rock a Sultanate? Those bimbos never told a decent riddle in their lives!"""
?CCL13:	EQUAL?	PRSA,V?WHERE,V?WHAT \?CCL18
	PRINTR	"""I ask the riddles around here!"""
?CCL18:	EQUAL?	PRSA,V?YES \?CCL20
	EQUAL?	AWAITING-REPLY,1 \?CCL20
	CALL1	V-YES
	RSTACK	
?CCL20:	EQUAL?	PRSA,V?NO \?CCL24
	EQUAL?	AWAITING-REPLY,1 \?CCL24
	CALL1	V-NO
	RSTACK	
?CCL24:	EQUAL?	PRSA,V?USE-QUOTES,V?ANSWER-KLUDGE \?CCL28
	ZERO?	AWAITING-FAKE-ORPHAN /?CCL28
	ZERO?	RIDDLE-ANSWERED \?CCL28
	EQUAL?	PRSO,RIDDLE /?CND32
	ICALL1	RIDDLE-ANSWER
	RTRUE	
?CND32:	SET	'RIDDLE-ANSWERED,TRUE-VALUE
	ICALL2	DEQUEUE,I-SNEEZE
	ICALL	INCREMENT-SCORE,8,11
	PRINTI	"The "
	ICALL2	DPRINT,SULTAN
	PRINTI	" looks crestfallen. ""Yes, that's right."" The "
	ICALL2	DPRINT,SULTAN
	PRINTI	" is struck by a thought. ""Can we kill "
	ICALL1	HIM-HER
	PRINTI	" anyway?"" "
	ICALL2	HE-SHE,TRUE-VALUE
	PRINTI	" begins"
	ICALL1	ARGUING-WITH-LEGAL-ADVISOR
	PRINTR	" This might be a good time to make a beeline for the harem to the west."
?CCL28:	PRINTI	"The "
	ICALL2	DPRINT,SULTAN
	PRINTI	" ignores you."
	CRLF	
	CALL1	STOP
	RSTACK	
?CCL10:	ZERO?	RIDDLE-ANSWERED \?CCL35
	CALL2	TOUCHING?,SULTAN
	ZERO?	STACK \?CTR34
	EQUAL?	PRSA,V?THROW \?CCL35
	EQUAL?	PRSI,SULTAN \?CCL35
?CTR34:	CALL2	DO-WALK,P?WEST
	RSTACK	
?CCL35:	EQUAL?	PRSA,V?SHOW,V?GIVE \?CCL43
	EQUAL?	PRSO,CODED-MESSAGE \?CCL43
	PRINTI	"""A spy! A spy!"" "
	CALL1	RIDDLE-DEATH
	RSTACK	
?CCL43:	EQUAL?	PRSA,V?LISTEN \FALSE
	ZERO?	RIDDLE-ANSWERED /FALSE
	PRINTI	"The "
	ICALL2	DPRINT,SULTAN
	PRINTI	" is"
	ICALL1	ARGUING-WITH-LEGAL-ADVISOR
	CRLF	
	RTRUE	


	.FUNCT	ARGUING-WITH-LEGAL-ADVISOR
	PRINTI	" arguing loudly with one of "
	ICALL1	HIS-HER
	PRINTI	" legal advisors."
	RTRUE	


	.FUNCT	I-SULTAN
	INC	'SULTAN-COUNTER
	PRINTI	"   "
	GRTR?	SULTAN-COUNTER,1 \?CCL3
	EQUAL?	SULTAN-COUNTER,4 \?CCL6
	PRINTI	"""Have this bore devoured."" "
	ICALL1	RIDDLE-DEATH
	JUMP	?CND1
?CCL6:	PRINTI	"""I grow impatient. "
	JUMP	?CND1
?CCL3:	SET	'AWAITING-REPLY,1
	PRINTI	"""Ah,"" says"
	ICALL2	TPRINT,SULTAN
	PRINTI	", ""a visitor. This is pleasing; it was turning out to be a very dull morning."" "
	ICALL2	HE-SHE,TRUE-VALUE
	PRINTI	" clears "
	ICALL1	HIS-HER
	PRINTI	" throat. ""The rules: I will pose a riddle. If you answer it correctly, you may spend one hour with any of my "
	ZERO?	MALE /?CCL9
	PRINTI	"wive"
	JUMP	?CND7
?CCL9:	PRINTI	"husband"
?CND7:	PRINTI	"s."
	ICALL2	YOU-WILL-DIE,STR?287
	ICALL2	YOU-WILL-DIE,STR?288
	ICALL2	YOU-WILL-DIE,STR?289
	ICALL2	YOU-WILL-DIE,STR?290
	ICALL2	YOU-WILL-DIE,STR?291
	ICALL2	YOU-WILL-DIE,STR?292
	ICALL2	YOU-WILL-DIE,STR?293
	PRINTI	""" "
	ICALL2	HE-SHE,TRUE-VALUE
	SET	'AWAITING-REPLY,1
	PRINTI	" motions to one of the palace eunuchs. ""Go tell the animal tenders not to feed the tigers yet."" Pause. """
?CND1:	PRINTR	"Are you ready?"""


	.FUNCT	YOU-WILL-DIE,STRING
	PRINTI	" If "
	PRINT	STRING
	PRINTI	", you will die."
	RTRUE	


	.FUNCT	RIDDLE-DEATH
	CALL2	JIGS-UP,STR?294
	RSTACK	


	.FUNCT	I-SNEEZE
	ICALL	QUEUE,I-SNEEZE,-1
	INC	'SULTAN-COUNTER
	PRINTI	"   The "
	ICALL2	DPRINT,SULTAN
	EQUAL?	SULTAN-COUNTER,4 \?CCL3
	PRINTI	" convulses. ""Achoooooo!!!!"" "
	CALL1	RIDDLE-DEATH
	RSTACK	
?CCL3:	EQUAL?	SULTAN-COUNTER,3 \?CCL5
	PRINTR	" is squinting and drawing in quick gasps of air!"
?CCL5:	EQUAL?	SULTAN-COUNTER,2 \?CCL7
	PRINTI	" is rubbing "
	ICALL1	HIS-HER
	PRINTI	" nose with the back of "
	ICALL1	HIS-HER
	PRINTR	" hand."
?CCL7:	PRINTI	" is twitching "
	ICALL1	HIS-HER
	PRINTR	" nose."


	.FUNCT	RIDDLE-ANSWER
	ZERO?	P-CONT \?CCL3
	ZERO?	PRSO \?CCL3
	SET	'PRSO,SULTAN
	ICALL1	V-TELL
	RETURN	STR?295
?CCL3:	ZERO?	P-CONT /?CCL7
	GET	P-LEXV,P-CONT
	EQUAL?	STACK,W?RIDDLE /?CTR6
	ADD	P-CONT,2
	GET	P-LEXV,STACK
	EQUAL?	STACK,W?RIDDLE \?CCL7
?CTR6:	SET	'WINNER,SULTAN
	ICALL	PERFORM,V?ANSWER-KLUDGE,RIDDLE
	SET	'WINNER,PROTAGONIST
	CALL1	STOP
	RSTACK	
?CCL7:	ZERO?	P-CONT /?PRD15
	GET	P-LEXV,P-CONT
	EQUAL?	STACK,W?SEX,W?LOVE /?CTR12
?PRD15:	EQUAL?	PRSO,LOVE \?CCL13
?CTR12:	PRINTI	"""Good guess! It's wrong, though."" "
	CALL1	RIDDLE-DEATH
	RSTACK	
?CCL13:	PRINTI	"""Wrongo!"" "
	CALL1	RIDDLE-DEATH
	RSTACK	


	.FUNCT	HAREM-F,RARG
	EQUAL?	RARG,M-LOOK \?CCL3
	PRINTI	"This is a sensuous location of silks and satins and furs. A draped exit leads east."
	FSET?	NOSE,MUNGBIT /TRUE
	PRINTI	" A pleasant odor"
	FSET?	HERE,SMELLEDBIT \?CND6
	PRINTI	" of "
	GETP	HERE,P?ODOR
	PRINT	STACK
?CND6:	PRINTI	" tickles mischievously at "
	PRINTD	NOSE
	PRINTC	46
	RTRUE	
?CCL3:	EQUAL?	RARG,M-END \?CCL9
	IN?	SIDEKICK,HERE \?CCL9
	CALL2	QUEUED?,I-HAREM
	ZERO?	STACK /?CCL9
	PRINTI	"   A "
	PRINTD	HAREM-GUARD
	PRINTI	" grabs "
	ICALL1	DPRINT-SIDEKICK
	PRINTI	". ""You didn't answer the riddle!"" "
	CALL1	TIGER-EATS-SIDEKICK
	RSTACK	
?CCL9:	EQUAL?	RARG,M-SMELL \FALSE
	PRINT	IT-SEEMS-THAT
	ICALL2	TPRINT,SULTAN
	PRINTI	" likes h"
	ZERO?	MALE /?CCL17
	PRINTI	"is wives"
	JUMP	?CND15
?CCL17:	PRINTI	"er husbands"
?CND15:	PRINTI	" to wear fine "
	GETP	HERE,P?ODOR
	PRINT	STACK
	PRINTC	46
	RTRUE	


	.FUNCT	TIGER-EATS-SIDEKICK
	REMOVE	SIDEKICK
	SET	'FOLLOW-FLAG,2
	ICALL	QUEUE,I-FOLLOW,2
	SET	'SIDEKICK-EATEN,TRUE-VALUE
	ICALL1	DPRINT-SIDEKICK
	PRINTI	" is led away. As you hear, from nearby, a fierce roar followed by a blood-curdling scream"
	CALL1	MEMORIAM
	RSTACK	


	.FUNCT	I-HAREM
	EQUAL?	HERE,HAREM \FALSE
	PRINTI	"   A figure, completely cloaked in veils of silk, enters and beckons you deeper into the harem"
	PRINT	ELLIPSIS
	ICALL2	GOTO,INNER-HAREM
	ICALL2	THIS-IS-IT,SULTANS-WIFE
	FCLEAR	SULTANS-WIFE,NDESCBIT
	ICALL	QUEUE,I-HOUR,60
	PRINTI	"   "
	ICALL2	DPRINT,SULTANS-WIFE
	ZERO?	NAUGHTY-LEVEL \?CCL6
	PRINTR	" sits down at the far end of the room."
?CCL6:	PRINTI	" touches a button at the shoulder of "
	ICALL1	HER-HIS
	PRINTI	" tunic and it slowly floats to the floor. "
	ICALL2	SHE-HE,TRUE-VALUE
	PRINTR	" pulls you down onto the furs, whispering in a husky voice, ""For an hour, I am yours."""


	.FUNCT	I-HOUR
	EQUAL?	HERE,INNER-HAREM \FALSE
	PRINTI	"   ""The hour is over,"" sighs "
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTI	", reluctantly leading you out of the "
	PRINTD	HERE
	PRINT	ELLIPSIS
	CALL2	GOTO,HAREM
	RSTACK	


	.FUNCT	HAREM-OBJECT-F
	EQUAL?	PRSA,V?BOARD,V?WALK-TO,V?ENTER \?CCL3
	EQUAL?	HERE,AUDIENCE-CHAMBER \?CCL6
	CALL2	DO-WALK,P?WEST
	RSTACK	
?CCL6:	EQUAL?	HERE,HAREM,INNER-HAREM \FALSE
	PRINT	LOOK-AROUND
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?DISEMBARK,V?EXIT,V?LEAVE \?CCL10
	EQUAL?	HERE,AUDIENCE-CHAMBER \?CCL13
	PRINT	LOOK-AROUND
	RTRUE	
?CCL13:	CALL2	DO-WALK,P?OUT
	RSTACK	
?CCL10:	EQUAL?	PRSA,V?EXAMINE \?CCL15
	EQUAL?	HERE,AUDIENCE-CHAMBER /?CCL15
	CALL1	V-LOOK
	RSTACK	
?CCL15:	EQUAL?	PRSA,V?SMELL \?CCL19
	EQUAL?	HERE,AUDIENCE-CHAMBER /?CCL19
	ICALL2	PERFORM-PRSA,ODOR
	RTRUE	
?CCL19:	EQUAL?	PRSA,V?SEARCH \FALSE
	PRINT	NOTHING-NEW
	RTRUE	


	.FUNCT	INNER-HAREM-F,RARG
	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"This luxurious bedroom, presumably one of many throughout the harem, is appointed with a multitude of exotic furs, warm to the touch as though still alive. "
	FSET?	NOSE,MUNGBIT /?CND4
	PRINTI	"The heady aroma of "
	GETP	HAREM,P?ODOR
	PRINT	STACK
	PRINTI	" and incense mingle in the air. "
?CND4:	PRINTI	"There's an exit to the southeast"
	ZERO?	CATACOMBS-OPEN /?CND6
	PRINTI	" and a secret passage leads downward"
?CND6:	PRINTC	46
	RTRUE	


	.FUNCT	INNER-HAREM-EXIT-F
	CALL2	ULTIMATELY-IN?,MAP
	ZERO?	STACK /?CCL3
	CALL2	VISIBLE?,MAP
	ZERO?	STACK /?CCL3
	PRINTI	"As"
	ICALL2	TPRINT,SULTANS-WIFE
	CALL2	JIGS-UP,STR?296
	RSTACK	
?CCL3:	RETURN	HAREM


	.FUNCT	SULTANS-WIFE-F,OARG
	ZERO?	OARG /?CCL3
	EQUAL?	OARG,M-OBJDESC? /TRUE
	PRINTI	"   "
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTI	" is here"
	ZERO?	NAUGHTY-LEVEL /?CND6
	PRINTI	", lying seductively naked on a bed of furs"
?CND6:	PRINTC	46
	RTRUE	
?CCL3:	EQUAL?	WINNER,SULTANS-WIFE \?CCL9
	EQUAL?	PRSA,V?KISS \?PRD14
	EQUAL?	PRSO,KNEECAPS \?PRD14
	ZERO?	CATACOMBS-OPEN /?CTR11
?PRD14:	EQUAL?	PRSA,V?KISS-ON \?CCL12
	EQUAL?	PRSO,ME \?CCL12
	EQUAL?	PRSI,KNEECAPS \?CCL12
	ZERO?	CATACOMBS-OPEN \?CCL12
?CTR11:	EQUAL?	CHOICE-NUMBER,WIFE-NUMBER \?CCL24
	MOVE	MAP,HERE
	MOVE	TORCH,HERE
	ICALL	QUEUE,I-TORCH,23
	ICALL2	DEQUEUE,I-HOUR
	SET	'CATACOMBS-OPEN,TRUE-VALUE
	ICALL1	OPEN-EYES-AND-REMOVE-HANDS
	PRINTI	"""Oh,"" whispers "
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTI	", ""you're from the rebels! Here's"
	ICALL2	TPRINT,MAP
	PRINTI	","" "
	ICALL1	SHE-HE
	PRINTI	" says, laying"
	ICALL2	APRINT,MAP
	PRINTI	" at your feet, ""and here's"
	ICALL2	APRINT,TORCH
	PRINTI	","" "
	ICALL1	SHE-HE
	PRINTI	" says, lighting"
	ICALL2	APRINT,TORCH
	PRINTI	" and placing it next to the map. "
	ICALL2	SHE-HE,TRUE-VALUE
	PRINTI	" moves some furs to reveal a secret entrance leading downwards. ""The only way out is through the catacombs -- if you come back this way with"
	ICALL2	TPRINT,MAP
	PRINTC	44
	ICALL2	TPRINT,HAREM-GUARD
	PRINTR	"s will..."""
?CCL24:	PRINTR	"""I'm not into that kinky stuff."""
?CCL12:	EQUAL?	PRSA,V?FUCK,V?SUCK,V?KISS /?PRD28
	EQUAL?	PRSA,V?BLOW,V?LICK,V?EAT /?PRD28
	EQUAL?	PRSA,V?TOUCH,V?TAKE \?CCL26
?PRD28:	ZERO?	NAUGHTY-LEVEL \?CCL26
	EQUAL?	PRSO,COCK,ME \?CCL26
	SET	'WINNER,PROTAGONIST
	ICALL	PERFORM,V?FUCK,SULTANS-WIFE
	SET	'WINNER,SULTANS-WIFE
	RTRUE	
?CCL26:	EQUAL?	PRSA,V?KISS \?CCL34
	EQUAL?	PRSO,ME \?CCL34
	SET	'WINNER,PROTAGONIST
	ICALL2	PERFORM-PRSA,SULTANS-WIFE
	SET	'WINNER,SULTANS-WIFE
	RTRUE	
?CCL34:	EQUAL?	PRSA,V?TAKE,V?FUCK \?CCL38
	EQUAL?	PRSO,ME \?CCL38
	SET	'WINNER,PROTAGONIST
	ICALL	PERFORM,V?FUCK,SULTANS-WIFE
	SET	'WINNER,SULTANS-WIFE
	RTRUE	
?CCL38:	EQUAL?	PRSA,V?BLOW,V?LICK,V?EAT /?PRD44
	EQUAL?	PRSA,V?SUCK \?CCL42
?PRD44:	EQUAL?	PRSO,COCK,ME \?CCL42
	EQUAL?	NAUGHTY-LEVEL,1 \?CCL49
	PRINT	MISSIONARY-ONLY
	RTRUE	
?CCL49:	ICALL2	DPRINT,SULTANS-WIFE
	PRINTI	" nods eagerly and slides downward. Skillful tongue-work soon has you squirming on the edge of orgasm... Eventually, spent and satisfied, you take "
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTR	" lovingly into your arms."
?CCL42:	EQUAL?	PRSA,V?WHAT \?PRD53
	EQUAL?	PRSO,LGOP /?CTR50
?PRD53:	EQUAL?	PRSA,V?TELL-ABOUT \?CCL51
	EQUAL?	PRSO,ME \?CCL51
	EQUAL?	PRSI,LGOP \?CCL51
?CTR50:	PRINTR	"""That's the code name of the cadre who lead the rebel underground. It is said they have pledged their lives and souls to the revolution!"""
?CCL51:	PRINTI	"""Shhh... "
	ZERO?	NAUGHTY-LEVEL \?CCL61
	PRINTI	"It's past bedtime for the children of"
	ICALL2	TPRINT,SULTAN
	PRINTI	"! You'll wake them!"""
	CRLF	
	CALL1	STOP
	RSTACK	
?CCL61:	PRINTI	"Let "
	PRINTD	YOUR-BODY
	PRINTI	" do the talking,"" says "
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTI	", reaching out toward you."
	CRLF	
	CALL1	STOP
	RSTACK	
?CCL9:	CALL	WRONG-SEX-WORD,SULTANS-WIFE,W?WIFE,W?HUSBAND
	ZERO?	STACK /?CCL63
	CALL1	STOP
	RSTACK	
?CCL63:	EQUAL?	PRSA,V?THANK \?CCL65
	ZERO?	CATACOMBS-OPEN /?CCL65
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTR	" gives you a grand salute. ""For the revolution!"""
?CCL65:	EQUAL?	PRSA,V?FUCK,V?TOUCH,V?KISS /?PRD71
	EQUAL?	PRSA,V?TAKE \?CCL69
?PRD71:	ZERO?	NAUGHTY-LEVEL \?CCL69
	PRINTI	"Instead, you decide to get to know "
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTI	" better, so you engage "
	ICALL1	HER-HIM
	PRINTI	" in a stimulating discussion about "
	CALL2	PICK-ONE,DISCUSSION-TOPICS
	PRINT	STACK
	CRLF	
	RTRUE	
?CCL69:	EQUAL?	PRSA,V?EAT \?CCL75
	ZERO?	NAUGHTY-LEVEL \?CCL78
	CALL1	V-FUCK
	RSTACK	
?CCL78:	EQUAL?	NAUGHTY-LEVEL,1 \?CCL80
	PRINT	MISSIONARY-ONLY
	RTRUE	
?CCL80:	ICALL2	DPRINT,PRSO
	PRINTI	" arches "
	ICALL1	HER-HIS
	PRINTR	" body to meet you, passionately stroking your neck and shoulders."
?CCL75:	EQUAL?	PRSA,V?UNDRESS \?CCL82
	ZERO?	NAUGHTY-LEVEL /?CCL82
	ICALL2	SHE-HE,TRUE-VALUE
	PRINTR	" is!"
?CCL82:	EQUAL?	PRSA,V?DRESS \?CCL86
	PRINTR	"You must be from Massachusetts."
?CCL86:	EQUAL?	PRSA,V?TAKE,V?TOUCH,V?KISS \?CCL88
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTR	" moans softly and draws closer to you."
?CCL88:	EQUAL?	PRSA,V?FUCK \?CCL90
	ZERO?	WIFE-FUCKED /?CND91
	PRINTR	"You shouldn't wear yourself out. [Besides, do you think there's infinite room on this disk for long, lurid descriptions of sex acts?]"
?CND91:	SET	'WIFE-FUCKED,TRUE-VALUE
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTI	" draws you into "
	ICALL1	HER-HIS
	PRINTI	" arms. "
	EQUAL?	NAUGHTY-LEVEL,2 \?CND93
	PRINTI	"As "
	PRINTD	HANDS
	PRINTI	"s explore h"
	ZERO?	MALE /?CCL97
	PRINTI	"er soft, rounded"
	JUMP	?CND95
?CCL97:	PRINTI	"is firm, strong"
?CND95:	PRINTI	" body, a faint sweaty, musky odor triggers a passionate fire within you, and you find yourself "
	ZERO?	MALE /?CCL100
	PRINTI	"ris"
	JUMP	?CND98
?CCL100:	PRINTI	"warm"
?CND98:	PRINTI	"ing to the occasion. Your lovemaking is slow and gentle, and as you reach a crescendo of pleasure, you cry out softly, passionately, and repeatedly. ""Oh,"" moans "
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTI	", ""say my number again ... say it in French..."""
	CRLF	
?CND93:	PRINTI	"Much later, you and "
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTR	" fall back upon the furs, basking in the aura of postcoital bliss."
?CCL90:	EQUAL?	PRSA,V?MARRY \?CCL102
	PRINTI	"But "
	ICALL2	DPRINT,PRSO
	PRINTR	" is already married!"
?CCL102:	EQUAL?	PRSA,V?MEASURE \?CCL104
	ZERO?	MALE /?CCL107
	PRINTI	"36-24-36"
	JUMP	?CND105
?CCL107:	ZERO?	NAUGHTY-LEVEL \?CCL109
	PRINTI	"Tall"
	JUMP	?CND105
?CCL109:	EQUAL?	NAUGHTY-LEVEL,1 \?CCL111
	PRINTI	"Long"
	JUMP	?CND105
?CCL111:	PRINTI	"Ten delicious inches"
?CND105:	PRINT	PERIOD-CR
	RTRUE	
?CCL104:	EQUAL?	PRSA,V?EXAMINE \?CCL113
	ZERO?	NAUGHTY-LEVEL /?CCL113
	PRINTI	"A mere glance at the succulent, sexy body of "
	ICALL2	DPRINT,SULTANS-WIFE
	PRINTI	" is enough to "
	EQUAL?	NAUGHTY-LEVEL,1 \?CCL118
	PRINTI	"really turn you on"
	JUMP	?CND116
?CCL118:	ZERO?	MALE /?CCL120
	PRINTI	"give you an instant hard-on"
	JUMP	?CND116
?CCL120:	PRINTI	"get you all moist and randy"
?CND116:	PRINT	PERIOD-CR
	RTRUE	
?CCL113:	EQUAL?	PRSA,V?SMELL \FALSE
	ICALL2	SHE-HE,TRUE-VALUE
	PRINTI	" smells of "
	GETP	HAREM,P?ODOR
	PRINT	STACK
	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	TORCH-F
	EQUAL?	PRSA,V?OFF \?CCL3
	FSET?	TORCH,ONBIT \?CCL3
	ICALL1	TORCH-OFF
	PRINT	PFFT
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?ON \?CCL7
	FSET?	TORCH,ONBIT /?CCL7
	ICALL	PERFORM,V?BURN,TORCH
	RTRUE	
?CCL7:	EQUAL?	PRSA,V?BURN \?CCL11
	EQUAL?	PRSO,TORCH \?CCL11
	FSET?	TORCH,ONBIT \?CCL11
	ICALL	PERFORM,V?ON,TORCH
	RTRUE	
?CCL11:	EQUAL?	PRSA,V?PUT-ON,V?PUT \?CCL16
	FSET?	TORCH,ONBIT \?CCL16
	EQUAL?	PRSI,TRELLIS,BARGE \?CCL16
	FSET?	PRSI,UNTEEDBIT /?CCL16
	PRINTI	"The "
	PRINTD	PRSI
	PRINTR	" would burn!"
?CCL16:	EQUAL?	PRSA,V?PUT \FALSE
	EQUAL?	PRSI,WATER,CANAL \FALSE
	FSET?	TORCH,ONBIT \FALSE
	ICALL1	TORCH-OFF
	PRINT	PFFT
	RTRUE	


	.FUNCT	TORCH-OFF
	ICALL2	DEQUEUE,I-TORCH
	FCLEAR	TORCH,ONBIT
	FCLEAR	TORCH,LIGHTBIT
	PUTP	TORCH,P?SDESC,STR?304
	FSET	TORCH,VOWELBIT
	RTRUE	


	.FUNCT	I-TORCH
	DEC	'TORCH-LIFE
	ZERO?	TORCH-LIFE \?CCL3
	ICALL1	TORCH-OFF
	JUMP	?CND1
?CCL3:	MUL	TORCH-LIFE,6
	ICALL	QUEUE,I-TORCH,STACK
?CND1:	CALL2	VISIBLE?,TORCH
	ZERO?	STACK /FALSE
	FSET?	EYES,MUNGBIT /FALSE
	EQUAL?	HAND-COVER,EYES /FALSE
	PRINTI	"   "
	ZERO?	TORCH-LIFE \?CCL11
	PRINT	PFFT
	ICALL1	NOW-DARK?
	RFALSE	
?CCL11:	PRINTI	"The torch is noticeably dimmer."
	CRLF	
	RFALSE	


	.FUNCT	MAP-F
	EQUAL?	PRSA,V?EXAMINE,V?READ \FALSE
	FSET?	PRSO,UNTEEDBIT /FALSE
	ICALL2	IN-YOUR-PACKAGE,STR?306
	CRLF	
	RTRUE	


	.FUNCT	CATACOMBS-ENTER-F
	ZERO?	CATACOMBS-OPEN /?CCL3
	ICALL	QUEUE,I-BEETLES,6
	ICALL	QUEUE,I-CRABS,10
	ICALL	QUEUE,I-GATOR,12
	PRINTI	"As you leave, "
	ZERO?	NAUGHTY-LEVEL \?CCL6
	ICALL	PERFORM,V?THANK,SULTANS-WIFE
	CRLF	
	RETURN	CATACOMBS
?CCL6:	ICALL2	DPRINT,SULTANS-WIFE
	ZERO?	MALE /?CCL9
	PRINTI	" throws herself into your arms. Her ample bosom presses against your chest as she whispers into your ear, ""Please, oh, please be careful down there!"" Sh"
	JUMP	?CND7
?CCL9:	PRINTI	" gathers you into his powerful arms. Nibbling tenderly on your neck, he whispers, ""Be wary -- the catacombs are dangerous."" H"
?CND7:	PRINTI	"e kisses you longingly, but eventually you descend, reluctantly, into the gloom of the catacombs"
	PRINT	ELLIPSIS
	RETURN	CATACOMBS
?CCL3:	PRINT	CANT-GO
	RFALSE	


	.FUNCT	CATACOMBS-F,RARG
	EQUAL?	RARG,M-LOOK \?CCL3
	PRINTI	"You're at a junction within an ancient, crumbling catacomb. Your "
	CALL2	ULTIMATELY-IN?,TORCH
	ZERO?	STACK /?CND4
	FSET?	TORCH,ONBIT \?CND4
	PRINTI	"torch"
?CND4:	PRINTI	"light pierces the gloom for only a few feet in each direction. "
	PRINT	CATACOMBS-WATER-DESC
	RTRUE	
?CCL3:	EQUAL?	RARG,M-END \FALSE
	ZERO?	SIDEKICK-EATEN /FALSE
	MOVE	SIDEKICK,HERE
	SET	'SIDEKICK-EATEN,FALSE-VALUE
	PRINTI	"   ""Yo!"" says "
	ICALL1	DPRINT-SIDEKICK
	PRINTI	", tapping your shoulder. ""Looked like my number was up that time! Would've been, if those dimension-hopping midgets hadn't come through at the right moment. Good thing the tiger cage leads to the catacombs, eh?"" "
	ICALL2	HE-SHE,TRUE-VALUE
	PRINTI	" brushes a stray patch of fur off "
	ICALL1	HIS-HER
	PRINTR	" shoulder."


	.FUNCT	CATACOMBS-MOVEMENT-F,DIR-OFFSET,TABLE-VALUE
	ZERO?	LIT \?CND1
	ICALL2	JIGS-UP,STR?307
?CND1:	EQUAL?	PRSO,P?NORTH \?CCL5
	SET	'DIR-OFFSET,0
	JUMP	?CND3
?CCL5:	EQUAL?	PRSO,P?NE \?CCL7
	SET	'DIR-OFFSET,1
	JUMP	?CND3
?CCL7:	EQUAL?	PRSO,P?EAST \?CCL9
	SET	'DIR-OFFSET,2
	JUMP	?CND3
?CCL9:	EQUAL?	PRSO,P?SE \?CCL11
	SET	'DIR-OFFSET,3
	JUMP	?CND3
?CCL11:	EQUAL?	PRSO,P?SOUTH \?CCL13
	SET	'DIR-OFFSET,4
	JUMP	?CND3
?CCL13:	EQUAL?	PRSO,P?SW \?CCL15
	SET	'DIR-OFFSET,5
	JUMP	?CND3
?CCL15:	EQUAL?	PRSO,P?WEST \?CCL17
	SET	'DIR-OFFSET,6
	JUMP	?CND3
?CCL17:	EQUAL?	PRSO,P?NW \?CCL19
	SET	'DIR-OFFSET,7
	JUMP	?CND3
?CCL19:	EQUAL?	PRSO,P?UP \?CCL21
	SET	'DIR-OFFSET,8
	JUMP	?CND3
?CCL21:	SET	'DIR-OFFSET,9
?CND3:	SUB	CATACOMBS-LOC,1
	MUL	STACK,10
	ADD	STACK,DIR-OFFSET
	GET	CATACOMBS-TABLE,STACK >TABLE-VALUE
	PRINTI	"You wade into the gloom ... and find "
	ZERO?	TABLE-VALUE \?CCL24
	EQUAL?	PRSO,P?DOWN,P?UP \?CCL27
	PRINTI	"a severe paucity of passages leading "
	EQUAL?	PRSO,P?UP \?CCL30
	PRINTI	"up"
	JUMP	?CND25
?CCL30:	PRINTI	"down"
	JUMP	?CND25
?CCL27:	PRINTI	"yourself face to face with a blank wall"
?CND25:	PRINT	PERIOD-CR
	RFALSE	
?CCL24:	PRINTI	"a "
	EQUAL?	PRSO,P?DOWN,P?UP \?CCL33
	PRINTI	"hidden passage leading "
	EQUAL?	PRSO,P?UP \?CCL36
	PRINTI	"up"
	JUMP	?CND34
?CCL36:	PRINTI	"down"
?CND34:	PRINTI	"wards."
	JUMP	?CND31
?CCL33:	PRINTI	"dark and winding tunnel."
?CND31:	EQUAL?	TABLE-VALUE,99 \?CCL39
	PRINTI	" Unfortunately, you soon come to a point where the tunnel has collapsed, hopelessly blocking your way."
	CRLF	
	RFALSE	
?CCL39:	EQUAL?	TABLE-VALUE,80 \?CCL41
	PRINTI	" Unfortunately, it's too steep and slippery."
	CRLF	
	RFALSE	
?CCL41:	CRLF	
	CRLF	
	EQUAL?	TABLE-VALUE,40 \?CCL44
	RETURN	FORGOTTEN-STOREHOUSE
?CCL44:	EQUAL?	TABLE-VALUE,50 \?CCL46
	RETURN	WELL-BOTTOM
?CCL46:	EQUAL?	TABLE-VALUE,60 \?CCL48
	RETURN	LADDER-ROOM
?CCL48:	EQUAL?	TABLE-VALUE,70 \?CCL50
	RETURN	BURIAL-CHAMBER
?CCL50:	SET	'CATACOMBS-LOC,TABLE-VALUE
	ICALL1	DESCRIBE-ROOM
	IN?	SIDEKICK,HERE /?CCL52
	RETURN	ROOMS
?CCL52:	ICALL1	SIDEKICK-FOLLOWS-YOU
	RETURN	ROOMS


	.FUNCT	PHONE-BOOK-F
	EQUAL?	PRSA,V?OPEN,V?LOOK-INSIDE,V?READ \?CCL3
	PRINTR	"How useful. Now you know how many Smiths live in Cleveland."
?CCL3:	EQUAL?	PRSA,V?CLOSE \?CCL5
	PRINTR	"It is."
?CCL5:	EQUAL?	PRSA,V?TAKE \FALSE
	FSET?	PHONE-BOOK,TOUCHBIT /FALSE
	FSET	PHONE-BOOK,TOUCHBIT
	ICALL	INCREMENT-SCORE,13,26,TRUE-VALUE
	RFALSE	


	.FUNCT	WELL-BOTTOM-EXIT-F
	EQUAL?	PRSO,P?EAST \?CCL3
	SET	'CATACOMBS-LOC,21
	RETURN	CATACOMBS
?CCL3:	SET	'CATACOMBS-LOC,22
	RETURN	CATACOMBS


	.FUNCT	WELL-BOTTOM-LOOP-F
	ICALL1	DESCRIBE-ROOM
	IN?	SIDEKICK,HERE \FALSE
	ICALL1	NORMAL-SIDEKICK-FOLLOW
	RFALSE	


	.FUNCT	LADDER-ROOM-EXIT-F
	PRINTI	"You climb for a seemingly endless time, with the ladder becoming increasingly rickety. Suddenly a rung snaps, and you tumble into the darkness! You bounce painfully into a slanted ventilation shaft, slide through a wooden grating, and land amidst thousands of silk "
	ZERO?	MALE /?CCL3
	PRINTI	"brassieres"
	JUMP	?CND1
?CCL3:	PRINTI	"jockstraps"
?CND1:	PRINT	PERIOD-CR
	CRLF	
	RETURN	LAUNDRY-ROOM


	.FUNCT	LADDER-F
	EQUAL?	PRSA,V?CLIMB-UP,V?CLIMB \FALSE
	CALL2	DO-WALK,P?UP
	RSTACK	


	.FUNCT	RAFT-F,OARG,NUM
	ZERO?	OARG /?CCL3
	FSET?	RAFT,TOUCHBIT /?CCL6
	EQUAL?	OARG,M-OBJDESC? /TRUE
	PRINTI	"   On the other hand, another Sultan had a considerably more modest vision of the afterlife, bringing only a simple rubber life raft."
	RTRUE	
?CCL6:	ZERO?	RAFT-HELD /?CCL10
	EQUAL?	OARG,M-OBJDESC? /TRUE
	PRINTI	"   There is a raft here, which you're keeping a hand on."
	RTRUE	
?CCL10:	EQUAL?	HERE,CANAL \FALSE
	EQUAL?	OARG,M-OBJDESC? /TRUE
	PRINTI	"   A raft is floating nearby."
	RTRUE	
?CCL3:	EQUAL?	HERE,CANAL \?CCL18
	IN?	PROTAGONIST,BARGE \?CCL18
	IN?	RAFT,CANAL \?CCL18
	EQUAL?	RAFT-LOC-NUM,BARGE-LOC-NUM /?CCL18
	CALL2	CANT-SEE,RAFT
	RSTACK	
?CCL18:	FSET?	RAFT,UNTEEDBIT /FALSE
	EQUAL?	PRSA,V?SINK \?CCL26
	ZERO?	RAFT-HELD \?CTR28
	EQUAL?	HERE,CANAL \?CCL29
	IN?	PROTAGONIST,RAFT \?CCL29
?CTR28:	ICALL	PERFORM,V?DEFLATE,RAFT
	RTRUE	
?CCL29:	PRINTR	"It's not even in water!"
?CCL26:	EQUAL?	PRSA,V?PUT \?CCL35
	CALL1	IN-CATACOMBS
	ZERO?	STACK /?CCL35
	EQUAL?	PRSI,WATER \?CCL35
	ICALL	PERFORM,V?DROP,RAFT
	RTRUE	
?CCL35:	EQUAL?	PRSA,V?THROW,V?DROP \?CCL40
	EQUAL?	PRSO,RAFT \?CCL40
	CALL1	IN-CATACOMBS
	ZERO?	STACK /?CCL40
	REMOVE	RAFT
	PRINTR	"The raft floats into the darkness. Oh, well, easy come, easy go."
?CCL40:	EQUAL?	PRSA,V?DROP \?CCL45
	ZERO?	RAFT-HELD /?CCL45
	SET	'RAFT-HELD,FALSE-VALUE
	MOVE	RAFT,CANAL
	ICALL1	SET-RAFT-LOC
	ICALL	QUEUE,I-CANAL,-1
	PRINTI	"The raft "
	EQUAL?	HERE,CANAL \?CCL50
	ZERO?	BARGE-UNDER-POWER /?CCL53
	PRINTI	"is left behind in the wake of"
	JUMP	?CND51
?CCL53:	SET	'RAFT-WAIT,BARGE-WAIT
	PRINTI	"floats along beside"
?CND51:	PRINTR	" the barge."
?CCL50:	PRINTR	"is swept away."
?CCL45:	EQUAL?	PRSA,V?TAKE \?CCL55
	EQUAL?	PRSO,RAFT \?CCL55
	FSET?	RAFT,TOUCHBIT /?CCL55
	FSET	RAFT,TOUCHBIT
	ICALL	INCREMENT-SCORE,8,3
	RFALSE	
?CCL55:	EQUAL?	PRSA,V?TAKE \?CCL60
	IN?	YOUR-BODY,RAFT /?CTR59
	IN?	SIDEKICKS-BODY,RAFT \?CCL60
?CTR59:	PRINTR	"It's too heavy."
?CCL60:	EQUAL?	PRSA,V?BOARD \?CCL66
	IN?	RAFT,BARGE \?CCL69
	PRINTI	"Hrumph! There's no reason to board the raft inside the barge! "
	ICALL	PERFORM,V?SINK,BARGE
	RTRUE	
?CCL69:	IN?	RAFT,ODD-MACHINE \?CCL71
	CALL	DO-FIRST,STR?316,ODD-MACHINE
	RSTACK	
?CCL71:	CALL	ULTIMATELY-IN?,RAFT,MALE-GORILLA
	ZERO?	STACK \?CTR72
	CALL	ULTIMATELY-IN?,RAFT,FEMALE-GORILLA
	ZERO?	STACK /?CCL73
?CTR72:	CALL2	NOT-ON-GROUND,RAFT
	RSTACK	
?CCL73:	ZERO?	RAFT-HELD \?PRD79
	IN?	RAFT,CANAL \FALSE
?PRD79:	IN?	PROTAGONIST,RAFT /FALSE
	ICALL	QUEUE,I-CANAL,-1
	ICALL1	SET-RAFT-LOC
	EQUAL?	HERE,MY-KIND-OF-DOCK \?CCL84
	SET	'NEARER-DOCK,MY-KIND-OF-DOCK
	JUMP	?CND82
?CCL84:	SET	'NEARER-DOCK,ABANDONED-DOCK
?CND82:	GRTR?	BARGE-LOC-NUM,RAFT-LOC-NUM \?CND85
	IN?	BARGE,CANAL \?CND85
	SET	'BARGE-LOC-NUM,36
	MOVE	BARGE,ICY-DOCK
?CND85:	PRINTI	"As you"
	ICALL2	AND-SIDEKICK,RAFT
	PRINTI	" board the raft, "
	EQUAL?	HERE,CANAL \?CCL91
	PRINTI	"it begins drifting away from the barge"
	ZERO?	BARGE-UNDER-POWER /?CND89
	ICALL1	BARGE-FORGES-AHEAD
	JUMP	?CND89
?CCL91:	PRINTI	"the current sweeps it away from the dock"
?CND89:	PRINT	PERIOD-CR
	ZERO?	BARGE-WAIT /?CCL96
	EQUAL?	RAFT-LOC-NUM,BARGE-LOC-NUM \?CCL96
	SET	'RAFT-WAIT,TRUE-VALUE
	JUMP	?CND94
?CCL96:	SET	'RAFT-WAIT,FALSE-VALUE
?CND94:	SET	'RAFT-HELD,FALSE-VALUE
	MOVE	RAFT,CANAL
	EQUAL?	HERE,CANAL \?CCL101
	MOVE	PROTAGONIST,RAFT
	SET	'OHERE,FALSE-VALUE
	RETURN	OHERE
?CCL101:	CRLF	
	CALL2	GOTO,RAFT
	RSTACK	
?CCL66:	EQUAL?	PRSA,V?STAND-ON \?CCL103
	ICALL	PERFORM,V?BOARD,RAFT
	RTRUE	
?CCL103:	EQUAL?	PRSA,V?KILL,V?MUNG,V?DEFLATE \?CCL105
	FSET?	RAFT,MUNGBIT \?CCL108
	PRINT	ALREADY-IS
	RTRUE	
?CCL108:	PRINTI	"""Phssss."""
	ZERO?	RAFT-HELD \?CTR110
	IN?	RAFT,CANAL \?CCL111
?CTR110:	PRINTI	" The raft sinks"
	IN?	PROTAGONIST,RAFT \?CCL116
	CALL2	JIGS-UP,STR?317
	RSTACK	
?CCL116:	SET	'RAFT-HELD,FALSE-VALUE
	REMOVE	RAFT
	PRINT	PERIOD-CR
	RTRUE	
?CCL111:	FSET	RAFT,MUNGBIT
	PUTP	RAFT,P?SDESC,STR?318
	CRLF	
	RTRUE	
?CCL105:	EQUAL?	PRSA,V?INFLATE \?CCL118
	FSET?	RAFT,MUNGBIT \?CCL121
	PRINTR	"Without a pump? Forget it."
?CCL121:	PRINT	ALREADY-IS
	RTRUE	
?CCL118:	EQUAL?	PRSA,V?SHAKE \?CCL123
	EQUAL?	HERE,CANAL \?CCL123
	IN?	PROTAGONIST,RAFT \?CCL123
	CALL1	SHAKE-BOAT
	RSTACK	
?CCL123:	EQUAL?	PRSA,V?PUSH-DIR \?CCL128
	EQUAL?	PRSI,INTDIR \?CCL128
	IN?	PROTAGONIST,RAFT \?CCL133
	EQUAL?	P-PRSA-WORD,W?MOVE /?CCL133
	PRINTR	"You're in it!"
?CCL133:	IN?	RAFT,CANAL \?CCL137
	PRINT	NO-STEERING
	RTRUE	
?CCL137:	ICALL2	DO-WALK,P-DIRECTION
	MOVE	RAFT,HERE
	RTRUE	
?CCL128:	EQUAL?	PRSA,V?SET \?CCL139
	IN?	RAFT,CANAL \?CCL139
	PRINT	NO-STEERING
	RTRUE	
?CCL139:	EQUAL?	PRSA,V?LAND \FALSE
	PRINTR	"Try grabbing a dock."


	.FUNCT	I-BEETLES
	CALL1	IN-CATACOMBS
	ZERO?	STACK /FALSE
	ICALL	QUEUE,I-BEETLES,6
	IN?	PROTAGONIST,HERE \?CCL5
	RANDOM	CATACOMBS-LOC >CATACOMBS-LOC
	IN?	SIDEKICK,HERE \?CND6
	MOVE	SIDEKICK,CATACOMBS
?CND6:	MOVE	PROTAGONIST,CATACOMBS
	SET	'OHERE,FALSE-VALUE
	SET	'HERE,CATACOMBS
	FSET	CATACOMBS,MUNGBIT
	ICALL1	OPEN-EYES-AND-REMOVE-HANDS
	PRINTR	"   Suddenly the water explodes with life! A swarm of the nastiest beetles this side of Pluto starts munching your flesh. You escape by running blindly through the catacombs, completely losing track of your location."
?CCL5:	CALL2	HARMLESS-SNAP,STR?319
	RSTACK	


	.FUNCT	I-CRABS,OBJ
	CALL1	IN-CATACOMBS
	ZERO?	STACK /FALSE
	ICALL	QUEUE,I-CRABS,10
	IN?	PROTAGONIST,HERE \?CCL5
	ICALL1	OPEN-EYES-AND-REMOVE-HANDS
	FSET	CATACOMBS,MUNGBIT
	PRINTI	"   You feel an intense pain, like a tuft of hair being yanked out -- except that it's coming from your feet, and in about a hundred places. As you flail at the pack of Martian sand crabs, the splashing startles them away"
	FIRST?	PROTAGONIST >OBJ \?CCL8
	EQUAL?	OBJ,GARMENT,COMIC-BOOK /?CCL8
	EQUAL?	OBJ,TORCH \?CND11
	NEXT?	TORCH \?CND11
	NEXT?	TORCH >OBJ /?CND11
?CND11:	PRINTI	", but during the struggle you seem to have lost your "
	ICALL2	DPRINT,OBJ
	PRINT	PERIOD-CR
	REMOVE	OBJ
	CALL1	NOW-DARK?
	RSTACK	
?CCL8:	PRINT	PERIOD-CR
	RTRUE	
?CCL5:	CALL2	HARMLESS-SNAP,STR?320
	RSTACK	


	.FUNCT	I-GATOR
	CALL1	IN-CATACOMBS
	ZERO?	STACK /FALSE
	IN?	PROTAGONIST,HERE \?CCL5
	CALL2	JIGS-UP,STR?321
	RSTACK	
?CCL5:	ICALL	QUEUE,I-GATOR,12
	CALL2	HARMLESS-SNAP,STR?322
	RSTACK	


	.FUNCT	HARMLESS-SNAP,STRING
	PRINTI	"   The calm water is suddenly shattered by the jaws of a huge Martian "
	PRINT	STRING
	PRINTR	" snapping harmlessly toward you. Good thing you were in the raft."


	.FUNCT	MARTIAN-DESSERT-EXIT-F
	FSET?	MARTIAN-DESSERT,MUNGBIT /?CND1
	FSET	MARTIAN-DESSERT,MUNGBIT
	PRINTI	"I guess the paths aren't a mirage..."
	CRLF	
	CRLF	
?CND1:	EQUAL?	PRSO,P?NW \?CCL5
	RETURN	RUINED-CASTLE-2
?CCL5:	RETURN	OASIS


	.FUNCT	WATTZ-UPP-DOCK-ENTER-F
	PUTP	HOLE,P?SDESC,STR?134
	RETURN	WATTZ-UPP-DOCK


	.FUNCT	MARTIAN-DESSERT-ENTER-F
	PUTP	HOLE,P?SDESC,STR?134
	RETURN	MARTIAN-DESSERT


	.FUNCT	CIRCLE-ISNT-BLACK
	ZERO?	CIRCLE-BLACK \FALSE
	EQUAL?	HERE,OASIS /TRUE
	RFALSE	


	.FUNCT	OASIS-F,RARG
	EQUAL?	RARG,M-ENTER \?CCL3
	ZERO?	CIRCLE-BLACK \?CCL3
	PUTP	HOLE,P?SDESC,STR?325
	RTRUE	
?CCL3:	EQUAL?	RARG,M-LOOK \?CCL7
	PRINTI	"This is a remarkable sight on arid Mars -- subsurface water bubbling up in a fountain, flowing around"
	ICALL2	APRINT,HOLE
	PRINTI	", and soaking into the thirsty sand. A path curves east around the "
	PRINTD	DUNES
	CALL2	UNCHARTABLE-DESERT,STR?260
	RSTACK	
?CCL7:	EQUAL?	RARG,M-END \FALSE
	ZERO?	SIDEKICK-DROWNED /?CND10
	MOVE	SIDEKICK,HERE
	SET	'SIDEKICK-DROWNED,FALSE-VALUE
	PRINTI	"   Like a wet watermelon seed being squirted from between two fingers, "
	ICALL1	DPRINT-SIDEKICK
	PRINTI	" is ejected from the fountain and lands in a dripping heap at your feet. ""Good thing I'm so good at holding my breath,"" "
	ICALL1	HE-SHE
	PRINTI	" says."
	CRLF	
?CND10:	ZERO?	CIRCLE-FADED \FALSE
	SET	'CIRCLE-FADED,TRUE-VALUE
	SET	'CIRCLE-BLACK,FALSE-VALUE
	PUTP	HOLE,P?SDESC,STR?325
	PRINTR	"   Inexplicably, the circle fades before your very eyes, slowly going from black to white."


	.FUNCT	ICY-DOCK-F,RARG
	EQUAL?	RARG,M-ENTER \?CCL3
	FSET?	ICY-DOCK,TOUCHBIT /?CCL3
	CALL2	RUNNING?,I-ION-DEATH
	ZERO?	STACK \?CCL3
	CALL	INCREMENT-SCORE,4,14
	RSTACK	
?CCL3:	EQUAL?	RARG,M-END \FALSE
	IN?	SIDEKICK,HERE \FALSE
	SET	'FOLLOW-FLAG,3
	ICALL	QUEUE,I-FOLLOW,2
	REMOVE	SIDEKICK
	SET	'SIDEKICK-DROWNED,TRUE-VALUE
	PRINTI	"   With a whoop of surprise, "
	ICALL1	DPRINT-SIDEKICK
	PRINTI	" loses "
	ICALL1	HIS-HER
	PRINTI	" footing on the ice, skids right into the canal, and is immediately dragged under by the strong current produced by the underwater teleporters. You search frantically for any sign of "
	ICALL1	HIM-HER
	PRINTI	", but after several agonizingly long minutes you abandon all hope. As you gaze across "
	ICALL1	DPRINT-SIDEKICK
	PRINTI	"'s watery grave"
	CALL1	MEMORIAM
	RSTACK	


	.FUNCT	TUNDRA-F,RARG
	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"This snowy plain is barren of all signs of life. Drifts block travel in all directions but north, south and southeast. It's pretty cold, but nothing a tough g"
	ZERO?	MALE /?CCL6
	PRINTI	"uy"
	JUMP	?CND4
?CCL6:	PRINTI	"al"
?CND4:	PRINTI	" like yourself can't stand."
	RTRUE	


	.FUNCT	PENGUIN-PARK-F,RARG
	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"Even on Mars, one could hardly expect a polar visit without seeing penguins. Well, here they are! A whole waddling mass of them, "
	ZERO?	PENGUINS-PARTED /?CCL6
	PRINTI	"standing politely on either side of"
	JUMP	?CND4
?CCL6:	PRINTI	"a pack so dense they completely block"
?CND4:	PRINTI	" the path to the southeast. Other paths lead west and northwest."
	ZERO?	PENGUINS-PARTED \TRUE
	CRLF	
	PRINTI	"   One penguin teasingly waves a sign in your direction, much like a matador waving his cape toward a bull."
	RTRUE	


	.FUNCT	PENGUINS-F
	EQUAL?	PRSA,V?GIVE \?CCL3
	EQUAL?	PRSO,TEN-MARSMID-COIN \?CCL6
	SET	'PENGUINS-PARTED,TRUE-VALUE
	REMOVE	TEN-MARSMID-COIN
	MOVE	ONE-MARSMID-COIN,PROTAGONIST
	PRINTR	"The penguins, satisfied by your donation to the PRF, part ranks for you to pass. The going rate for donations to the fund must be nine marsmids, since one of the penguins hands you a one marsmid coin."
?CCL6:	EQUAL?	PRSO,ONE-MARSMID-COIN \FALSE
	PRINTR	"Nine marsmids is the minimum contribution to the PRF."
?CCL3:	EQUAL?	PRSA,V?SHOW \FALSE
	EQUAL?	PRSO,TEN-MARSMID-COIN \FALSE
	PRINTR	"The penguins wiggle eagerly."


	.FUNCT	GYPSY-CAMP-F,RARG
	EQUAL?	RARG,M-END \FALSE
	ZERO?	PARENTS-KILLED \?CND4
	SET	'PARENTS-KILLED,TRUE-VALUE
	ZERO?	VERBOSITY /TRUE
	PRINTI	"   A male and a female robot emerge from the tent, waving in a gesture of gypsyish greeting. ""Hello, weary traveller"
	IN?	SIDEKICK,HERE \?CND8
	PRINTC	115
?CND8:	PRINTI	"! We are but poor gypsies, but we invite you to spend the night in our humble tent and share our simple but delicious oil and silicon stew."" Suddenly, in an event so shocking that even a hardened space opera hero"
	ZERO?	MALE \?CND10
	PRINTI	"ine"
?CND10:	PRINTI	" like yourself is stunned beyond belief, a meteorite shrieks through the atmosphere and completely obliterates the two robots."
	CRLF	
?CND4:	IN?	BABY,TENT \FALSE
	IN?	BLANKET,BABY /FALSE
	PRINTR	"   You hear the sound of high-pitched crying, slightly muffled, coming from inside the tent."


	.FUNCT	OUTSIDE-TENT-F
	EQUAL?	PRSA,V?WALK-TO,V?BOARD,V?ENTER \?CCL3
	CALL2	DO-WALK,P?NORTH
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?DISEMBARK,V?LEAVE,V?EXIT \?CCL5
	PRINT	LOOK-AROUND
	RTRUE	
?CCL5:	EQUAL?	PRSA,V?LOOK-INSIDE \FALSE
	PRINT	CANT-FROM-HERE
	RTRUE	


	.FUNCT	INSIDE-TENT-F
	EQUAL?	PRSA,V?DISEMBARK,V?LEAVE,V?EXIT \?CCL3
	CALL2	DO-WALK,P?SOUTH
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?WALK-TO,V?BOARD,V?ENTER \?CCL5
	PRINT	LOOK-AROUND
	RTRUE	
?CCL5:	EQUAL?	PRSA,V?LOOK-INSIDE,V?EXAMINE \?CCL7
	CALL1	V-LOOK
	RSTACK	
?CCL7:	EQUAL?	PRSA,V?SEARCH \FALSE
	PRINT	NOTHING-NEW
	RTRUE	


	.FUNCT	TENT-F,RARG
	EQUAL?	RARG,M-ENTER \FALSE
	CALL	QUEUE,I-CRY,-1
	RSTACK	


	.FUNCT	I-CRY
	IN?	BLANKET,BABY \?CCL3
	ICALL2	DEQUEUE,I-CRY
	RFALSE	
?CCL3:	CALL2	VISIBLE?,BABY
	ZERO?	STACK /FALSE
	PRINTI	"   The baby continues to wail at the top of its lungs."
	RANDOM	100
	LESS?	12,STACK /?CND6
	PRINTR	" It's amazing that such small lungs have such a high top."
?CND6:	CRLF	
	RTRUE	


	.FUNCT	BABY-F,OARG
	ZERO?	OARG /?CCL3
	FSET?	BABY,TOUCHBIT /FALSE
	EQUAL?	OARG,M-OBJDESC? /TRUE
	PRINTI	"   A little baby robot is shivering in the corner. It stops crying long enough to open a tiny metal eyelid and look at you. """
	ZERO?	MALE /?CCL11
	PRINTI	"Momm"
	JUMP	?CND9
?CCL11:	PRINTI	"Dadd"
?CND9:	PRINTI	"y?"" it says, in a quavering, high-pitched, metallic voice."
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?TELL \?CCL13
	IN?	BLANKET,BABY \?CCL16
	SET	'WINNER,PROTAGONIST
	ICALL	PERFORM,V?KISS,BABY
	JUMP	?CND14
?CCL16:	PRINTI	"""Goo goo ga ga buzz whirr click."""
	CRLF	
?CND14:	CALL1	STOP
	RSTACK	
?CCL13:	EQUAL?	PRSA,V?PUT \?PRD20
	EQUAL?	PRSI,BLANKET /?CTR17
?PRD20:	EQUAL?	PRSA,V?WRAP,V?PUT-ON \?PRD23
	EQUAL?	PRSO,BLANKET /?CTR17
?PRD23:	EQUAL?	PRSA,V?PUT \?CCL18
	EQUAL?	PRSI,BASKET \?CCL18
	IN?	BLANKET,BASKET \?CCL18
?CTR17:	FSET?	BLANKET,UNTEEDBIT /FALSE
	IN?	BLANKET,BABY \?CND29
	PRINT	SENILITY-STRIKES
	RTRUE	
?CND29:	FSET	BABY,TOUCHBIT
	FSET	BLANKET,NDESCBIT
	MOVE	BLANKET,BABY
	EQUAL?	PRSI,BASKET \?CND33
	MOVE	BABY,BASKET
?CND33:	PUTP	BABY,P?SDESC,STR?334
	ICALL2	DEQUEUE,I-CRY
	PRINTR	"The baby stops crying and, in the comfy warmth of the blanket, slips into a calm sleep. A peaceful smile creeps over its face."
?CCL18:	EQUAL?	PRSA,V?PUT \?PRD38
	EQUAL?	PRSI,SHEET /?CTR35
?PRD38:	EQUAL?	PRSA,V?WRAP,V?PUT-ON \?CCL36
	EQUAL?	PRSO,SHEET \?CCL36
?CTR35:	IN?	BLANKET,BABY /?CTR44
	FSET?	SHEET,MUNGBIT /?CTR44
	FSET?	SHEET,PLURALBIT \?CCL45
?CTR44:	CALL1	WASTES
	RSTACK	
?CCL45:	PRINTR	"The sheet provides little warmth."
?CCL36:	EQUAL?	PRSA,V?PUT \?CCL50
	EQUAL?	PRSI,BASKET \?CCL50
	IN?	BASKET,FRONT-STOOP \?CCL50
	FIRST?	BASKET /?CCL50
	IN?	BLANKET,BABY \?CCL57
	MOVE	BABY,BASKET
	CALL2	ABANDON-BABY,STR?335
	RSTACK	
?CCL57:	CALL1	CRYING-ALERTS-MATRON
	RSTACK	
?CCL50:	EQUAL?	PRSA,V?REMOVE \?CCL59
	IN?	BLANKET,BABY \?CCL59
	MOVE	BLANKET,PROTAGONIST
	FCLEAR	BLANKET,NDESCBIT
	PUTP	BABY,P?SDESC,STR?333
	ICALL	QUEUE,I-CRY,-1
	PRINTI	"The baby robo"
	PRINT	TWICE-AS-LOUD
	CALL	ULTIMATELY-IN?,BABY,FRONT-STOOP
	ZERO?	STACK /TRUE
	PRINTI	"   "
	ICALL1	CRYING-ALERTS-MATRON
	RTRUE	
?CCL59:	EQUAL?	PRSA,V?KISS \?CCL65
	IN?	BLANKET,BABY \?CCL68
	ICALL	PERFORM,V?ALARM,BABY
	RTRUE	
?CCL68:	PRINTI	"The "
	ICALL2	DPRINT,BABY
	PRINTI	" reacts as a human baby would react if kissed by a giant walking metal machine. In other words, i"
	PRINT	TWICE-AS-LOUD
	RTRUE	
?CCL65:	EQUAL?	PRSA,V?LISTEN \?CCL70
	IN?	BLANKET,BABY /?CCL70
	PRINTR	"""Waaaa!"""
?CCL70:	EQUAL?	PRSA,V?SHAKE \?CCL74
	IN?	BLANKET,BABY \?CCL77
	PRINTR	"The baby's asleep!"
?CCL77:	PRINTI	"This upsets the "
	ICALL2	DPRINT,BABY
	PRINTI	"'s equilibrium mechanism. I"
	PRINT	TWICE-AS-LOUD
	RTRUE	
?CCL74:	EQUAL?	PRSA,V?ALARM \?CCL79
	IN?	BLANKET,BABY \?CCL79
	PRINTR	"The baby whimpers briefly, but the warm coziness of the blanket soon lulls it back to sleep."
?CCL79:	CALL2	TAKE-BABY-FROM-STOOP,BABY
	ZERO?	STACK \TRUE
	EQUAL?	PRSA,V?SUCKLE \?CCL85
	ZERO?	MALE /?CCL88
	PRINTR	"You're a male, remember? You obviously have a poor mammary."
?CCL88:	PRINTR	"How touching that the baby robot has stirred your maternal instinct. Unfortunately, your mammaries won't produce #3 machine oil."
?CCL85:	EQUAL?	PRSA,V?PUT-NEAR,V?PUT \?CCL90
	EQUAL?	PRSI,ORPHANAGE-DOOR \?CCL90
	ICALL	PERFORM,V?PUT-ON,BABY,FRONT-STOOP
	RTRUE	
?CCL90:	EQUAL?	PRSA,V?EXAMINE \?CCL94
	PRINTI	"The "
	ICALL2	DPRINT,BABY
	PRINTI	" is "
	IN?	BLANKET,BABY \?CCL97
	PRINTI	"sleep"
	JUMP	?CND95
?CCL97:	PRINTI	"cry"
?CND95:	PRINTR	"ing."
?CCL94:	EQUAL?	PRSA,V?CLOSE,V?OPEN \FALSE
	PRINT	HUH
	RTRUE	


	.FUNCT	CRYING-ALERTS-MATRON
	PRINTI	"The baby's crying alerts someone within the igloo. "
	CALL2	SHOO,STR?336
	RSTACK	


	.FUNCT	SHOO,STRING
	ICALL2	DEQUEUE,I-ORPHANAGE
	PRINT	MATRON-DESC
	PRINTI	"appears. ""Caught you, you baby-"
	PRINT	STRING
	PRINTI	"ing gypsy!"" she cries, in a voice that, in a more mountainous region, could probably initiate an avalanche. ""Begone!"" She "
	CALL	ULTIMATELY-IN?,BABY,FRONT-STOOP
	ZERO?	STACK /?CND1
	PRINTI	"thrusts the babe into your arms and "
?CND1:	IN?	BASKET,FRONT-STOOP \?CND3
	MOVE	BASKET,PROTAGONIST
?CND3:	CALL	ULTIMATELY-IN?,BABY,FRONT-STOOP
	ZERO?	STACK /?CND5
	MOVE	BABY,PROTAGONIST
?CND5:	PRINTI	"drives you away with blows that would fell an elephant."
	CRLF	
	CRLF	
	EQUAL?	HERE,ORPHANAGE-FOYER \?CCL9
	CALL2	GOTO,SOUTH-POLE
	RSTACK	
?CCL9:	CALL2	GOTO,GYPSY-CAMP
	RSTACK	


	.FUNCT	SOUTH-POLE-F,RARG
	EQUAL?	RARG,M-ENTER \FALSE
	ZERO?	COTTON-BALLS-SEEN /FALSE
	FSET?	COTTON-BALLS,TRYTAKEBIT \FALSE
	MOVE	COTTON-BALLS,HERE
	FSET	COTTON-BALLS,NDESCBIT
	RTRUE	


	.FUNCT	ORPHANAGE-DOOR-F
	EQUAL?	PRSA,V?KNOCK \FALSE
	EQUAL?	HERE,SOUTH-POLE \FALSE
	CALL2	VISIBLE?,BABY
	ZERO?	STACK /?CCL8
	CALL2	SHOO,STR?336
	RSTACK	
?CCL8:	CALL2	SHOO,STR?341
	RSTACK	


	.FUNCT	FRONT-STOOP-F
	EQUAL?	PRSA,V?PUT-NEAR,V?PUT-ON,V?PUT \?CCL3
	EQUAL?	PRSO,BABY \?CCL6
	IN?	BABY,BASKET /?CCL6
	IN?	BLANKET,BABY \?CND9
	ICALL1	COLD-CAUSES-CRYING
?CND9:	MOVE	PRSO,FRONT-STOOP
	CALL1	CRYING-ALERTS-MATRON
	RSTACK	
?CCL6:	EQUAL?	PRSO,BABY,BASKET \FALSE
	IN?	BABY,BASKET \FALSE
	IN?	BLANKET,BABY /?CCL17
	CALL1	CRYING-ALERTS-MATRON
	RSTACK	
?CCL17:	MOVE	BASKET,FRONT-STOOP
	CALL2	ABANDON-BABY,STR?342
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?STAND-ON,V?ENTER,V?BOARD \?CCL19
	CALL1	WASTES
	RSTACK	
?CCL19:	EQUAL?	PRSA,V?PUT \FALSE
	EQUAL?	PRSO,BABY \FALSE
	ICALL1	COLD-CAUSES-CRYING
	CALL1	CRYING-ALERTS-MATRON
	RSTACK	


	.FUNCT	COLD-CAUSES-CRYING
	PRINTI	"As you place the baby on the cold doorstep, i"
	PRINT	TWICE-AS-LOUD
	PRINTI	"   "
	RTRUE	


	.FUNCT	ABANDON-BABY,STRING
	ICALL	QUEUE,I-ORPHANAGE,5
	MOVE	PROTAGONIST,HERE
	SET	'OHERE,FALSE-VALUE
	PRINTI	"You place the baby gently "
	PRINT	STRING
	PRINTR	" and sneak behind a nearby snowdrift."


	.FUNCT	I-ORPHANAGE
	REMOVE	BABY
	REMOVE	BASKET
	FCLEAR	ORPHANAGE-DOOR,LOCKEDBIT
	EQUAL?	HERE,SOUTH-POLE \FALSE
	SET	'FOLLOW-FLAG,15
	ICALL	QUEUE,I-FOLLOW,2
	PRINTI	"   "
	PRINT	MATRON-DESC
	PRINTI	"opens the "
	PRINTD	ORPHANAGE-DOOR
	PRINTR	". She coos over the baby for a moment then carries it inside, closing the door behind her."


	.FUNCT	ORPHANAGE-FOYER-F,RARG
	EQUAL?	RARG,M-ENTER \?CCL3
	FSET?	COTTON-BALLS,TRYTAKEBIT \?CND4
	MOVE	COTTON-BALLS,HERE
	FCLEAR	COTTON-BALLS,NDESCBIT
?CND4:	CALL2	QUEUED?,I-ORPHANAGE-BOOT
	ZERO?	STACK \FALSE
	CALL	QUEUE,I-ORPHANAGE-BOOT,5
	RSTACK	
?CCL3:	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"The igloo's front hall has rooms to the northeast and northwest. A barred window is next to the "
	ICALL2	OPEN-CLOSED,ORPHANAGE-DOOR
	PRINTI	" door to the south."
	RTRUE	


	.FUNCT	IGLOO-ENTER-F
	PRINTI	"Nursery"
	CRLF	
	ICALL1	I-ORPHANAGE-BOOT
	ICALL2	DEQUEUE,I-ORPHANAGE-BOOT
	RFALSE	


	.FUNCT	I-ORPHANAGE-BOOT
	EQUAL?	HERE,ORPHANAGE-FOYER \?CCL3
	PRINTI	"   "
	ICALL2	SHOO,STR?341
	FCLEAR	ORPHANAGE-DOOR,OPENBIT
	FSET	ORPHANAGE-DOOR,LOCKEDBIT
	RTRUE	
?CCL3:	EQUAL?	HERE,SOUTH-POLE \?CCL5
	FSET?	ORPHANAGE-DOOR,OPENBIT \?CCL5
	PRINTI	"   The "
	PRINTD	ORPHANAGE-DOOR
	PRINTI	" slams shut."
	CRLF	
	FCLEAR	ORPHANAGE-DOOR,OPENBIT
	FSET	ORPHANAGE-DOOR,LOCKEDBIT
	RTRUE	
?CCL5:	FCLEAR	ORPHANAGE-DOOR,OPENBIT
	FSET	ORPHANAGE-DOOR,LOCKEDBIT
	RFALSE	


	.FUNCT	COTTON-BALLS-F
	EQUAL?	HERE,SOUTH-POLE \?CCL3
	FSET?	COTTON-BALLS,TRYTAKEBIT \?CCL3
	CALL2	TOUCHING?,COTTON-BALLS
	ZERO?	STACK /?CCL3
	CALL2	CANT-REACH,COTTON-BALLS
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?TAKE \?CCL8
	FSET?	COTTON-BALLS,TRYTAKEBIT \?CCL8
	ICALL	INCREMENT-SCORE,16,29,TRUE-VALUE
	FCLEAR	COTTON-BALLS,TRYTAKEBIT
	RFALSE	
?CCL8:	FSET?	COTTON-BALLS,UNTEEDBIT \?CCL12
	EQUAL?	PRSA,V?EXAMINE \FALSE
	PRINTR	"Let's just say that some poor male raccoon is speaking in a particularly high-pitched voice."
?CCL12:	EQUAL?	PRSA,V?PUT-ON,V?PUT \?CCL17
	EQUAL?	PRSI,EARS \?CCL17
	ZERO?	GONE-APE /?CCL22
	PRINT	DEXTERITY
	RTRUE	
?CCL22:	FSET	COTTON-BALLS,WORNBIT
	FSET	EARS,MUNGBIT
	MOVE	COTTON-BALLS,PROTAGONIST
	PRINT	MUFFLED
	PRINTI	" have "
	ICALL2	DPRINT,COTTON-BALLS
	PRINTI	" stuffed in "
	PRINTD	EARS
	PRINT	PERIOD-CR
	RTRUE	
?CCL17:	EQUAL?	PRSA,V?DISEMBARK,V?REMOVE \?CCL24
	FSET?	COTTON-BALLS,WORNBIT \?CCL24
	ZERO?	GONE-APE /?CND27
	ICALL	PERFORM,V?TAKE,COTTON-BALLS
	RTRUE	
?CND27:	ICALL1	OPEN-EYES-AND-REMOVE-HANDS
	FCLEAR	COTTON-BALLS,WORNBIT
	CALL2	SENSE-AGAIN,EARS
	RSTACK	
?CCL24:	EQUAL?	PRSA,V?PUT \FALSE
	EQUAL?	PRSI,NOSE \FALSE
	PRINTI	"The "
	PRINTD	COTTON-BALLS
	PRINTR	" is too itchy."


	.FUNCT	IGLOO-F
	EQUAL?	PRSA,V?BOARD,V?WALK-TO,V?ENTER \?CCL3
	EQUAL?	HERE,ORPHANAGE-FOYER \?CCL6
	PRINT	LOOK-AROUND
	RTRUE	
?CCL6:	EQUAL?	HERE,SOUTH-POLE \FALSE
	CALL2	DO-WALK,P?IN
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?DISEMBARK,V?EXIT,V?LEAVE \?CCL10
	EQUAL?	HERE,SOUTH-POLE \?CCL13
	PRINT	LOOK-AROUND
	RTRUE	
?CCL13:	CALL2	DO-WALK,P?OUT
	RSTACK	
?CCL10:	EQUAL?	PRSA,V?LOOK-INSIDE \?CCL15
	EQUAL?	HERE,SOUTH-POLE \?CCL18
	ICALL2	PERFORM-PRSA,WINDOW
	RTRUE	
?CCL18:	CALL1	V-LOOK
	RSTACK	
?CCL15:	EQUAL?	PRSA,V?SEARCH \FALSE
	PRINT	NOTHING-NEW
	RTRUE	

	.ENDI
