

	.FUNCT	VENUS-F
	EQUAL?	PRSA,V?EXAMINE \?CCL3
	CALL1	V-LOOK
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?EXIT,V?DISEMBARK,V?LEAVE \FALSE
	PRINTR	"How?"


	.FUNCT	JUNGLE-F,RARG
	EQUAL?	RARG,M-ENTER \?CCL3
	IN?	FLYTRAP,HERE \?CCL3
	CALL	QUEUE,I-FLYTRAP,-1
	RSTACK	
?CCL3:	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"You are surrounded by hot, steamy, primitive rain forest. Judging by the overpowering heat, the excessive humidity, and "
	IN?	FLYTRAP,HERE \?CCL10
	PRINTI	"especially by the gigantic "
	PRINTD	FLYTRAP
	PRINTI	" sidling your way, "
	JUMP	?CND8
?CCL10:	PRINTI	"the odd flora, "
?CND8:	PRINTI	"you must be in the death-clogged jungles of Venus.
   A path runs east-west through the jungle"
	IN?	FLYTRAP,HERE \?CND11
	PRINTI	", but don't even think about going west unless you love wading into four tons of "
	ZERO?	MALE \?CND13
	PRINTI	"wo"
?CND13:	PRINTI	"man-eating lettuce"
?CND11:	PRINTC	46
	RTRUE	


	.FUNCT	PASS-FLYTRAP-F
	IN?	FLYTRAP,HERE \?CCL3
	PRINTI	"Despite being warned, you walk right into the orifice of the "
	PRINTD	FLYTRAP
	PRINTI	". "
	CALL1	FLYTRAP-DEATH
	RSTACK	
?CCL3:	EQUAL?	HERE,JUNGLE \?CCL5
	RETURN	SPAWNING-GROUND
?CCL5:	RETURN	JUNGLE


	.FUNCT	FLYTRAP-DEATH
	PRINTI	"A little known fact about "
	PRINTD	FLYTRAP
	PRINTI	"s: they secrete an enzyme which stimulates the pleasure centers of their victim. Hence, you experience "
	ZERO?	NAUGHTY-LEVEL \?CCL3
	PRINTI	"a feeling similar to eating a really good hot fudge sundae"
	JUMP	?CND1
?CCL3:	PRINTI	"multiple orgasms"
?CND1:	CALL2	JIGS-UP,STR?344
	RSTACK	


	.FUNCT	FLYTRAP-F
	EQUAL?	PRSA,V?EXAMINE \?CCL3
	PRINTI	"It looks just like the Terrestrial variety -- except that "
	PRINTD	FLYTRAP
	PRINTI	"s on Earth"
	PRINT	EVOLVED
	PRINTI	"n ounce, and Venusian "
	PRINTD	FLYTRAP
	PRINTC	115
	PRINT	EVOLVED
	PRINTI	" ton. Oh, one other thing. Terrestrial "
	PRINTD	FLYTRAP
	PRINTR	"s don't usually stalk their prey."
?CCL3:	EQUAL?	PRSA,V?FOLLOW \?CCL5
	EQUAL?	FOLLOW-FLAG,9 \?CCL8
	CALL2	DO-WALK,P?WEST
	RSTACK	
?CCL8:	EQUAL?	FOLLOW-FLAG,10 \?CCL10
	ICALL	PERFORM,V?DISEMBARK,TREE-HOLE
	RTRUE	
?CCL10:	EQUAL?	FOLLOW-FLAG,11 \FALSE
	ICALL	PERFORM,V?ENTER,TREE-HOLE
	RTRUE	
?CCL5:	CALL2	TOUCHING?,FLYTRAP
	ZERO?	STACK /FALSE
	PRINTR	"You don't want to get that close to the flytrap -- and it has nothing to do with its breath."


	.FUNCT	I-FLYTRAP
	INC	'FLYTRAP-COUNTER
	PRINTI	"   "
	IN?	FLYTRAP,HERE /?CCL3
	SET	'FLYTRAP-COUNTER,0
	EQUAL?	HERE,CLEARING \?CCL6
	ZERO?	LEAVES-PLACED /?CCL9
	ZERO?	TOO-LATE \?CCL9
	ICALL1	TRAP-FLYTRAP
	PRINTI	"You hear a crash from the west"
	JUMP	?CND7
?CCL9:	MOVE	FLYTRAP,JUNGLE
	SET	'TOO-LATE,FALSE-VALUE
	ICALL2	DEQUEUE,I-FLYTRAP
	SET	'FOLLOW-FLAG,9
	ICALL	QUEUE,I-FOLLOW,2
	PRINTI	"Holy tropism! The "
	PRINTD	FLYTRAP
	PRINTI	" loses interest in you and crawls away"
?CND7:	PRINT	PERIOD-CR
	RTRUE	
?CCL6:	MOVE	FLYTRAP,HERE
	ZERO?	LEAVES-PLACED \?CND12
	SET	'TOO-LATE,TRUE-VALUE
?CND12:	PRINTI	"As"
	ICALL2	TPRINT,FLYTRAP
	PRINTR	" scurries along, you dash to the eastern side of the hole in order to be as far from it as possible."
?CCL3:	IN?	PROTAGONIST,TREE-HOLE \?CCL15
	MOVE	FLYTRAP,JUNGLE
	SET	'FOLLOW-FLAG,10
	ICALL	QUEUE,I-FOLLOW,2
	SET	'TOO-LATE,FALSE-VALUE
	SET	'FLYTRAP-COUNTER,0
	ICALL2	DEQUEUE,I-FLYTRAP
	PRINTI	"The "
	PRINTD	FLYTRAP
	PRINTR	" peers down, decides that it's not worth getting trapped for such a measly scrap of meat, and shuffles away."
?CCL15:	EQUAL?	FLYTRAP-COUNTER,1 \?CCL17
	FSET?	FLYTRAP,TOUCHBIT \?CCL17
	EQUAL?	HERE,JUNGLE \?CCL17
	PRINTI	"Flies must be in short supply, because the "
	PRINTD	FLYTRAP
	PRINTR	" nearby expectantly rustles a few stalks and begins creeping in your direction."
?CCL17:	LESS?	FLYTRAP-COUNTER,4 \?CCL22
	FSET	FLYTRAP,TOUCHBIT
	PRINTI	"The "
	PRINTD	FLYTRAP
	PRINTI	" sidles "
	EQUAL?	HERE,FORK-OF-SORTS \?CCL25
	ZERO?	LEAVES-PLACED /?CTR24
	ZERO?	TOO-LATE /?CCL25
?CTR24:	PRINTR	"around the hole toward you."
?CCL25:	PRINTR	"closer."
?CCL22:	EQUAL?	HERE,FORK-OF-SORTS \?CCL31
	ZERO?	LEAVES-PLACED /?CCL31
	ZERO?	TOO-LATE \?CCL31
	ICALL1	TRAP-FLYTRAP
	PRINTR	"Never before has splintering wood sounded so sweet or tossed salad looked so lovely. The amazing flying flytrap tumbles into your flytrap trap, covered with leaves and bits of shattered trellis, giving the plant the amusing appearance of a tar-and-feather victim."
?CCL31:	CALL1	FLYTRAP-DEATH
	RSTACK	


	.FUNCT	TRAP-FLYTRAP
	FSET	FLYTRAP,MUNGBIT
	ICALL	INCREMENT-SCORE,2,15
	MOVE	FLYTRAP,TREE-HOLE
	SET	'FOLLOW-FLAG,11
	ICALL	QUEUE,I-FOLLOW,2
	ICALL	ROB,TRELLIS,TREE-HOLE
	REMOVE	TRELLIS
	FCLEAR	FLYTRAP,NDESCBIT
	ICALL1	UNDO-TRAP
	CALL2	DEQUEUE,I-FLYTRAP
	RSTACK	


	.FUNCT	SPAWNING-GROUND-F,RARG
	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"As if this hasn't already been a rough enough day, you have stumbled upon a spawning ground for Venusian slime beasts. "
	PRINT	OOZY-WITH-SLIME
	PRINTI	" Fortunately, these beasts are still in the earliest (and least deadly) stage. Only one spot is free of slime:"
	ICALL2	TPRINT,HOLE
	PRINTI	" near the path to the east."
	RTRUE	


	.FUNCT	CREAM-F
	EQUAL?	PRSA,V?LOOK-INSIDE,V?EXAMINE \?CCL3
	CALL1	EXAMINE-CREAM-AND-STAIN
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?READ \?CCL5
	PRINTI	"The jar is marked ""Un"
	FSET?	CREAM,UNTEEDBIT /?CND6
	PRINTC	116
?CND6:	PRINTR	"angling cream."""
?CCL5:	EQUAL?	PRSA,V?EMPTY \?CCL9
	EQUAL?	PRSO,CREAM \?CCL9
	ZERO?	PRSI \?CND12
	PUT	P-NAMW,1,FALSE-VALUE
	SET	'PRSI,GROUND
?CND12:	FSET?	CREAM,MUNGBIT \?CCL16
	PRINT	ALREADY-IS
	RTRUE	
?CCL16:	PUT	P-NAMW,0,W?CREAM
	ICALL	PERFORM,V?PUT-ON,CREAM,PRSI
	RTRUE	
?CCL9:	EQUAL?	PRSA,V?CLOSE,V?OPEN \?CCL18
	CALL1	NO-LID
	RSTACK	
?CCL18:	EQUAL?	PRSA,V?EAT \?CCL20
	PRINT	YECHH
	RTRUE	
?CCL20:	EQUAL?	PRSA,V?RUB,V?PUT-ON,V?POUR \FALSE
	EQUAL?	PRSO,CREAM \FALSE
	GET	P-NAMW,0
	EQUAL?	STACK,W?JAR,FALSE-VALUE /FALSE
	FSET?	CREAM,MUNGBIT \?CND26
	ICALL1	EXAMINE-CREAM-AND-STAIN
	RTRUE	
?CND26:	MOVE	CREAM,PROTAGONIST
	FSET	CREAM,MUNGBIT
	PRINTI	"As the lotion soaks in,"
	FSET?	CREAM,UNTEEDBIT \?CCL30
	EQUAL?	PRSI,THETA \?CCL30
	MOVE	EIGHTY-TWO-DEGREE-ANGLE,THRONE-ROOM
	FCLEAR	THETA,MUNGBIT
	FCLEAR	THETA,NDESCBIT
	FSET	THETA,ACTORBIT
	FSET	THETA,FEMALEBIT
	FSET	THETA,NARTICLEBIT
	PUTP	THETA,P?SDESC,STR?348
	ICALL	INCREMENT-SCORE,16,10,TRUE-VALUE
	PRINTI	" the angle slowly transforms into a beautiful princess. Mitre, gushing tears of happiness, cries, ""You have restored my beloved Theta to me!"" He reveals a perfect "
	ICALL2	DPRINT,EIGHTY-TWO-DEGREE-ANGLE
	PRINTI	". ""I only brushed against it,"" explains the King. ""Please accept it, along with my thanks."" He reaches out to shake "
	PRINTD	HANDS
	PRINT	PERIOD-CR
	RTRUE	
?CCL30:	EQUAL?	PRSI,PILE-OF-ANGLES \?CCL34
	FSET?	CREAM,UNTEEDBIT \?CCL34
	CALL2	JIGS-UP,STR?349
	RSTACK	
?CCL34:	EQUAL?	PRSI,ME \?CCL38
	PRINTR	" your skin tingles a bit."
?CCL38:	ICALL1	TPRINT-PRSI
	PRINTI	" seem"
	FSET?	PRSI,PLURALBIT /?CND39
	PRINTC	115
?CND39:	PRINTI	" unchanged. "
	EQUAL?	PRSI,MITRE \?CCL43
	FSET?	CREAM,UNTEEDBIT \?CCL43
	PRINTR	"(Like fighting a forest fire with a water pistol.)"
?CCL43:	PRINTI	"I guess "
	FSET?	PRSI,PLURALBIT \?CCL48
	PRINTI	"they were"
	JUMP	?CND46
?CCL48:	FSET?	PRSI,FEMALEBIT \?CCL51
	PRINTI	"she"
	JUMP	?CND49
?CCL51:	FSET?	PRSI,ACTORBIT \?CCL53
	PRINTI	"he"
	JUMP	?CND49
?CCL53:	PRINTI	"it"
?CND49:	PRINTI	" was"
?CND46:	PRINTI	"n't very "
	FSET?	CREAM,UNTEEDBIT /?CND54
	PRINTC	116
?CND54:	PRINTR	"angled."


	.FUNCT	FORK-OF-SORTS-F,RARG
	EQUAL?	RARG,M-ENTER \?CCL3
	FSET?	HERE,TOUCHBIT /?CCL3
	ZERO?	VERBOSITY /?CCL3
	PRINTI	"A mighty tree rises before you in the center of the path. Suddenly and without warning (as is the nature of the jungle) it dies. Within seconds, the tree is consumed by Venusian hypertermites, which then move off in search of other dead trees, leaving a massive hole in the ground."
	CRLF	
	CRLF	
	RTRUE	
?CCL3:	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"This jungle path once split here, went around a mighty tree, and rejoined off to the east. Now, it splits here, goes around a "
	ZERO?	LEAVES-PLACED /?CCL11
	PRINTD	LEAVES
	JUMP	?CND9
?CCL11:	PRINTI	"mighty hole"
?CND9:	PRINTI	", and rejoins off to the east."
	RTRUE	


	.FUNCT	TREE-HOLE-F
	EQUAL?	PRSA,V?CLOSE,V?OPEN \?CCL3
	PRINT	HUH
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?DISEMBARK \?CCL5
	IN?	PROTAGONIST,TREE-HOLE \?CCL5
	PRINT	YOU-CANT
	PRINTR	"climb out. You're trapped."
?CCL5:	EQUAL?	PRSA,V?REACH-IN \?CCL9
	IN?	FLYTRAP,TREE-HOLE \?CCL9
	PRINTI	"The "
	PRINTD	FLYTRAP
	PRINTI	" pulls you in. "
	CALL1	FLYTRAP-DEATH
	RSTACK	
?CCL9:	EQUAL?	PRSA,V?BOARD \?CCL13
	FSET?	TRELLIS,MUNGBIT \?CCL16
	PRINTR	"The hole's covered."
?CCL16:	CALL2	ULTIMATELY-IN?,TRELLIS
	ZERO?	STACK /?CCL18
	PRINT	TRELLIS-TOO-WIDE
	RTRUE	
?CCL18:	IN?	FLYTRAP,TREE-HOLE \FALSE
	PRINTI	"Hey! There's a big, hungry, angry "
	PRINTD	FLYTRAP
	CALL2	JIGS-UP,STR?350
	RSTACK	
?CCL13:	EQUAL?	PRSA,V?MEASURE \?CCL22
	PRINTR	"The hole is about six feet across."
?CCL22:	EQUAL?	PRSA,V?WALK-AROUND \?CCL24
	IN?	FLYTRAP,HERE \?CCL27
	PRINTI	"You circle the hole completely, with"
	ICALL2	TPRINT,FLYTRAP
	PRINTR	" in hot pursuit."
?CCL27:	CALL1	WEE
	RSTACK	
?CCL24:	EQUAL?	PRSA,V?LOOK-INSIDE \?CCL29
	ZERO?	LEAVES-PLACED /?CCL29
	ICALL	PERFORM,V?BOARD,TREE-HOLE
	RTRUE	
?CCL29:	EQUAL?	PRSA,V?PUT-ON \?CCL33
	EQUAL?	PRSO,LEAVES \?CCL33
	FSET?	TRELLIS,MUNGBIT \?CCL33
	ICALL	PERFORM-PRSA,LEAVES,TRELLIS
	RTRUE	
?CCL33:	EQUAL?	PRSA,V?EXAMINE \?CCL38
	FSET?	TRELLIS,MUNGBIT \?CCL38
	ICALL1	DESCRIBE-TRELLIS-ON-HOLE
	CRLF	
	RTRUE	
?CCL38:	EQUAL?	PRSA,V?UNCOVER \?CCL42
	FSET?	TRELLIS,MUNGBIT \?CCL42
	ICALL	PERFORM,V?MOVE,TRELLIS
	RTRUE	
?CCL42:	EQUAL?	PRSA,V?HIDE \FALSE
	IN?	FLYTRAP,HERE \FALSE
	ICALL	PERFORM,V?WALK-AROUND,TREE-HOLE
	RTRUE	


	.FUNCT	CLEARING-F,RARG
	EQUAL?	RARG,M-LOOK \FALSE
	PRINTI	"This is a tiny anti-oasis of barrenness amidst the teeming Venusian jungle. Winding paths enter the jungle in most directions."
	RTRUE	


	.FUNCT	CLEARING-EXIT-F
	PRINTI	"You walk swiftly down the trail! It turns! It twists! It narrows! Vines grab at your ankles and bird-sized insects close in for a kill! Suddenly"
	PRINT	ELLIPSIS
	EQUAL?	PRSO,P?NE \?CCL3
	RETURN	FRONT-DOOR
?CCL3:	EQUAL?	PRSO,P?NW \?CCL5
	RETURN	BACK-DOOR
?CCL5:	ICALL1	DESCRIBE-ROOM
	IN?	SIDEKICK,HERE \FALSE
	ICALL1	NORMAL-SIDEKICK-FOLLOW
	RFALSE	


	.FUNCT	STAIN-F
	FSET?	STAIN,UNTEEDBIT /FALSE
	EQUAL?	PRSA,V?LOOK-INSIDE,V?EXAMINE \?CCL5
	CALL1	EXAMINE-CREAM-AND-STAIN
	RSTACK	
?CCL5:	EQUAL?	PRSA,V?APPLY \?CCL7
	CALL	GLOBAL-IN?,HOLE,HERE
	ZERO?	STACK /?CCL7
	CALL2	APPLY-STAIN,HOLE
	RSTACK	
?CCL7:	EQUAL?	PRSA,V?EMPTY \?CCL11
	EQUAL?	PRSO,STAIN \?CCL11
	FSET?	STAIN,MUNGBIT \?CCL16
	CALL1	EXAMINE-CREAM-AND-STAIN
	RSTACK	
?CCL16:	ZERO?	PRSI /?CTR17
	EQUAL?	PRSI,WATER,CANAL-OBJECT,GROUND /?CTR17
	EQUAL?	PRSI,TREE-HOLE \?CCL18
?CTR17:	FSET	STAIN,MUNGBIT
	PRINTR	"Done. What a waste of good stain!"
?CCL18:	CALL2	APPLY-STAIN,PRSI
	RSTACK	
?CCL11:	EQUAL?	PRSA,V?CLOSE,V?OPEN \?CCL23
	CALL1	NO-LID
	RSTACK	
?CCL23:	EQUAL?	PRSA,V?DRINK \?CCL25
	PRINT	YECHH
	RTRUE	
?CCL25:	EQUAL?	PRSA,V?POUR \?CCL27
	EQUAL?	PRSI,WATER,CANAL-OBJECT,GROUND /?CTR26
	EQUAL?	PRSI,TREE-HOLE \?CCL27
?CTR26:	ICALL	PERFORM,V?EMPTY,STAIN,GROUND
	RTRUE	
?CCL27:	EQUAL?	PRSA,V?RUB,V?PUT-ON,V?POUR \FALSE
	EQUAL?	PRSO,STAIN \FALSE
	CALL	NOUN-USED,W?STAIN,STAIN
	ZERO?	STACK /FALSE
	CALL2	APPLY-STAIN,PRSI
	RSTACK	


	.FUNCT	APPLY-STAIN,OBJ
	FSET?	STAIN,MUNGBIT \?CCL3
	SET	'PRSO,STAIN
	CALL1	EXAMINE-CREAM-AND-STAIN
	RSTACK	
?CCL3:	EQUAL?	OBJ,HOLE \?CCL5
	ICALL2	THIS-IS-IT,HOLE
	PRINTI	"The circle is "
	CALL1	CIRCLE-ISNT-BLACK
	ZERO?	STACK /?CCL8
	SET	'CIRCLE-BLACK,TRUE-VALUE
	FSET	STAIN,MUNGBIT
	PUT	P-ADJW,0,FALSE-VALUE
	PUT	P-ADJW,1,FALSE-VALUE
	PUTP	HOLE,P?SDESC,STR?134
	PRINTI	"once again"
	JUMP	?CND6
?CCL8:	PRINTI	"already"
?CND6:	PRINTR	" black!"
?CCL5:	EQUAL?	OBJ,FLYTRAP \?CCL10
	ICALL	PERFORM,V?TOUCH,FLYTRAP
	RTRUE	
?CCL10:	PRINTI	"You apply a tiny dab to"
	ICALL2	TPRINT,OBJ
	PRINTR	" but it doesn't stick."


	.FUNCT	EXAMINE-CREAM-AND-STAIN
	PRINTI	"The "
	ICALL2	DPRINT,PRSO
	PRINTI	" is "
	FSET?	PRSO,MUNGBIT \?CCL3
	PRINTI	"empty"
	JUMP	?CND1
?CCL3:	PRINTI	"full"
?CND1:	EQUAL?	PRSA,V?EXAMINE \?CND4
	PRINTI	", and has some writing on it"
?CND4:	PRINT	PERIOD-CR
	RTRUE	


	.FUNCT	BACK-DOOR-F,RARG
	EQUAL?	RARG,M-ENTER \FALSE
	CALL	QUEUE,I-SALESMAN,-1
	RSTACK	


	.FUNCT	SALESMAN-F
	EQUAL?	SALESMAN,WINNER \?CCL3
	ICALL	QUEUE,I-SALESMAN,2
	EQUAL?	PRSA,V?WHAT \?PRD8
	EQUAL?	PRSO,LGOP /?CTR5
?PRD8:	EQUAL?	PRSA,V?TELL-ABOUT \?CCL6
	EQUAL?	PRSO,ME \?CCL6
	EQUAL?	PRSI,LGOP \?CCL6
?CTR5:	PRINTR	"""I know the ones you mean. Made a fortune in interplanetary shoe and briefcase peddling. They really know the territory."""
?CCL6:	PRINTI	"""Let's cut the gab and cut a deal instead!"""
	CRLF	
	CALL1	STOP
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?GIVE \?CCL15
	EQUAL?	PRSI,SALESMAN \?CCL15
	EQUAL?	PRSO,FLASHLIGHT \?CCL20
	REMOVE	FLASHLIGHT
	MOVE	ODD-MACHINE,HERE
	FCLEAR	ODD-MACHINE,TRYTAKEBIT
	REMOVE	SALESMAN
	SET	'FOLLOW-FLAG,8
	ICALL	QUEUE,I-FOLLOW,2
	ICALL	INCREMENT-SCORE,3,7
	ICALL1	EAGERLY-ACCEPTS
	PRINTI	", mentioning that he knows a Plutonian plutocrat who'll trade his life fortune for one, and drops"
	ICALL2	APRINT,ODD-MACHINE
	PRINTI	" at your feet. ""It's a TEE remover,"" he explains. You ponder what it removes -- tea stains, hallway T-intersections -- even TV star Mr. T crosses your mind, until you recall that it's only 1936. But before you have a chance to ask the salesman, he "
	FSET?	FLASHLIGHT,ONBIT \?CCL23
	PRINTI	"points"
	ICALL2	TPRINT,FLASHLIGHT
	PRINTI	" upwards"
	JUMP	?CND21
?CCL23:	PRINTI	"turns on"
	ICALL2	TPRINT,FLASHLIGHT
?CND21:	PRINTI	" and a giant Venusian MegaMoth swoops down and carries him off. The other salesmen scatter like frightened salesmen."
	CRLF	
	RETURN	8
?CCL20:	ICALL	QUEUE,I-SALESMAN,2
	EQUAL?	PRSO,ONE-MARSMID-COIN,TEN-MARSMID-COIN \?CCL28
	ICALL	PERFORM,V?BUY,ODD-MACHINE
	RTRUE	
?CCL28:	CALL2	PICK-ONE,SALESMAN-REFUSALS
	PRINT	STACK
	PRINTR	" Offer me something else."""
?CCL15:	EQUAL?	PRSA,V?SHOW \?PRD32
	EQUAL?	PRSO,FLASHLIGHT /?CTR29
?PRD32:	EQUAL?	PRSA,V?ASK-ABOUT \?CCL30
	EQUAL?	PRSI,FLASHLIGHT \?CCL30
?CTR29:	PRINTR	"The salesman tries to look disinterested."
?CCL30:	EQUAL?	PRSA,V?FOLLOW \?CCL38
	EQUAL?	FOLLOW-FLAG,8 \?CCL38
	PRINT	DONT-WANT-TO
	RTRUE	
?CCL38:	EQUAL?	PRSA,V?BARTER-WITH \?CCL42
	PRINTR	"Just give him something!"
?CCL42:	EQUAL?	PRSA,V?COUNT \FALSE
	PRINTR	"Lots."


	.FUNCT	I-SALESMAN
	ICALL	QUEUE,I-SALESMAN,-1
	IN?	SALESMAN,HERE /?CND1
	FCLEAR	SALESMAN,TOUCHBIT
	ICALL2	DEQUEUE,I-SALESMAN
	RFALSE	
?CND1:	PRINTI	"   "
	FSET?	SALESMAN,TOUCHBIT \?CCL5
	CALL2	PICK-ONE,SALESMANISMS
	PRINT	STACK
	CRLF	
	RTRUE	
?CCL5:	FSET	SALESMAN,TOUCHBIT
	FCLEAR	ODD-MACHINE,NDESCBIT
	ICALL2	THIS-IS-IT,SALESMAN
	PRINTI	"A salesman approaches you. ""You look like a "
	ZERO?	MALE /?CCL8
	PRINTI	"fella"
	JUMP	?CND6
?CCL8:	PRINTI	"doll"
?CND6:	PRINTR	" who can spot a good deal. One of my machines could change your life! Let's barter; offer me something as an even-up trade."""


	.FUNCT	ODD-MACHINE-F,OBJ-IN-MACHINE
	FIRST?	ODD-MACHINE >OBJ-IN-MACHINE /?BOGUS1
?BOGUS1:	EQUAL?	PRSA,V?BUY \?CCL4
	IN?	ODD-MACHINE,SALESMAN \?CCL4
	ICALL	QUEUE,I-SALESMAN,2
	PRINTR	"""I wouldn't part with this baby for a hundred marsmids!"""
?CCL4:	EQUAL?	PRSA,V?PUT \?CCL8
	FSET?	ODD-MACHINE,OPENBIT \?CCL8
	EQUAL?	PRSI,ODD-MACHINE \?CCL8
	ZERO?	OBJ-IN-MACHINE /?CCL14
	EQUAL?	PRSO,OBJ-IN-MACHINE /?CCL14
	PRINT	ONLY-ONE-THING-IN-COMPARTMENT
	RTRUE	
?CCL14:	EQUAL?	PRSO,BABY \?CCL18
	PRINTR	"The baby cries so ferociously, you reconsider."
?CCL18:	FIRST?	PRSO \FALSE
	PRINT	YOULL-HAVE-TO
	PRINTI	"empty"
	ICALL1	TPRINT-PRSO
	PRINTI	" first. "
	PRINT	ONLY-ONE-THING-IN-COMPARTMENT
	RTRUE	
?CCL8:	EQUAL?	PRSA,V?EXAMINE \?CCL22
	PRINTI	"The "
	PRINTD	ODD-MACHINE
	PRINTI	" is off, and has a small, "
	ICALL2	OPEN-CLOSED,ODD-MACHINE
	PRINTI	" compartment"
	ZERO?	OBJ-IN-MACHINE /?CND23
	FSET?	ODD-MACHINE,OPENBIT \?CND23
	PRINTI	" containing"
	ICALL2	APRINT,OBJ-IN-MACHINE
?CND23:	PRINT	PERIOD-CR
	RTRUE	
?CCL22:	EQUAL?	PRSA,V?ON,V?OPEN,V?TAKE \?CCL28
	FSET?	ODD-MACHINE,TRYTAKEBIT \?CCL28
	ICALL	QUEUE,I-SALESMAN,2
	PRINTR	"""Hey!"" The salesman jumps back. ""No deal, no merchandise."""
?CCL28:	EQUAL?	PRSA,V?BARTER-FOR \?CCL32
	EQUAL?	PRSI,ODD-MACHINE \?CCL35
	ICALL	PERFORM,V?GIVE,PRSO,SALESMAN
	RTRUE	
?CCL35:	ICALL	PERFORM,V?BARTER-WITH,SALESMAN
	RTRUE	
?CCL32:	EQUAL?	PRSA,V?OFF \?CCL37
	PRINT	ALREADY-IS
	RTRUE	
?CCL37:	EQUAL?	PRSA,V?ON \?CCL39
	FSET?	ODD-MACHINE,OPENBIT \?CCL42
	PRINT	NOTHING-HAPPENS
	RTRUE	
?CCL42:	ZERO?	OBJ-IN-MACHINE /?CCL45
	GETP	OBJ-IN-MACHINE,P?NO-T-DESC
	ZERO?	STACK /?CCL45
	EQUAL?	OBJ-IN-MACHINE,TUBE,TORCH \?CND48
	FSET	OBJ-IN-MACHINE,VOWELBIT
?CND48:	EQUAL?	OBJ-IN-MACHINE,TORCH \?CND50
	ICALL2	DEQUEUE,I-TORCH
?CND50:	FCLEAR	OBJ-IN-MACHINE,CONTBIT
	FCLEAR	OBJ-IN-MACHINE,SEARCHBIT
	FCLEAR	OBJ-IN-MACHINE,OPENBIT
	FCLEAR	OBJ-IN-MACHINE,READBIT
	FCLEAR	OBJ-IN-MACHINE,VEHBIT
	FCLEAR	OBJ-IN-MACHINE,WEARBIT
	FCLEAR	OBJ-IN-MACHINE,ONBIT
	FCLEAR	OBJ-IN-MACHINE,SURFACEBIT
	FSET	OBJ-IN-MACHINE,UNTEEDBIT
	JUMP	?CND43
?CCL45:	EQUAL?	OBJ-IN-MACHINE,RABBIT \?CND43
	FSET	RABBIT,UNTEEDBIT
?CND43:	EQUAL?	OBJ-IN-MACHINE,CHOCOLATE \?CND53
	FSET?	CHOCOLATE,SMELLEDBIT /?CND53
	FCLEAR	CHOCOLATE,UNTEEDBIT
?CND53:	PRINTR	"Sparks! Explosions! ""Pockita pockita pockita FEEP!"" exclaims the machine."
?CCL39:	EQUAL?	PRSA,V?OPEN \FALSE
	IN?	RABBIT,ODD-MACHINE \FALSE
	FSET?	RABBIT,UNTEEDBIT \FALSE
	FSET	ODD-MACHINE,OPENBIT
	REMOVE	RABBIT
	PRINTI	"A bearded rabbi wearing a prayer shawl leaps out of the machine, recites a Torah blessing, and "
	EQUAL?	HERE,CANAL,IN-SPACE \?CCL64
	PRINTI	"swim"
	JUMP	?CND62
?CCL64:	PRINTI	"dashe"
?CND62:	PRINTR	"s off in search of a minyan."


	.FUNCT	MAD-SCIENTIST-DOOR-F
	EQUAL?	PRSA,V?KNOCK \FALSE
	EQUAL?	HERE,LOOKS-CAN-BE-DECEIVING /FALSE
	FSET?	CAGE,MUNGBIT /FALSE
	FSET	PRSO,OPENBIT
	PRINTI	"The door is thrown open by a wild-eyed "
	PRINTD	MAD-SCIENTIST
	PRINTI	". """
	FSET?	LOOKS-CAN-BE-DECEIVING,TOUCHBIT \?CCL9
	PRINTI	"Ach! You haf returned! Ve can continue der experiment!"
	JUMP	?CND7
?CCL9:	PRINTI	"Nein! Nein! Nein! I don't need any!"" Then, taking a closer look at you through spectacles thick enough to stop gamma rays, he says, ""Oh! Not ein salesman! In fact, just der type I need for mein experiment."
?CND7:	CALL2	ULTIMATELY-IN?,FLEXIBLE-HOLE
	ZERO?	STACK /?CND10
	PRINTI	" But leaf your "
	IN?	FLEXIBLE-HOLE,TUBE \?CCL14
	PRINTD	TUBE
	MOVE	TUBE,HERE
	JUMP	?CND12
?CCL14:	PRINTD	FLEXIBLE-HOLE
	MOVE	FLEXIBLE-HOLE,HERE
?CND12:	PRINTI	" outsite,"" he says, knocking it to the ground, ""I'm allergic."
?CND10:	PRINTI	""" He grips your wrist with surprising strength and drags you inside."
	CRLF	
	CRLF	
	MOVE	MAD-SCIENTIST,LOOKS-CAN-BE-DECEIVING
	CALL2	GOTO,LOOKS-CAN-BE-DECEIVING
	RSTACK	


	.FUNCT	LOOKS-CAN-BE-DECEIVING-F,RARG,OPEN-DOOR
	FSET?	FRONT-DOOR-OBJECT,OPENBIT \?CCL3
	SET	'OPEN-DOOR,FRONT-DOOR-OBJECT
	JUMP	?CND1
?CCL3:	FSET?	BACK-DOOR-OBJECT,OPENBIT \?CND1
	SET	'OPEN-DOOR,BACK-DOOR-OBJECT
?CND1:	EQUAL?	RARG,M-LOOK \?CCL7
	PRINTI	"From the innocent appearance of this quiet living area, you'd never guess that all sorts of twisted, maniacal, perverted experiments are in progress a short flight of stairs below. There are doors to the north"
	EQUAL?	OPEN-DOOR,BACK-DOOR-OBJECT \?CND8
	PRINTI	" (open)"
?CND8:	PRINTI	" and south"
	EQUAL?	OPEN-DOOR,FRONT-DOOR-OBJECT \?CND10
	PRINTI	" (open)"
?CND10:	ZERO?	OPEN-DOOR \?CND12
	PRINTI	", both closed"
?CND12:	PRINTC	46
	RTRUE	
?CCL7:	EQUAL?	RARG,M-END \FALSE
	ZERO?	OPEN-DOOR /FALSE
	ICALL	QUEUE,I-MAD-SCIENTIST,2
	FCLEAR	OPEN-DOOR,OPENBIT
	PRINTI	"   You feel uneasy as"
	ICALL2	TPRINT,MAD-SCIENTIST
	PRINTR	" locks the door behind you and dissolves the key in a vat of acid."


	.FUNCT	MAD-SCIENTIST-F,OARG
	ZERO?	OARG /?CCL3
	ZERO?	IMPATIENCE-COUNTER /FALSE
	EQUAL?	OARG,M-OBJDESC? /TRUE
	PRINTI	"   The wild-eyed "
	PRINTD	MAD-SCIENTIST
	PRINTI	" is "
	GET	MAD-SCIENTIST-DESCS,MAD-SCIENTIST-COUNTER
	PRINT	STACK
	RTRUE	
?CCL3:	EQUAL?	MAD-SCIENTIST,WINNER \?CCL9
	EQUAL?	PRSA,V?WHAT \?PRD14
	EQUAL?	PRSO,LGOP /?CTR11
?PRD14:	EQUAL?	PRSA,V?TELL-ABOUT \?CCL12
	EQUAL?	PRSO,ME \?CCL12
	EQUAL?	PRSI,LGOP \?CCL12
?CTR11:	PRINTI	"""Eh?"" yells"
	ICALL2	TPRINT,MAD-SCIENTIST
	PRINTR	", cupping his ear. ""Heather bodices of no-doze? Vat in heck are you jabbering about?"""
?CCL12:	PRINTI	"The "
	PRINTD	MAD-SCIENTIST
	PRINTI	" ignores you, cackling with inner glee."
	CRLF	
	CALL1	STOP
	RSTACK	
?CCL9:	EQUAL?	PRSA,V?FOLLOW \FALSE
	EQUAL?	FOLLOW-FLAG,17 \FALSE
	CALL2	DO-WALK,P?NORTH
	RSTACK	


	.FUNCT	I-MAD-SCIENTIST
	PRINTI	"   "
	ZERO?	MAD-SCIENTIST-COUNTER \?CCL3
	INC	'IMPATIENCE-COUNTER
	ICALL	QUEUE,I-MAD-SCIENTIST,2
	EQUAL?	IMPATIENCE-COUNTER,1 \?CCL6
	PRINTI	"""Let us retire to der laboratory,"" suggests"
	CALL2	TRPRINT,MAD-SCIENTIST
	RSTACK	
?CCL6:	EQUAL?	IMPATIENCE-COUNTER,2 \?CCL8
	PRINTI	"""Downstairs, please,"" says"
	ICALL2	TPRINT,MAD-SCIENTIST
	PRINTR	", impatiently."
?CCL8:	EQUAL?	IMPATIENCE-COUNTER,3 \?CCL10
	PRINTI	"The "
	PRINTD	MAD-SCIENTIST
	PRINTR	", fidgeting himself into a frenzy, motions toward the stairs."
?CCL10:	PRINTI	"The "
	PRINTD	MAD-SCIENTIST
	PRINTI	" loses his patience and opens the trapdoor, dumping you"
	ICALL2	AND-SIDEKICK,LABORATORY
	PRINTI	" down a chute"
	PRINT	ELLIPSIS
	ICALL2	GOTO,LABORATORY
	ICALL2	LABORATORY-F,M-END
	RTRUE	
?CCL3:	EQUAL?	MAD-SCIENTIST-COUNTER,1 \?CCL12
	MOVE	PROTAGONIST,FIRST-SLAB
	SET	'OHERE,FALSE-VALUE
	ICALL	QUEUE,I-MAD-SCIENTIST,3
	SET	'MAD-SCIENTIST-COUNTER,2
	SET	'BODY-TIED-TO-SLAB,TRUE-VALUE
	PRINTI	"Again exhibiting extraordinary strength,"
	ICALL2	TPRINT,MAD-SCIENTIST
	PRINTI	" straps you down on"
	ICALL2	TPRINT,FIRST-SLAB
	CALL2	VISIBLE?,SIDEKICK
	ZERO?	STACK /?CND13
	MOVE	SIDEKICK,SECOND-SLAB
	SET	'SIDEKICKS-BODY-TIED-TO-SLAB,TRUE-VALUE
	PRINTI	" and "
	ICALL1	DPRINT-SIDEKICK
	PRINTI	" onto"
	ICALL2	TPRINT,SECOND-SLAB
?CND13:	PRINT	PERIOD-CR
	RTRUE	
?CCL12:	EQUAL?	MAD-SCIENTIST-COUNTER,2 \?CCL16
	ICALL	QUEUE,I-MAD-SCIENTIST,6
	SET	'MAD-SCIENTIST-COUNTER,3
	ICALL1	IDENTITY-TRANSFER
	PRINTI	"The "
	PRINTD	MAD-SCIENTIST
	PRINTI	" flips"
	ICALL2	TPRINT,POWER-SWITCH
	PRINTI	", and you suddenly find yourself within the cage. Oddly, you can also see yourself still strapped to"
	ICALL2	TPRINT,FIRST-SLAB
	PRINTR	". As you swing across the cage to get a better look, you realize that you're now inside the body of a gorilla."
?CCL16:	EQUAL?	MAD-SCIENTIST-COUNTER,3 \FALSE
	CALL1	MINE-THEORY
	RSTACK	


	.FUNCT	LABORATORY-F,RARG
	EQUAL?	RARG,M-ENTER \?CCL3
	CALL2	QUEUED?,I-ION-DEATH
	ZERO?	STACK /?CCL3
	FSET	POWER-TRANSMITTER,MUNGBIT
	CALL	QUEUE,I-ION-DEATH,1
	RSTACK	
?CCL3:	EQUAL?	RARG,M-LOOK \?CCL7
	PRINTI	"The scientist's madness is finally evident by his lab, filled with many expressions of insane genius, such as the "
	FSET?	MALE-GORILLA,NDESCBIT \?CCL10
	FSET?	FEMALE-GORILLA,NDESCBIT \?CCL10
	PRINTI	"two caged gorillas, one male and one female"
	JUMP	?CND8
?CCL10:	PRINTI	"cage"
?CND8:	PRINTI	", the two slabs for strapping down human victims, and"
	ICALL2	TPRINT,POWER-SWITCH
	PRINTI	". A closed door leads north; at the foot of the winding stone stairs is"
	ICALL2	APRINT,HOLE
	PRINTC	46
	RTRUE	
?CCL7:	EQUAL?	RARG,M-END \FALSE
	IN?	MAD-SCIENTIST,LOOKS-CAN-BE-DECEIVING \FALSE
	FCLEAR	MALE-GORILLA,NDESCBIT
	FCLEAR	FEMALE-GORILLA,NDESCBIT
	MOVE	MAD-SCIENTIST,HERE
	ICALL	QUEUE,I-MAD-SCIENTIST,5
	SET	'MAD-SCIENTIST-COUNTER,1
	PRINTI	"   The "
	PRINTD	MAD-SCIENTIST
	PRINTR	" bounds down from the first floor, activating a (guaranteed 100% effective) Vaporo-Zap Energy Barrier across the foot of the stairs."


	.FUNCT	LAB-DOOR-ENTER-F
	ICALL2	DO-FIRST,STR?366
	RFALSE	


	.FUNCT	LAB-DOOR-F
	EQUAL?	PRSA,V?CLOSE,V?OPEN \?CCL3
	ICALL2	PERFORM-PRSA,BACK-DOOR-OBJECT
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?KNOCK \FALSE
	ICALL2	PERFORM-PRSA,WIDE-CELL-DOOR
	RTRUE	


	.FUNCT	STRAP-F
	EQUAL?	PRSA,V?OPEN,V?UNTIE \FALSE
	ICALL	PERFORM,V?UNTIE,ME
	RTRUE	


	.FUNCT	POWER-SWITCH-F
	CALL2	TOUCHING?,POWER-SWITCH
	ZERO?	STACK /?CCL3
	IN?	PROTAGONIST,HERE /?CCL3
	CALL2	CANT-REACH,POWER-SWITCH
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?OFF,V?ON,V?SET /?PRD9
	EQUAL?	PRSA,V?PUSH,V?MOVE,V?THROW /?PRD9
	EQUAL?	PRSA,V?OPEN,V?LOWER,V?RAISE /?PRD9
	EQUAL?	PRSA,V?CLOSE \FALSE
?PRD9:	EQUAL?	PRSO,POWER-SWITCH \FALSE
	IN?	MAD-SCIENTIST,HERE \?CCL16
	PRINTI	"The "
	PRINTD	MAD-SCIENTIST
	PRINTR	" stops you."
?CCL16:	ICALL1	IDENTITY-TRANSFER
	PRINTI	"Zap! You're back in "
	ZERO?	GONE-APE /?CCL19
	PRINTI	"the body of the "
	ZERO?	MALE \?CND20
	PRINTI	"fe"
?CND20:	PRINTD	MALE-GORILLA
	PRINTC	46
	JUMP	?CND17
?CCL19:	FSET?	RUBBER-HOSE,MUNGBIT /?CND22
	FSET	RUBBER-HOSE,MUNGBIT
	ICALL	INCREMENT-SCORE,19,24,TRUE-VALUE
?CND22:	MOVE	MALE-GORILLA,CAGE
	MOVE	FEMALE-GORILLA,CAGE
	PRINTI	"your own body! The gorilla looks confused and slinks back into the comfortingly familiar environment of the cage."
?CND17:	ZERO?	BODY-TIED-TO-SLAB /?CND24
	ZERO?	SIDEKICKS-BODY-TIED-TO-SLAB \?CND24
	CALL2	VISIBLE?,SIDEKICK
	ZERO?	STACK /?CND24
	SET	'BODY-TIED-TO-SLAB,FALSE-VALUE
	MOVE	SIDEKICK,HERE
	PRINTC	32
	ICALL1	DPRINT-SIDEKICK
	PRINTR	" rushes over and unties you."
?CND24:	CRLF	
	RTRUE	


	.FUNCT	IDENTITY-TRANSFER
	ICALL1	OPEN-EYES-AND-REMOVE-HANDS
	ZERO?	GONE-APE /?CCL3
	ZERO?	MALE /?CCL6
	ICALL	ROB,PROTAGONIST,MALE-GORILLA
	LOC	PROTAGONIST
	MOVE	MALE-GORILLA,STACK
	FCLEAR	MALE-GORILLA,NDESCBIT
	JUMP	?CND4
?CCL6:	ICALL	ROB,PROTAGONIST,FEMALE-GORILLA
	LOC	PROTAGONIST
	MOVE	FEMALE-GORILLA,STACK
	FCLEAR	FEMALE-GORILLA,NDESCBIT
?CND4:	CALL2	VISIBLE?,SIDEKICKS-BODY
	ZERO?	STACK /?CND7
	LOC	SIDEKICKS-BODY
	MOVE	SIDEKICK,STACK
	REMOVE	SIDEKICKS-BODY
?CND7:	LOC	YOUR-BODY
	MOVE	PROTAGONIST,STACK
	SET	'OHERE,FALSE-VALUE
	ICALL	ROB,YOUR-BODY,PROTAGONIST
	REMOVE	YOUR-BODY
	SET	'GONE-APE,FALSE-VALUE
	RETURN	GONE-APE
?CCL3:	SET	'GONE-APE,TRUE-VALUE
	LOC	PROTAGONIST
	MOVE	YOUR-BODY,STACK
	ICALL	ROB,PROTAGONIST,YOUR-BODY
	ZERO?	MALE /?CCL11
	LOC	MALE-GORILLA
	MOVE	PROTAGONIST,STACK
	FSET	MALE-GORILLA,NDESCBIT
	ICALL	ROB,MALE-GORILLA,PROTAGONIST
	JUMP	?CND9
?CCL11:	LOC	FEMALE-GORILLA
	MOVE	PROTAGONIST,STACK
	FSET	FEMALE-GORILLA,NDESCBIT
	ICALL	ROB,FEMALE-GORILLA,PROTAGONIST
?CND9:	SET	'OHERE,FALSE-VALUE
	CALL2	VISIBLE?,SIDEKICK
	ZERO?	STACK /FALSE
	LOC	SIDEKICK
	MOVE	SIDEKICKS-BODY,STACK
	REMOVE	SIDEKICK
	RTRUE	


	.FUNCT	LABORATORY-EXIT-F
	CALL2	JIGS-UP,STR?367
	RSTACK	


	.FUNCT	CAGE-F
	EQUAL?	PRSA,V?EXAMINE \?CCL3
	PRINTI	"The bars "
	FSET?	CAGE,MUNGBIT \?CCL6
	PRINTI	"have been"
	PRINT	SPREAD-APART
	JUMP	?CND4
?CCL6:	PRINTI	"seem sturdy"
?CND4:	PRINT	PERIOD-CR
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?WALK-TO,V?BOARD,V?ENTER /?PRD10
	EQUAL?	PRSA,V?EXIT,V?LEAVE,V?DISEMBARK \?CCL8
?PRD10:	EQUAL?	HERE,LABORATORY \?CCL8
	FSET?	CAGE,MUNGBIT /?CCL8
	PRINTR	"You don't fit between the bars."
?CCL8:	EQUAL?	PRSA,V?BEND,V?MUNG,V?OPEN /?CTR14
	EQUAL?	PRSA,V?MOVE \?CCL15
	CALL	NOUN-USED,W?CAGE,CAGE
	ZERO?	STACK \?CCL15
?CTR14:	FSET?	CAGE,MUNGBIT \?CCL22
	PRINT	SENILITY-STRIKES
	RTRUE	
?CCL22:	ZERO?	GONE-APE \?CCL24
	PRINTR	"This cage was built to hold an ape! Mere human strength is nothing against these bars!"
?CCL24:	PRINTI	"Bellowing madly, you pull at the bars! "
	EQUAL?	SUGAR-RUSH,GORILLA-ATE-CHOCOLATE \?CCL27
	FSET	CAGE,MUNGBIT
	PRINTI	"Slowly, they"
	PRINT	SPREAD-APART
	PRINTC	46
	IN?	MAD-SCIENTIST,HERE \?CCL30
	PRINTI	" The "
	PRINTD	MAD-SCIENTIST
	CALL2	JIGS-UP,STR?368
	RSTACK	
?CCL30:	CRLF	
	RTRUE	
?CCL27:	PRINTR	"They almost give, but you haven't got quite enough strength."
?CCL15:	EQUAL?	PRSA,V?PUT \?CCL32
	EQUAL?	PRSI,CAGE \?CCL32
	LOC	PROTAGONIST
	EQUAL?	STACK,FIRST-SLAB,SECOND-SLAB \?CCL32
	CALL2	CANT-REACH,CAGE
	RSTACK	
?CCL32:	EQUAL?	PRSA,V?REACH-IN \FALSE
	IN?	PROTAGONIST,CAGE \?CCL40
	PRINT	LOOK-AROUND
	RTRUE	
?CCL40:	IN?	RUBBER-HOSE,CAGE \FALSE
	CALL2	CANT-REACH,RUBBER-HOSE
	RSTACK	


	.FUNCT	GORILLA-F
	ZERO?	GONE-APE /?CCL3
	ZERO?	MALE /?CCL3
	EQUAL?	PRSO,MALE-GORILLA \?CCL3
	ICALL	PERFORM-PRSA,ME,PRSI
	RTRUE	
?CCL3:	ZERO?	GONE-APE /?CCL8
	ZERO?	MALE /?CCL8
	EQUAL?	PRSI,MALE-GORILLA \?CCL8
	ICALL	PERFORM-PRSA,PRSO,ME
	RTRUE	
?CCL8:	ZERO?	GONE-APE /?CCL13
	ZERO?	MALE \?CCL13
	EQUAL?	PRSO,FEMALE-GORILLA \?CCL13
	ICALL	PERFORM-PRSA,ME,PRSI
	RTRUE	
?CCL13:	ZERO?	GONE-APE /?CCL18
	ZERO?	MALE \?CCL18
	EQUAL?	PRSI,FEMALE-GORILLA \?CCL18
	ICALL	PERFORM-PRSA,PRSO,ME
	RTRUE	
?CCL18:	EQUAL?	PRSA,V?TELL \?CCL23
	PRINTI	"""Ooo oo ee ee ee!"""
	CRLF	
	CALL1	STOP
	RSTACK	
?CCL23:	EQUAL?	PRSA,V?GIVE \?CCL25
	EQUAL?	PRSI,FEMALE-GORILLA,MALE-GORILLA \?CCL25
	LOC	PROTAGONIST
	EQUAL?	STACK,FIRST-SLAB,SECOND-SLAB \?CCL30
	CALL2	CANT-REACH,PRSI
	RSTACK	
?CCL30:	ICALL1	EAGERLY-ACCEPTS
	PRINT	PERIOD-CR
	RTRUE	
?CCL25:	EQUAL?	PRSA,V?EXAMINE \?CCL32
	ZERO?	GONE-APE /?CCL35
	SET	'GORILLA-EXAMINED,TRUE-VALUE
	ICALL1	NOT-BAD-LOOKING
	JUMP	?CND33
?CCL35:	PRINTI	"An uglier beast cannot possibly exist."
?CND33:	FIRST?	PRSO \?CCL38
	PRINTC	32
	RFALSE	
?CCL38:	CRLF	
	RTRUE	
?CCL32:	EQUAL?	PRSA,V?TOUCH,V?KISS,V?FUCK \FALSE
	ZERO?	GONE-APE \?CCL43
	PRINTR	"What a repulsive, bestial idea!"
?CCL43:	ZERO?	NAUGHTY-LEVEL \?CCL46
	PRINTI	"Normally, we wouldn't allow this in TAME mode, but it's okay in this case since you're only a gorilla. This sort of thing appears all the time in National Geographic."
	JUMP	?CND44
?CCL46:	ZERO?	GORILLA-EXAMINED \?CND47
	SET	'GORILLA-EXAMINED,TRUE-VALUE
	ICALL1	NOT-BAD-LOOKING
	PRINTC	32
?CND47:	PRINTI	"You begin nuzzling, and things quickly get hot and heavy."
	EQUAL?	NAUGHTY-LEVEL,2 \?CND44
	PRINTI	" The "
	PRINTD	PRSO
	PRINTI	" screams, ""Eee oo oo ah!"" which translates roughly as ""Oh, you animal!"""
?CND44:	IN?	MAD-SCIENTIST,HERE \?CCL53
	PRINTC	32
	CALL2	MINE-THEORY,TRUE-VALUE
	RSTACK	
?CCL53:	CRLF	
	RTRUE	


	.FUNCT	GENERIC-GORILLA-F
	ZERO?	GONE-APE /FALSE
	ZERO?	MALE \?CTR4
	RETURN	MALE-GORILLA
?CTR4:	RETURN	FEMALE-GORILLA


	.FUNCT	NOT-BAD-LOOKING
	PRINTI	"Hey! The "
	PRINTD	PRSO
	PRINTI	" isn't bad-looking!"
	RTRUE	


	.FUNCT	MINE-THEORY,RIGHT
	REMOVE	MAD-SCIENTIST
	ICALL2	DEQUEUE,I-MAD-SCIENTIST
	SET	'FOLLOW-FLAG,17
	ICALL	QUEUE,I-FOLLOW,2
	PRINTI	"""Ach!"" yells"
	ICALL2	TPRINT,MAD-SCIENTIST
	PRINTI	", ""mein theory iss "
	ZERO?	RIGHT /?CCL3
	PRINTI	"correct"
	JUMP	?CND1
?CCL3:	PRINTI	"wronk"
?CND1:	PRINTI	"! Der sex drive uf a species resides in der b"
	ZERO?	RIGHT /?CCL6
	PRINTI	"ody"
	JUMP	?CND4
?CCL6:	PRINTI	"rain"
?CND4:	PRINTI	", not in der b"
	ZERO?	RIGHT /?CCL9
	PRINTI	"rain"
	JUMP	?CND7
?CCL9:	PRINTI	"ody"
?CND7:	PRINTI	"!"" He dashes off."
	CRLF	
	CALL2	VISIBLE?,SIDEKICKS-BODY
	ZERO?	STACK /TRUE
	PRINTI	"   Through the briefly open door, you see two "
	PRINTD	FLYTRAP
	PRINTR	"s running madly around the next room. One is chasing, while the other is frantically trying to stay as far away as possible."


	.FUNCT	RUBBER-HOSE-F
	EQUAL?	PRSA,V?MEASURE,V?EXAMINE \?CCL3
	PRINTR	"The hose is around six feet long."
?CCL3:	EQUAL?	PRSA,V?LOOK-INSIDE \FALSE
	PRINT	ONLY-BLACKNESS
	RTRUE	


	.FUNCT	FIRST-SLAB-F
	EQUAL?	PRSA,V?DISEMBARK \?CCL3
	ZERO?	GONE-APE \?CCL3
	ZERO?	BODY-TIED-TO-SLAB /?CCL3
	PRINTR	"You're strapped down."
?CCL3:	EQUAL?	PRSA,V?PUT-ON \FALSE
	EQUAL?	PRSI,FIRST-SLAB \FALSE
	IN?	PROTAGONIST,CAGE \FALSE
	CALL2	CANT-REACH,FIRST-SLAB
	RSTACK	


	.FUNCT	SECOND-SLAB-F
	EQUAL?	PRSA,V?PUT-ON \FALSE
	EQUAL?	PRSI,SECOND-SLAB \FALSE
	IN?	PROTAGONIST,CAGE \FALSE
	CALL2	CANT-REACH,SECOND-SLAB
	RSTACK	


	.FUNCT	GENERIC-SLAB-F
	LOC	PROTAGONIST
	EQUAL?	STACK,FIRST-SLAB,SECOND-SLAB \FALSE
	LOC	PROTAGONIST
	RSTACK	


	.FUNCT	YOUR-BODY-F
	EQUAL?	PRSA,V?TELL \?CCL3
	ICALL2	PERFORM-PRSA,MALE-GORILLA
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?EXAMINE \?CCL5
	PRINTI	"Your body"
	IN?	YOUR-BODY,FIRST-SLAB \?CND6
	PRINTI	" on"
	ICALL2	TPRINT,FIRST-SLAB
?CND6:	PRINTR	" is grunting, scratching itself with its foot, and looking around the room for a banana."
?CCL5:	EQUAL?	PRSA,V?GIVE \?CCL9
	EQUAL?	PRSI,YOUR-BODY \?CCL9
	ICALL1	EAGERLY-ACCEPTS
	PRINT	PERIOD-CR
	RTRUE	
?CCL9:	EQUAL?	PRSA,V?TAKE \?CCL13
	EQUAL?	PRSO,YOUR-BODY \?CCL13
	PRINTI	"Carrying "
	PRINTD	YOUR-BODY
	PRINTI	" around"
	CALL1	HO-HUM
	RSTACK	
?CCL13:	EQUAL?	PRSA,V?TIE \?CCL17
	EQUAL?	PRSO,SECOND-SLAB,FIRST-SLAB \?CCL17
	ZERO?	BODY-TIED-TO-SLAB \?CCL17
	EQUAL?	PRSO,SECOND-SLAB \?CND21
	PRINTI	"[the first slab is closer]"
	CRLF	
?CND21:	SET	'BODY-TIED-TO-SLAB,TRUE-VALUE
	CALL2	NOW-TIED,FIRST-SLAB
	RSTACK	
?CCL17:	EQUAL?	PRSA,V?UNTIE \FALSE
	IN?	PROTAGONIST,CAGE \?CCL27
	CALL2	CANT-REACH,YOUR-BODY
	RSTACK	
?CCL27:	ZERO?	GONE-APE /?CCL29
	ZERO?	BODY-TIED-TO-SLAB /?CCL32
	SET	'BODY-TIED-TO-SLAB,FALSE-VALUE
	PRINTI	"Your body leaps for a rafter and lands back on"
	ICALL2	TPRINT,FIRST-SLAB
	PRINTR	" with a loud ""whump,"" looking momentarily stunned."
?CCL32:	PRINT	SENILITY-STRIKES
	RTRUE	
?CCL29:	ZERO?	BODY-TIED-TO-SLAB /?CCL34
	CALL1	YUKS
	RSTACK	
?CCL34:	PRINTR	"Your body isn't tied down!"


	.FUNCT	SIDEKICKS-BODY-F
	EQUAL?	PRSA,V?EXAMINE \?CCL3
	ICALL2	HIS-HER,TRUE-VALUE
	PRINTR	" eyes are darting around the room, as though following a fly."
?CCL3:	EQUAL?	PRSA,V?TIE \?CCL5
	EQUAL?	PRSO,SECOND-SLAB \?CCL8
	ZERO?	SIDEKICKS-BODY-TIED-TO-SLAB /?CCL8
	ICALL1	DPRINT-SIDEKICK
	PRINTR	" already is!"
?CCL8:	EQUAL?	PRSO,SECOND-SLAB \?CCL12
	ZERO?	GONE-APE /?CCL12
	SET	'SIDEKICKS-BODY-TIED-TO-SLAB,TRUE-VALUE
	CALL2	NOW-TIED,SECOND-SLAB
	RSTACK	
?CCL12:	CALL1	WASTES
	RSTACK	
?CCL5:	EQUAL?	PRSA,V?UNTIE \FALSE
	LOC	PROTAGONIST
	EQUAL?	STACK,CAGE,FIRST-SLAB \?CCL19
	CALL2	CANT-REACH,SIDEKICKS-BODY
	RSTACK	
?CCL19:	ZERO?	GONE-APE /?CCL21
	ZERO?	SIDEKICKS-BODY-TIED-TO-SLAB /?CCL24
	SET	'SIDEKICKS-BODY-TIED-TO-SLAB,FALSE-VALUE
	PRINTI	"As you untie "
	ICALL2	DPRINT,SIDEKICKS-BODY
	PRINTR	", it attempts to wrap its arms around you as though they were tentacles."
?CCL24:	PRINT	SENILITY-STRIKES
	RTRUE	
?CCL21:	ICALL2	DPRINT,SIDEKICKS-BODY
	PRINTR	" isn't tied down!"


	.FUNCT	ROCKY-CLIFFTOP-F,RARG
	EQUAL?	RARG,M-LOOK \?CCL3
	PRINTI	"Even the most adaptable Venusian flora can't gain a foothold on this outcropping, so the jungle (which can be entered to the north or west) peters out here. To the southeast, your clifftop vantage offers a stunning view of more lush jungle, stretching unbroken to the horizon.
   To the northwest, between the two paths into the jungle, is a vizicomm booth. At the edge of the cliff is"
	ICALL2	APRINT,HOLE
	PRINTC	46
	RTRUE	
?CCL3:	EQUAL?	RARG,M-END \FALSE
	ZERO?	GONE-APE /FALSE
	CALL2	JIGS-UP,STR?370
	RSTACK	


	.FUNCT	CLIFF-OBJECT-F
	EQUAL?	PRSA,V?LEAP-OFF \?CCL3
	SET	'PRSO,FALSE-VALUE
	CALL1	V-LEAP
	RSTACK	
?CCL3:	EQUAL?	PRSA,V?EXAMINE \FALSE
	CALL1	V-LOOK
	RSTACK	


	.FUNCT	BOOTH-OBJECT-F
	EQUAL?	PRSA,V?BOARD,V?WALK-TO,V?ENTER \?CCL3
	EQUAL?	HERE,ROCKY-CLIFFTOP \?CCL6
	CALL2	DO-WALK,P?NW
	RSTACK	
?CCL6:	EQUAL?	HERE,VIZICOMM-BOOTH \FALSE
	PRINT	LOOK-AROUND
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?DISEMBARK,V?EXIT,V?LEAVE \?CCL10
	EQUAL?	HERE,ROCKY-CLIFFTOP \?CCL13
	PRINT	LOOK-AROUND
	RTRUE	
?CCL13:	CALL2	DO-WALK,P?SE
	RSTACK	
?CCL10:	EQUAL?	PRSA,V?EXAMINE \?CCL15
	EQUAL?	HERE,VIZICOMM-BOOTH \?CCL15
	CALL1	V-LOOK
	RSTACK	
?CCL15:	EQUAL?	PRSA,V?SEARCH \?CCL19
	PRINT	NOTHING-NEW
	RTRUE	
?CCL19:	EQUAL?	PRSA,V?LOOK-INSIDE \FALSE
	EQUAL?	HERE,ROCKY-CLIFFTOP \FALSE
	PRINT	CANT-FROM-HERE
	RTRUE	


	.FUNCT	VIZICOMM-BOOTH-F,RARG
	EQUAL?	RARG,M-LOOK \?CCL3
	PRINTI	"This small booth, which opens to the southeast, contains"
	PRINT	VIZICOMM-DESC
	PRINTI	" A red sign is posted over the vizicomm."
	RTRUE	
?CCL3:	EQUAL?	RARG,M-END \FALSE
	ZERO?	GONE-APE /FALSE
	CALL2	VISIBLE?,FLEXIBLE-HOLE
	ZERO?	STACK /FALSE
	CALL2	ROCKY-CLIFFTOP-F,M-END
	RSTACK	


	.FUNCT	VIZICOMM-F
	EQUAL?	PRSA,V?EXAMINE \?CCL3
	PRINTI	"It's"
	PRINT	VIZICOMM-DESC
	CRLF	
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?SET \FALSE
	PRINTR	"The dial is stuck and won't turn."


	.FUNCT	DIAL-F
	EQUAL?	PRSA,V?MOVE,V?SET \?CCL3
	ICALL	PERFORM,V?SET,VIZICOMM
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?TAKE \FALSE
	PRINT	PART-OF-VIZICOMM
	RTRUE	


	.FUNCT	COIN-SLOT-F
	EQUAL?	PRSA,V?TAKE \?CCL3
	PRINT	PART-OF-VIZICOMM
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?LOOK-INSIDE \?CCL5
	PRINT	ONLY-BLACKNESS
	RTRUE	
?CCL5:	EQUAL?	PRSA,V?PUT \FALSE
	EQUAL?	PRSO,ONE-MARSMID-COIN,TEN-MARSMID-COIN \FALSE
	MOVE	PRSO,COIN-RETURN-KNOB
	PRINTR	"""Clink."""


	.FUNCT	HANDSET-F
	EQUAL?	PRSA,V?RAISE,V?LISTEN,V?PICK-UP /?CTR2
	EQUAL?	PRSA,V?PICK-UP \?CCL3
?CTR2:	PRINTR	"There's no dial tone."
?CCL3:	EQUAL?	PRSA,V?TAKE \FALSE
	PRINT	PART-OF-VIZICOMM
	RTRUE	


	.FUNCT	COIN-RETURN-KNOB-F,COIN
	EQUAL?	PRSA,V?SET,V?MOVE,V?PUSH \?CCL3
	FIRST?	COIN-RETURN-KNOB >COIN \?CCL6
	MOVE	COIN,COIN-RETURN-BOX
	PRINTR	"""Clank."""
?CCL6:	PRINT	NOTHING-HAPPENS
	RTRUE	
?CCL3:	EQUAL?	PRSA,V?TAKE \FALSE
	PRINT	PART-OF-VIZICOMM
	RTRUE	


	.FUNCT	COIN-RETURN-BOX-F,COIN
	EQUAL?	PRSA,V?SEARCH,V?REACH-IN,V?LOOK-INSIDE /?CCL3
	EQUAL?	PRSA,V?OPEN \FALSE
?CCL3:	FIRST?	COIN-RETURN-BOX >COIN \?CCL8
	MOVE	COIN,HERE
	ICALL2	THIS-IS-IT,COIN
	PRINTR	"A coin falls to the ground!"
?CCL8:	PRINTR	"The box is empty. Upon letting go, it swings shut."


	.FUNCT	GENERIC-COIN-F
	RETURN	ONE-MARSMID-COIN

	.ENDI
